### YamlMime:PowershellCmdlet
summary: |-
  Installs an SSL certificate for a federation server proxy.
module: WebApplicationProxy
notes: ""
links:
- text: Get-WebApplicationProxySslCertificate
  href: ./Get-WebApplicationProxySslCertificate.yml
syntaxes:
- Set-WebApplicationProxySslCertificate -Thumbprint <String> [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Configure a certificate for use'
  code: |-
    PS C:\> Set-WebApplicationProxySslCertificate -Thumbprint "FC85DDB0FC58E63D8CB52654F22E4BE7900FE349"
  description: |-
    This command installs the certificate specified by the thumbprint, and configures the certificate for use by the federation server proxy component.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Thumbprint
  isRequired: true
  description: |+
    Specifies the thumbprint of an X.509 certificate.
    This cmdlet sets the certificate that this parameter specifies as the AD FS SSL certificate that Web Application Proxy installs and configure for the federation server proxy component.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: WebApplicationProxy.Set-WebApplicationProxySslCertificate
name: Set-WebApplicationProxySslCertificate
description: |-
  The **Set-WebApplicationProxySslCertificate** cmdlet installs and configures an Active Directory Federation Services (AD FS) Secure Sockets Layer (SSL) certificate for the federation server proxy component of the Web Application Proxy.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IdentityServer.Management.Proxy.dll-Help.xml
  Module Name: WebApplicationProxy
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/webapplicationproxy/set-webapplicationproxysslcertificate?view=windowsserver2019-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-WebApplicationProxySslCertificate
