### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet retrieves the front end IP configuration of a load balancer resource from the Network Controller
module: NetworkController
notes: ""
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Following properties can be retrieved for front end IP configuration of load balancer resource:
    1. Private IP address (VIP)
    2. Private IP address allocation method: Static or dynamic
    3. Load balancing rules associated with the resource
    4. Inbound NAT rules associated with the resource
    5. Outbound NAT rules associated with the resource
    6. Subnet associated with the resource
    7. Access control list associated with the resource
    8. Service insertion rules associated with the resource
syntaxes:
- >-
  Get-NetworkControllerLoadBalancerFrontendIpConfiguration [-LoadBalancerId] <String[]>

   [[-ResourceId] <String[]>] -ConnectionUri <Uri> [-CertificateThumbprint <String>] [-Credential <PSCredential>]

   [-PassInnerException] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    Get-NetworkControllerLoadBalancerFrontEndIpconfiguration -ConnectionUri https://networkcontroller -LoadBalancerId lb1
  description: ""
  summary: |+
    This example retrieves all the front end IP resource associated with a load balancer resource named lb1

parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: CertificateThumbprint
  description: |+
    Specifies the digital public key X.509 certificate of a user account that has permission to perform this action.This is the certificate thumbprint of the certificate.This thumbprint must also be provided in the *ClientCertificateThumbprint* parameter in the **Install-NetworkController** or **Set-NetworkController** cmdlet so that Network Controller can authorize this user.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Uri" data-throw-if-not-resolved="False" />
  name: ConnectionUri
  isRequired: true
  description: |+
    Specifies the Uniform Resource Identifier (URI) of the Network Controller, used by all Representational State Transfer (REST) clients to connect to Network Controller.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: Credential
  description: |+
    Specifies a user credential that has permission to perform this action.The default value is the current user.This user must be present in the security group provided in the *ClientSecurityGroup* parameter in the **Install-NetworkController** cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: LoadBalancerId
  isRequired: true
  description: |+
    Specifies the load balancer where the resource belongs

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassInnerException
  description: ""
  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ResourceId
  description: |+
    Specifies the unique identifier of the resource

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
uid: NetworkController.Get-NetworkControllerLoadBalancerFrontendIpConfiguration
name: Get-NetworkControllerLoadBalancerFrontendIpConfiguration
description: |-
  This cmdlet retrieves the front end IP configuration of a load balancer resource from the Network Controller. The front-end IP is commonly referred to as a Virtual IP (VIP). The VIP must be taken from an unused IP in one of the logical network IP Pool which has been previously given to the load balancer manager.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.NetworkController.Powershell.dll-help.xml
  Module Name: NetworkController
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/networkcontroller/get-networkcontrollerloadbalancerfrontendipconfiguration?view=windowsserver2016-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-NetworkControllerLoadBalancerFrontendIpConfiguration
