### YamlMime:PowershellCmdlet
summary: |-
  This cmdlet sets the global configuration for virtual networking in the Network Controller.
module: NetworkController
notes: ""
inputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    Following properties can be changed:

    - Whether distributed router is enabled or disabled
    - Network virtualization mode (NVGRE/VXLAN)
syntaxes:
- >-
  Set-NetworkControllerVirtualNetworkConfiguration -ConnectionUri <Uri>

   -Properties <VirtualNetworkManagerProperties> -ResourceId <string> [-CertificateThumbPrint <string>]

   [-Credential <PSCredential>] [-Etag <string>] [-Force] [-ResourceMetadata <ResourceMetadata>]

   [-Tags <psobject>]
examples:
- title: Example 1
  code: |-
    $config=New-Object Microsoft.Windows.NetworkController.VirtualNetworkManagerProperties
    $config.NetworkVirtualizationProtocol="NVGRE"
    Set-NetworkControllerVirtualNetworkConfiguration -ConnectionUri https://networkcontroller -ResourceId vnetglobalconfig -Properties $config
  description: ""
  summary: |+
    This example set the network virtualization protocol of the virtual networks to NVGRE.

parameters:
- type: <xref href="string" data-throw-if-not-resolved="False" />
  name: CertificateThumbPrint
  description: |+
    Specifies the digital public key X.509 certificate of a user account that has permission to perform this action.
    This is the certificate thumbprint of the certificate.
    This thumbprint must also be provided in the ClientCertificateThumbprint parameter in the Install-NetworkController or Set-NetworkController cmdlet so that Network Controller can authorize this user.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Uri" data-throw-if-not-resolved="False" />
  name: ConnectionUri
  isRequired: true
  description: |+
    Specifies the Uniform Resource Identifier (URI) of the Network Controller, used by all Representational State Transfer (REST) clients to connect to Network Controller.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
  name: Credential
  description: |+
    Specifies a user credential that has permission to perform this action.
    The default value is the current user.This user must be present in the security group provided in the ClientSecurityGroup parameter in the Install-NetworkController cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="string" data-throw-if-not-resolved="False" />
  name: Etag
  description: |+
    Specifies the entity tag (ETag) parameter of the resource.
    An ETag (entity tag) is an HTTP response header returned by an HTTP-compliant web server used to determine change in the content of a resource at a given URL.
    The value of the header is an opaque string representing the state of the resource at the time the response was generated.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="switch" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the command to run without asking for user confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="VirtualNetworkManagerProperties" data-throw-if-not-resolved="False" />
  name: Properties
  isRequired: true
  description: |+
    Following properties can be changed:

    - Whether distributed router is enabled or disabled
    - Network virtualization mode (NVGRE/VXLAN)

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="string" data-throw-if-not-resolved="False" />
  name: ResourceId
  isRequired: true
  description: |+
    Specifies the unique identifier for the virtual network configuration

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ResourceMetadata" data-throw-if-not-resolved="False" />
  name: ResourceMetadata
  description: |+
    This parameter contains metadata information for the client, such as the tenant ID, group ID, and resource name.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="psobject" data-throw-if-not-resolved="False" />
  name: Tags
  description: |+
    @{Text=}

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: NetworkController.Set-NetworkControllerVirtualNetworkConfiguration
name: Set-NetworkControllerVirtualNetworkConfiguration
description: |-
  This cmdlet sets the global configuration for virtual networking in the Network Controller.
  With this, you can set the network virtualization protocol of the virtual network to VXLAN or NVGRE.
  The default is VXLAN
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.NetworkController.Powershell.dll-help.xml
  Module Name: NetworkController
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/networkcontroller/set-networkcontrollervirtualnetworkconfiguration?view=windowsserver2016-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-NetworkControllerVirtualNetworkConfiguration
