### YamlMime:PowershellCmdlet
summary: |-
  Removes a trigger application from a VPN connection object.
module: VpnClient
notes: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#VpnConnectionTriggerApplication" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-VpnConnectionTriggerApplication
  href: ./Add-VpnConnectionTriggerApplication.yml
syntaxes:
- >-
  Remove-VpnConnectionTriggerApplication [-ConnectionName] <String> [-ApplicationID] <String[]> [-PassThru]

   [-Force] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Remove a VPN connection trigger application'
  code: |-
    PS C:\> Remove-VpnConnectionTriggerApplication -ConnectionName "Contoso" -ApplicationID "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe","Microsoft.RemoteDesktop_Contoso0987" -PassThru -Force
    ConnectionName : Contoso

    ApplicationID  : {C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe, Microsoft.RemoteDesktop_Contoso0987}
  description: |-
    This command uses the Remove-VpnConnectionTriggerApplication cmdlet to remove the trigger applications by using the *ApplicationID* parameter.
    The command also specifies the *PassThru* and *Force* parameters.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ApplicationID
  isRequired: true
  description: |+
    Specifies an array of unique identifiers for an application.
    For legacy desktop applications, the application identifier is the application path.
    For modern applications, it is the Package Family Name of the application.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ConnectionName
  isRequired: true
  description: |+
    Specifies the name of a VPN connection profile.
    To view existing VPN connection profiles, use the Get-VpnConnection cmdlet.

    A VPN connection profile includes connection types, group policy settings, and names of authentication, authorization, and accounting servers.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: Name
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the command to run without asking for user confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.
    If you specify this parameter, the cmdlet returns the **VpnConnectionTriggerApplication** object that contains the applications configured for VPN trigger.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: VpnClient.Remove-VpnConnectionTriggerApplication
name: Remove-VpnConnectionTriggerApplication
description: |-
  The **Remove-VpnConnectionTriggerApplication** cmdlet removes a trigger application from a VPN connection object.
  After you remove an application from the VPN connection, when the client accesses that application, it no longer triggers the VPN connection.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: PS_VpnConnectionTriggerApplication_v1.0.cdxml-help.xml
  Module Name: VpnClient
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/vpnclient/remove-vpnconnectiontriggerapplication?view=windowsserver2019-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Remove-VpnConnectionTriggerApplication
