### YamlMime:PowershellCmdlet
summary: |-
  Sets the name of the network adapter, profile, and the profile source.
module: NetAdapter
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  description: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Set-NetAdapterDataPathConfiguration [-Name] <String[]> [-IncludeHidden] [-Profile <String>]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-PassThru] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Set-NetAdapterDataPathConfiguration -InterfaceDescription <String[]> [-IncludeHidden] [-Profile <String>]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-PassThru] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Set-NetAdapterDataPathConfiguration -InputObject <CimInstance[]> [-Profile <String>]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-PassThru] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Set the profile of a network adapter'
  code: |-
    PS> Set-NetAdapterDataPathConfiguration -Name "Ethernet" -Profile Legacy
  description: |-
    Sets the profile to **Legacy** for the network adapter named **Ethernet**.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job.
    Use this parameter to run commands that take a long time to complete. 
     The cmdlet immediately returns an object that represents the job and then displays the command prompt.
    You can continue to work in the session while the job completes.
    To manage the job, use the `*-Job` cmdlets.
    To get the job results, use the [Receive-Job](https://go.microsoft.com/fwlink/?LinkID=113372) cmdlet. 
     For more information about Windows PowerShell background jobs, see [about_Jobs](https://go.microsoft.com/fwlink/?LinkID=113251).

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: IncludeHidden
  description: |+
    Indicates that this cmdlet includes both visible and hidden network adapters. By
    default only visible network adapters are included. If a wildcard character is
    used in identifying a network adapter and this parameter has been specified,
    then the wildcard string is matched against both hidden and visible network
    adapters.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the input to this cmdlet.
    You can use this parameter, or you can pipe the input to this cmdlet.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InterfaceDescription
  isRequired: true
  description: |+
    Specifies an array of network adapter interface descriptions. For a physical
    network adapter this is typically the name of the vendor of the network adapter
    followed by a part number and description, such as
    `Contoso 12345 Gigabit Network Device`.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ifDesc, InstanceID
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Name
  isRequired: true
  description: |+
    Specifies an array of network adapter names.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ifAlias, InterfaceAlias
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Profile
  description: |+
    Name of one of the four built-in profiles for the operating system.

    The profile describes the datapath behavior of NDIS Poll Mode. NDIS Poll Mode is an operating system
    controlled polling execution model that drives the network interface datapath.

    Allowed values for this parameter are: 
    - Windows Server - **Dispatch** (default), **Balanced**, **Legacy mode**, and **Passive**.
    - Windows client - **Balanced** (default)

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to
    run the cmdlet. If this parameter is omitted or a value of `0` is entered, then
    Windows PowerShell calculates an optimum throttle limit for the cmdlet based on
    the number of CIM cmdlets that are running on the computer. The throttle limit
    applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: NetAdapter.Set-NetAdapterDataPathConfiguration
name: Set-NetAdapterDataPathConfiguration
description: |-
  The **Set-NetAdapterDataPathConfiguration** cmdlet sets the name of the network adapter, profile,
  and the profile source. The profile describes the datapath behavior of NDIS Poll Mode. NDIS Poll
  Mode is an operating system controlled polling execution model that drives the network interface
  datapath. Currently, Windows supports four built-in profiles for server and two built-in profiles
  for client. The built-in profiles can only be set using PowerShell.
metadata:
  description: Sets the name of the network adapter, profile, and the profile source.
  external help file: MSFT_NetAdapterDataPathConfiguration.cdxml-help.xml
  Module Name: NetAdapter
  ms.date: 09/22/2021
  online version: https://learn.microsoft.com/powershell/module/netadapter/set-netadapterdatapathconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-NetAdapterDataPathConfiguration
