### YamlMime:PowershellCmdlet
summary: |-
  Configures security settings for a virtual machine.
module: Hyper-V
notes: ""
links:
- text: Get-VMSecurity
  href: ./Get-VMSecurity.yml
syntaxes:
- >-
  Set-VMSecurity [-CimSession <CimSession[]>] [-ComputerName <String[]>] [-Credential <PSCredential[]>]

   [-VMName] <String[]> [-Passthru] [-EncryptStateAndVmMigrationTraffic <Boolean>]

   [-VirtualizationBasedSecurityOptOut <Boolean>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-VMSecurity [-VM] <VirtualMachine[]> [-Passthru] [-EncryptStateAndVmMigrationTraffic <Boolean>]

   [-VirtualizationBasedSecurityOptOut <Boolean>] [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ComputerName
  description: |+
    Specifies one or more Hyper-V hosts to run the cmdlet.
    NetBIOS names, IP addresses, and fully qualified domain names are allowable.
    The default is the local computer.
    Use localhost or a dot (.) to specify the local computer explicitly.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Credential
  description: |+
    Specifies a user account that has permission to perform this action.
    The default is the current user.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EncryptStateAndVmMigrationTraffic
  description: |+
    Indicates that this cmdlet enables encryption of virtual machine state and migration traffic.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Passthru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: VirtualizationBasedSecurityOptOut
  description: |+
    Specifies whether to opt the virtual machine out of virtualization-based security.
    Specify a value of $True to opt out of virtualization-based security.
    If the guest operating system supports virtualization-based security, a value of $False allows it.
    The default value is $False.

    To change this setting, the virtual machine must be off.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="VirtualMachine" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: VM
  isRequired: true
  description: |+
    Specifies an array of virtual machines.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: VMName
  isRequired: true
  description: |+
    Specifies an array of virtual machine names.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Hyper-V.Set-VMSecurity
name: Set-VMSecurity
description: |-
  The **Set-VMSecurity** cmdlet configures security settings for a virtual machine.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.HyperV.PowerShell.Cmdlets.dll-Help.xml
  Module Name: Hyper-V
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/hyper-v/set-vmsecurity?view=windowsserver2016-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-VMSecurity
