### YamlMime:PowershellCmdlet
summary: |-
  Gets the File History configurations settings for the server.
module: WssCmdlets
notes: ""
outputs:
- name: <xref href="PackageInfo" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Set-WssFileHistoryConfiguration
  href: ./Set-WssFileHistoryConfiguration.yml
- text: Get-WssFileHistoryManagementStatus
  href: ./Get-WssFileHistoryManagementStatus.yml
syntaxes:
- Get-WssFileHistoryConfiguration
examples:
- title: 'Example 1: Get the File History configurations settings'
  code: |-
    PS C:\> Get-WssFileHistoryConfiguration
  description: |-
    This command gets the File History configuration settings for the server.
  summary: ""
uid: WssCmdlets.Get-WssFileHistoryConfiguration
name: Get-WssFileHistoryConfiguration
description: |-
  The **Get-WssFileHistoryConfiguration** cmdlet gets the File History configuration settings for the server.
  You can use the Set-WssFileHistoryConfiguration cmdlet to change the File History configuration settings.
metadata:
  external help file: WSS_Cmdlets.xml
  Module Name: WssCmdlets
  online version: https://docs.microsoft.com/powershell/module/wsscmdlets/get-wssfilehistoryconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
