### YamlMime:PowershellCmdlet
summary: |-
  Gets file specifications from a volume that is part of a backup.
module: WssCmdlets
notes: ""
links:
- text: Add-WssBackupConfiguration
  href: ./Add-WssBackupConfiguration.yml
- text: New-WssBackupConfiguration
  href: ./New-WssBackupConfiguration.yml
- text: Remove-WssBackupConfiguration
  href: ./Remove-WssBackupConfiguration.yml
syntaxes:
- Get-WssBackupConfiguration [-Volume] <BackupVolume>
examples:
- title: 'Example 1: Get a backup file specification'
  code: |-
    PS C:\>$ContosoBUVolume13 = Get-WssBackupVolume -AllVolumes PS C:\>$ContosoBUFSpec15 = Get-WssBackupConfiguration -Volume $ContosoBUVolume13[0]
  description: |-
    This example gets a backup file specification from a volume.

    The first command gets the backup volumes from the server and stores them in the **$ContosoBUVolume13** variable.

    The second command gets the backup file specification from the first item (located in position 0) in $ContosoBUVolume13 and stores the backup file specification in the **$ContosoBUFSpec15** variable.
  summary: ""
parameters:
- type: <xref href="BackupVolume" data-throw-if-not-resolved="False" />
  name: Volume
  isRequired: true
  description: |+
    Specifies the volume to back up.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
uid: WssCmdlets.Get-WssBackupConfiguration
name: Get-WssBackupConfiguration
description: |-
  The **Get-WssBackupConfiguration** cmdlet gets file specifications from a volume that is part of a backup.
metadata:
  external help file: WSS_Cmdlets.xml
  Module Name: WssCmdlets
  online version: https://docs.microsoft.com/powershell/module/wsscmdlets/get-wssbackupconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
