### YamlMime:PowershellCmdlet
summary: |-
  Removes a file specification from a backup volume.
module: WssCmdlets
notes: ""
links:
- text: Add-WssBackupConfiguration
  href: ./Add-WssBackupConfiguration.yml
- text: Get-WssBackupConfiguration
  href: ./Get-WssBackupConfiguration.yml
- text: New-WssBackupConfiguration
  href: ./New-WssBackupConfiguration.yml
syntaxes:
- Remove-WssBackupConfiguration [-Volume] <BackupVolume> [-Configuration] <BackupFileSpec>
examples:
- title: 'Example 1: Remove a file specification from a backup volume'
  code: |-
    PS C:\>$ContosoBUVolume110 = Get-WssBackupVolume -AllVolumes PS C:\>$ContosoBUFilespec05 = Get-WssBackupConfiguration -Volume $ContosoBUVolume110[0] PS C:\>Remove-WssBackupConfiguration -Configuration $ContosoBUFilespec05[1]
  description: |-
    This command removes the backup file specification from a backup volume.

    The first command gets the backup volumes from the server and stores them in the variable named $ContosoBUVolume110.

    The second command gets the backup file specification from the first item (located in position 0) in $ContosoBUVolume110 and stores the backup file specification in the variable named $ContosoBUFilespec05.

    The third command removes the backup file specification from the second item (located in position 1) in $ContosoBUFilespec05.
  summary: ""
parameters:
- type: <xref href="BackupFileSpec" data-throw-if-not-resolved="False" />
  name: Configuration
  isRequired: true
  description: |+
    Specifies the backup file specification to remove from the volume.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: Config
  parameterValueGroup: ""
- type: <xref href="BackupVolume" data-throw-if-not-resolved="False" />
  name: Volume
  isRequired: true
  description: |+
    Specifies the volume from which to remove the file specification.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
uid: WssCmdlets.Remove-WssBackupConfiguration
name: Remove-WssBackupConfiguration
description: |-
  The **Remove-WssBackupConfiguration** cmdlet removes a file specification from a backup volume.
  When you remove a file specification from a backup volume, the files and folders in the file specification are no longer backed up with the backup volume.
metadata:
  external help file: WSS_Cmdlets.xml
  Module Name: WssCmdlets
  online version: https://docs.microsoft.com/powershell/module/wsscmdlets/remove-wssbackupconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
