### YamlMime:PowershellCmdlet
summary: |-
  Copies the current user's international settings (Windows Display language, Input language, Regional Format/locale, and Location/GeoID) to one or both of the following:
  * Welcome screen and system accounts
  * New user accounts

  **Important:** Note that this PowerShell cmdlet is only available for Windows 11 and later.

  This is a system setting. It can only be changed by a user who has Administrator permissions. Changes take effect after the computer is restarted.
module: International
syntaxes:
- Copy-UserInternationalSettingsToSystem [-WelcomeScreen <Boolean>] [-NewUser <Boolean>] [<CommonParameters>]
examples:
- title: 'Example 1: Copy settings into both the Welcome screen and system accounts, and new user accounts'
  code: |-
    PS C:\> Copy-UserInternationalSettingsToSystem -WelcomeScreen $True -NewUser $True
  description: |-
    This example copies the Windows Display language, Input language, Regional Format/locale, and Location/GeoID into both the Welcome screen and system accounts, and new user accounts.
  summary: ""
- title: 'Example 2: Copy the settings into only the Welcome screen and system accounts'
  code: |-
    PS C:\> Copy-UserInternationalSettingsToSystem -WelcomeScreen $True -NewUser $False
  description: |-
    This example copies the Windows Display language, Input language, Format/locale, and Regional Location/GeoID to the Welcome screen and system accounts only.
  summary: ""
parameters:
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: NewUser
  isRequired: true
  description: |+
    Copies the settings into the new user accounts.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: WelcomeScreen
  isRequired: true
  description: |+
    Copies the settings into the Welcome screen and system accounts.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: International.Copy-UserInternationalSettingsToSystem
name: Copy-UserInternationalSettingsToSystem
description: |-
  The **Copy-UserInternationalSettingsToSystem** cmdlet gets the **international settings** from the current user.
  You can decide whether to copy these settings into the **Welcome screen and system accounts**, the **New user accounts**, or both.

  This cmdlet takes two parameters: **-WelcomeScreen** and **-NewUser**.

  When any of the parameters is set to $True, this cmdlet gets the current values from the current user and copies them to the system settings for the selected options based on the parameters that were set to $True.
metadata:
  ms.mktglfcycl: manage
  ms.sitesec: library
  ms.author: ertorres
  author: erik0686
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.InternationalSettings.Commands.dll-Help.xml
  keywords: powershell, cmdlet
  manager: aandrejs
  ms.date: 09/08/2021
  ms.prod: w11
  ms.technology: ""
  ms.topic: reference
  online version: ""
  schema: 2.0.0
  title: Copy-UserInternationalSettingsToSystem
  ms.reviewer: ""
  ms.assetid: ""
