### YamlMime:PowershellCmdlet
summary: |-
  Disables the NAT64 configuration on a computer.
module: NetworkTransition
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root\StandardCimv2\MSFT_NetNatTransitionConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The `Microsoft.Management.Infrastructure.CimInstance` object is a wrapper class that displays Windows Management Instrumentation (WMI) objects.
    The path after the pound sign (`#`) provides the namespace and class name for the underlying WMI object.
links:
- text: Enable-NetNatTransitionConfiguration
  href: ./Enable-NetNatTransitionConfiguration.yml
- text: Get-NetNatTransitionConfiguration
  href: ./Get-NetNatTransitionConfiguration.yml
- text: Get-NetNatTransitionMonitoring
  href: ./Get-NetNatTransitionMonitoring.yml
- text: New-NetNatTransitionConfiguration
  href: ./New-NetNatTransitionConfiguration.yml
- text: Remove-NetNatTransitionConfiguration
  href: ./Remove-NetNatTransitionConfiguration.yml
- text: Set-NetNatTransitionConfiguration
  href: ./Set-NetNatTransitionConfiguration.yml
syntaxes:
- >-
  Disable-NetNatTransitionConfiguration [-Adapter <CimInstance>] [-AsJob] [-CimSession <CimSession[]>]

   [-InstanceName <String[]>] [-PassThru] [-PolicyStore <PolicyStore[]>] [-ThrottleLimit <Int32>] [-Confirm]

   [-WhatIf]
- >-
  Disable-NetNatTransitionConfiguration [-AsJob] [-CimSession <CimSession[]>] [-PassThru]

   [-ThrottleLimit <Int32>] -InputObject <CimInstance[]> [-Confirm] [-WhatIf]
examples:
- title: EXAMPLE 1
  code: |-
    PS C:\>Disable-NetNatTransitionConfiguration
  description: |-
    This example makes the NAT64 configuration ineffective.
  summary: ""
parameters:
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" />
  name: Adapter
  description: |+
    Specifies the network adapter on which to disable the NAT64.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    ps_cimcommon_asjob

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a New-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227967 or Get-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227966 cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the NAT64 configuration object to disable.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InstanceName
  description: |+
    Specifies the instance of the NAT64 for which the configuration will be made ineffective.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PolicyStore" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PolicyStore
  description: |+
    Specifies to which policy store the NAT64 configuration is applied.
    The acceptable values for this parameter are: Persistent and Active.
    If this parameter is not specified, then the cmdlet operates on both active and persistent stores.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: Store
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: NetworkTransition.Disable-NetNatTransitionConfiguration
name: Disable-NetNatTransitionConfiguration
description: |-
  The **Disable-NetNatTransitionConfiguration** makes the NAT64 configuration ineffective on a computer.
metadata:
  external help file: NetTransition_Cmdlets.xml
  Module Name: NetworkTransition
  online version: https://docs.microsoft.com/powershell/module/networktransition/disable-netnattransitionconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
