### YamlMime:PowershellCmdlet
summary: |-
  Renames an IP-HTTPS profile.
module: NetworkTransition
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet accepts no input objects.
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root\StandardCimv2\MSFT_NetIPHttpsConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The `Microsoft.Management.Infrastructure.CimInstance` object is a wrapper class that displays Windows Management Instrumentation (WMI) objects.
    The path after the pound sign (`#`) provides the namespace and class name for the underlying WMI object.

    When the **Passthru** parameter is specified, this cmdlet outputs a modified Windows Management Instrumentation (WMI) object.
links:
- text: Get-NetIPHttpsConfiguration
  href: ./Get-NetIPHttpsConfiguration.yml
- text: New-NetIPHttpsConfiguration
  href: ./New-NetIPHttpsConfiguration.yml
- text: Remove-NetIPHttpsConfiguration
  href: ./Remove-NetIPHttpsConfiguration.yml
- text: Reset-NetIPHttpsConfiguration
  href: ./Reset-NetIPHttpsConfiguration.yml
- text: Set-NetIPHttpsConfiguration
  href: ./Set-NetIPHttpsConfiguration.yml
syntaxes:
- >-
  Rename-NetIPHttpsConfiguration [-AsJob] [-CimSession <CimSession[]>] [-PassThru] [-PolicyStore <String>]

   [-Profile <String[]>] [-ProfileActivated <Boolean[]>] [-ThrottleLimit <Int32>] -NewName <String> [-Confirm]

   [-WhatIf]
- >-
  Rename-NetIPHttpsConfiguration [-AsJob] [-CimSession <CimSession[]>] [-GPOSession <String>] [-PassThru]

   [-Profile <String[]>] [-ProfileActivated <Boolean[]>] [-ThrottleLimit <Int32>] -NewName <String> [-Confirm]

   [-WhatIf]
- >-
  Rename-NetIPHttpsConfiguration [-AsJob] [-CimSession <CimSession[]>] [-PassThru] [-ThrottleLimit <Int32>]

   -InputObject <CimInstance[]> -NewName <String> [-Confirm] [-WhatIf]
examples:
- title: 'Example 1: Rename an IP-HTTPS profile using a configuration object'
  code: |-
    PS C:\>$config = Get-NetIPHttpsConfiguration -PolicyStore "testdomain\GPOName"



    PS C:\>Rename-NetIPHttpsConfiguration -InputObject $config
  description: |-
    This set of commands uses the Get-NetIPHttpsConfiguration cmdlet to get an IP-HTTPS configuration object and stores it in a variable named $config.
    The contents of the variable are then passed to this cmdlet.
  summary: ""
- title: 'Example 2: Rename an IP-HTTPS profile'
  code: |-
    PS C:\>Rename-NetIPHttpsConfiguration -Profile Redmond -NewName Fareast
  description: |-
    This command renames the IP-HTTPS profile named **Redmond** to **Fareast**.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    ps_cimcommon_asjob

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a New-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227967 or Get-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227966 cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GPOSession
  description: |+
    Specifies the Group Policy session which contains the IP-HTTPS configuration to rename. 

    You can use this parameter with the **NetGPO** cmdlets to aggregate multiple operations performed on a GPO. 

    You cannot use this parameter with the **PolicyStore** parameter.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the object which contains an IP-HTTPS profile to rename.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: NewName
  isRequired: true
  description: |+
    Specifies the new name for the IP-HTTPS profile.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PolicyStore
  description: |+
    Specifies the policy store that contains the configuration profile to rename. 
    The acceptable values for this parameter are:

     -- GPO 

    To rename the configuration profile of a GPO, specify the GPO name using the following format: `Domain\GPOName`

    You cannot use this parameter with the **GPOSession** parameter.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Profile
  description: |+
    Specifies the name of the profile to rename.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: IPHttpsProfile
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ProfileActivated
  description: |+
    Specifies which profile to rename.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: NetworkTransition.Rename-NetIPHttpsConfiguration
name: Rename-NetIPHttpsConfiguration
description: |-
  The **Rename-NetIPHttpsConfiguration** cmdlet renames an IP-HTTPS profile, either on a computer or in a Group Policy Object (GPO).
metadata:
  external help file: NetTransition_Cmdlets.xml
  Module Name: NetworkTransition
  online version: https://docs.microsoft.com/powershell/module/networktransition/rename-netiphttpsconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
