### YamlMime:PowershellCmdlet
summary: |-
  Resets the Teredo configuration elements in a Group Policy Object (GPO).
module: NetworkTransition
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet accepts no input objects.
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root\StandardCimv2\MSFT_NetTeredoConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The `Microsoft.Management.Infrastructure.CimInstance` object is a wrapper class that displays Windows Management Instrumentation (WMI) objects.
    The path after the pound sign (`#`) provides the namespace and class name for the underlying WMI object.

    When the **Passthru** parameter is specified, this cmdlet outputs a modified Windows Management Instrumentation (WMI) object.
links:
- text: Get-NetTeredoConfiguration
  href: ./Get-NetTeredoConfiguration.yml
- text: Set-NetTeredoConfiguration
  href: ./Set-NetTeredoConfiguration.yml
syntaxes:
- >-
  Reset-NetTeredoConfiguration [-AsJob] [-CimSession <CimSession[]>] [-ClientPort] [-DefaultQualified]

   [-GPOSession <String>] [-IPInterface <CimInstance>] [-PassThru] [-PolicyStore <String>]

   [-RefreshIntervalSeconds] [-ServerName] [-ServerShunt] [-ServerVirtualIP] [-ThrottleLimit <Int32>] [-Type]

   [-Confirm] [-WhatIf]
- >-
  Reset-NetTeredoConfiguration [-AsJob] [-CimSession <CimSession[]>] [-ClientPort] [-DefaultQualified]

   [-PassThru] [-RefreshIntervalSeconds] [-ServerName] [-ServerShunt] [-ServerVirtualIP] [-ThrottleLimit <Int32>]

   [-Type] -InputObject <CimInstance[]> [-Confirm] [-WhatIf]
examples:
- title: 'Example 1: Reset the Teredo configuration'
  code: |-
    PS C:\>Reset-NetTeredoConfiguration
  description: |-
    This command resets the Teredo configuration to the not configured state.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    ps_cimcommon_asjob

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a New-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227967 or Get-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227966 cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ClientPort
  description: |+
    Resets the UDP port of the client to not configured.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DefaultQualified
  description: |+
    Resets the Teredo qualification configuration to false.
    This parameter can only be specified on GPOs.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GPOSession
  description: |+
    Specifies the Group Policy session that contains the Teredo configuration to reset. 

    You can use this parameter with the **NetGPO** cmdlets to aggregate multiple operations performed on a GPO. 

    You cannot use this parameter with the **PolicyStore** parameter.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the object which contains the Teredo configuration information to reset.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" />
  name: IPInterface
  description: |+
    Specifies the interface on which to reset the Teredo configuration.
    If the interface specified is not a Teredo interface, then the cmdlet does not return any configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PolicyStore
  description: |+
    Specifies the policy store that contains the Teredo configuration to reset. 
    The acceptable values for this parameter are:

     -- PersistentStore 

     -- ActiveStore 

     -- GPO 

    To reset the configuration of a GPO, specify the GPO name using the following format: `Domain\GPOName`

    You cannot use this parameter with the **GPOSession** parameter.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: RefreshIntervalSeconds
  description: |+
    Resets the client refresh interval to 30 (seconds).

  defaultValue: None
  position: Named
  aliases: RefreshInterval
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ServerName
  description: |+
    Resets the server name to teredo.ipv6.contoso.com.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ServerShunt
  description: |+
    Resets the server shunt configuration to False.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ServerVirtualIP
  description: |+
    Resets the IPv4 address of the Teredo configuration to 0.0.0.0.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Type
  description: |+
    Resets the type of the Teredo configuration to default.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: NetworkTransition.Reset-NetTeredoConfiguration
name: Reset-NetTeredoConfiguration
description: |-
  The **Reset-NetTeredoConfiguration** cmdlet resets the Teredo configuration elements in a Group Policy Object (GPO) configurations to the not configured state.
  Group Policy settings have three possible states: not configured, enabled, and disabled.

  If used with no parameters, this cmdlet resets all Teredo configurations on the specified store.
metadata:
  external help file: NetTransition_Cmdlets.xml
  Module Name: NetworkTransition
  online version: https://docs.microsoft.com/powershell/module/networktransition/reset-netteredoconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
