### YamlMime:PowershellCmdlet
summary: |-
  Sets the DNS64 configuration on a computer.
module: NetworkTransition
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root\StandardCimv2\MSFT_NetDnsTransitionConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The `Microsoft.Management.Infrastructure.CimInstance` object is a wrapper class that displays Windows Management Instrumentation (WMI) objects.
    The path after the pound sign (`#`) provides the namespace and class name for the underlying WMI object.
links:
- text: Disable-NetDnsTransitionConfiguration
  href: ./Disable-NetDnsTransitionConfiguration.yml
- text: Enable-NetDnsTransitionConfiguration
  href: ./Enable-NetDnsTransitionConfiguration.yml
- text: Get-NetDnsTransitionConfiguration
  href: ./Get-NetDnsTransitionConfiguration.yml
- text: Get-NetDnsTransitionMonitoring
  href: ./Get-NetDnsTransitionMonitoring.yml
- text: Reset-NetDnsTransitionConfiguration
  href: ./Reset-NetDnsTransitionConfiguration.yml
syntaxes:
- >-
  Set-NetDnsTransitionConfiguration [-AcceptInterface <String[]>] [-Adapter <CimInstance>]

   [-AlwaysSynthesize <Boolean>] [-AsJob] [-CimSession <CimSession[]>] [-ExclusionList <String[]>]

   [-LatencyMilliseconds <UInt32>] [-OnlySendAQuery <Boolean>] [-PassThru] [-PrefixMapping <String[]>]

   [-SendInterface <String[]>] [-State <State>] [-ThrottleLimit <Int32>] [-Confirm] [-WhatIf]
- >-
  Set-NetDnsTransitionConfiguration [-AcceptInterface <String[]>] [-AlwaysSynthesize <Boolean>] [-AsJob]

   [-CimSession <CimSession[]>] [-ExclusionList <String[]>] [-LatencyMilliseconds <UInt32>]

   [-OnlySendAQuery <Boolean>] [-PassThru] [-PrefixMapping <String[]>] [-SendInterface <String[]>]

   [-State <State>] [-ThrottleLimit <Int32>] -InputObject <CimInstance[]> [-Confirm] [-WhatIf]
examples:
- title: EXAMPLE 1
  code: |-
    PS C:\>Set-NetDnsTransitionConfiguration -State Enabled -Latencymilliseconds 400
  description: |-
    This example sets the state to enabled and latency to 400 ms for the DNS64 configuration.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: AcceptInterface
  description: |+
    Specifies the interface on which the DNS64 is listening to all of the interfaces classified in the domain profile.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" />
  name: Adapter
  description: |+
    Specifies the network adapter on which to set.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AlwaysSynthesize
  description: |+
    Specifies that the DNS64 will always send both the response to the AAAA query as well as the synthesized A query response.
    If this parameter is set to False, then the DNS64 will send neither the response to the AAAA query nor the synthesized A query response.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    ps_cimcommon_asjob

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a New-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227967 or Get-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227966 cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ExclusionList
  description: |+
    Sets the list of IPv6 address ranges to be excluded from synthesis by the DNS64.
    The format is a comma-separated list of IPv6 addresses ranges.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the DNS64 configuration object on which to set.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: LatencyMilliseconds
  description: |+
    Sets the delay in milliseconds between the AAAA and A query that the DNS64 sends.

  defaultValue: None
  position: Named
  aliases: Latency
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: OnlySendAQuery
  description: |+
    Specifies that only A queries should be sent or both A and AAAA queries should be sent.
    If this parameter is set to True, then only A queries should be sent.
    If this parameter is set to False, then both A and AAAA queries should be sent.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PrefixMapping
  description: |+
    Sets to the list of IPv6 address ranges to be used for synthesis by the DNS64.
    The format is a comma-separated list of \<IPv6 prefix,IPv4 subnet\>.
    Such as `"69:FF9B::/96,0.0.0.0/0","66:FF9B::/96,192.2.0.0/8"`.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: SendInterface
  description: |+
    Sets the interface on which the DNS64 sends DNS queries.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="State" data-throw-if-not-resolved="False" />
  name: State
  description: |+
    Sets the enabled state of the DNS64 configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: NetworkTransition.Set-NetDnsTransitionConfiguration
name: Set-NetDnsTransitionConfiguration
description: |-
  The **Set-NetDnsTransitionConfiguration** sets the DNS64 configuration on a computer.
metadata:
  external help file: NetTransition_Cmdlets.xml
  Module Name: NetworkTransition
  online version: https://docs.microsoft.com/powershell/module/networktransition/set-netdnstransitionconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
