### YamlMime:PowershellCmdlet
summary: |-
  Restores configuration for a network switch.
module: NetworkSwitchManager
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet does not generate any output.
links:
- text: Save-NetworkSwitchConfiguration
  href: ./Save-NetworkSwitchConfiguration.yml
syntaxes:
- Restore-NetworkSwitchConfiguration [-CimSession] <CimSession> [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Restore the configuration for a network switch'
  code: |-
    PS C:\>$Session = New-CimSession -ComputerName "NetworkSwitch08"
    PS C:\> Restore-NetworkSwitchConfiguration -CimSession $Session
  description: |-
    The first command creates a **CimSession** for a network switch, and then stores it in the **$Session** variable.
    For more information about **CimSession** objects, type `Get-Help New-CimSession`.

    The second command restores the configuration from the last saved configuration for NetworkSwitch08 by using the **$Session** object.
  summary: ""
parameters:
- type: <xref href="CimSession" data-throw-if-not-resolved="False" />
  name: CimSession
  isRequired: true
  description: |+
    Specifies the **CimSession** that this cmdlet uses to connect to the network switch.
    For more information about **CimSession** objects, type `Get-Help New-CimSession`.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: NetworkSwitchManager.Restore-NetworkSwitchConfiguration
name: Restore-NetworkSwitchConfiguration
description: |-
  The **Restore-NetworkSwitchConfiguration** cmdlet restores configuration for a network switch to the last saved startup configuration.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: NetworkSwitchConfiguration-help.xml
  Module Name: NetworkSwitchManager
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/networkswitchmanager/restore-networkswitchconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Restore-NetworkSwitchConfiguration
