### YamlMime:PowershellCmdlet
summary: |-
  Resets a configuration for NCSI.
module: NetworkConnectivityStatus
notes: ""
inputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root/StandardCimv2/MSFT_NCSIPolicyConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The `Microsoft.Management.Infrastructure.CimInstance` object is a wrapper class that displays Windows Management Instrumentation (WMI) objects.
    The path after the pound sign (`#`) provides the namespace and class name for the underlying WMI object.
outputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-DAConnectionStatus
  href: ./Get-DAConnectionStatus.yml
- text: Get-NCSIPolicyConfiguration
  href: ./Get-NCSIPolicyConfiguration.yml
- text: Set-NCSIPolicyConfiguration
  href: ./Set-NCSIPolicyConfiguration.yml
syntaxes:
- >-
  Reset-NCSIPolicyConfiguration [-PolicyStore <String>] [-GPOSession <String>] [-CorporateDNSProbeHostAddress]

   [-CorporateDNSProbeHostName] [-CorporateSitePrefixList] [-CorporateWebsiteProbeURL]

   [-DomainLocationDeterminationURL] [-PassThru] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Reset-NCSIPolicyConfiguration -InputObject <CimInstance[]> [-CorporateDNSProbeHostAddress]

   [-CorporateDNSProbeHostName] [-CorporateSitePrefixList] [-CorporateWebsiteProbeURL]

   [-DomainLocationDeterminationURL] [-PassThru] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob]

   [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Reset NCSI configuration'
  code: |-
    This command resets the NCSI configuration of the specified GPO.
    PS C:\>Reset-NCSIPolicyConfiguration -PolicyStore "contoso\davidchew"


    This command performs an identical operation using the pipeline operator.
    PS C:\> Get-NCSIPolicyConfiguration -PolicyStore "contoso\davidchew" | Reset-NCSIPolicyConfiguration
  description: |-
    This example resets the NCSI configuration of a specified GPO in two ways.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete. 

    The cmdlet immediately returns an object that represents the job and then displays the command prompt. 
    You can continue to work in the session while the job completes. 
    To manage the job, use the `*-Job` cmdlets. 
    To get the job results, use the [Receive-Job](https://go.microsoft.com/fwlink/?LinkID=113372) cmdlet. 

    For more information about Windows PowerShell background jobs, see [about_Jobs](https://go.microsoft.com/fwlink/?LinkID=113251).

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: CorporateDNSProbeHostAddress
  description: |+
    Specifies that the specified policy store will no longer configure the corporate DNS probe host address.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: CorporateDNSProbeHostName
  description: |+
    Specifies that the specified policy store will no longer configure the corporate DNS probe host name.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: CorporateSitePrefixList
  description: |+
    Specifies that the specified policy store will no longer configure the corporate site prefix list.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: CorporateWebsiteProbeURL
  description: |+
    Specifies that the specified policy store will no longer configure the corporate website probe URL.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DomainLocationDeterminationURL
  description: |+
    Specifies that the specified policy store will no longer configure the domain location determination URL.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GPOSession
  description: |+
    Specifies a GPO session as the store for this cmdlet.

    Using this parameter will allow an aggregate of multiple cmdlets to run against a local GPO cache.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the input to this cmdlet. 
    You can use this parameter, or you can pipe the input to this cmdlet.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PolicyStore
  description: |+
    Specifies the logical store for the management operation.
    An example is the local persistent store or a Group Policy Object.
    The acceptable values for this parameter are:

    - `Domain\GPOName`
    - `ComputerName`

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: NetworkConnectivityStatus.Reset-NCSIPolicyConfiguration
name: Reset-NCSIPolicyConfiguration
description: |-
  The **Reset-NCSIPolicyConfiguration** cmdlet resets a configuration for NCSI.
  There is a GPO that configures NCSI.
  Return that GPO to a not configured state.
  To do that, use this cmdlet to reset the fields that no longer need to be configured.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: MSFT_NCSIPolicyConfiguration.cdxml-help.xml
  Module Name: NetworkConnectivityStatus
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/networkconnectivitystatus/reset-ncsipolicyconfiguration?view=windowsserver2019-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Reset-NCSIPolicyConfiguration
