### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the current volume backup performance settings.
module: WindowsServerBackup
notes: ""
inputs:
- name: <xref href="SwitchParameter, WBVolume" data-throw-if-not-resolved="False" />
  description: |-
    Indicates either global settings or volume settings.
links:
- text: Set-WBPerformanceConfiguration
  href: ./Set-WBPerformanceConfiguration.yml
syntaxes:
- Get-WBPerformanceConfiguration [-OverallPerformanceSetting]
- Get-WBPerformanceConfiguration [-Volume] <WBVolume>
examples:
- title: Example 1:Retrieve global settings
  code: |-
    PS C:\> Get-WBPerformanceSetting -OverallPerformanceSetting AlwaysIncremental
  description: |-
    This example retrieves the global settings for all volumes with the AlwaysIncremental setting.
  summary: ""
- title: 'Example 2: Retrieve settings for a volume'
  code: |-
    PS C:\>$Backup = Get-WBBackupSet PS C:\> Get-WBPerformanceSetting -Volume $Backup.Volume[1] AlwaysFull
  description: |-
    This example retrieves the settings for a specific volume with the AlwaysFull setting.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: OverallPerformanceSetting
  isRequired: true
  description: |+
    If specified, indicates that the returned data is to be for the global setting.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="WBVolume" data-throw-if-not-resolved="False" />
  name: Volume
  isRequired: true
  description: |+
    Specifies the **WBVolume** object for which the current performance settings are retrieved.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
uid: WindowsServerBackup.Get-WBPerformanceConfiguration
name: Get-WBPerformanceConfiguration
description: |-
  The **Get-WBPerformanceSetting** cmdlet retrieves the current performance settings for volume backups.
  The settings are applicable only for volume backups; these settings are not applicable for files, folders, system state, or applications.
  The settings apply globally to all volumes in a backup, or to specific volumes.
  The valid settings are: 

  - AlwaysFull:  The time to create a backup is proportional to the size of volume being backed up.
  This setting applies at a global level for all volumes or for specific volumes. 

  - AlwaysIncremental:  Increase the backup speed by just tracking the changes between the last and current backup.
  This option is not recommended for servers with disk-intensive operation which may experience reduced disk throughput on volumes included in the backup.
  This can be set at a global level for all volumes or specific for some volumes. 

  - Custom:  This is the global setting reported in case there is a specific volume level setting set.
metadata:
  external help file: WSBackup_Cmdlets.xml
  Module Name: WindowsServerBackup
  online version: https://docs.microsoft.com/powershell/module/windowsserverbackup/get-wbperformanceconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
