### YamlMime:PowershellCmdlet
summary: |-
  Sets the binding to the AD FS SSL certificate that is installed and configured for the FS proxy component of the Web Application Proxy.
module: WebApplicationProxy
notes: ""
syntaxes:
- Set-WebApplicationProxySslCertificate -Thumbprint <String> [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\> Set-WebApplicationProxySslCertificate -Thumbprint FC85DDB0FC58E63D8CB52654F22E4BE7900FE349
  description: |-
    This example installs the certificate specified by the thumbprint and configures for use by the FS proxy component.
  summary: ""
- title: '1:'
  code: |-
    PS C:\>
  description: ""
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Thumbprint
  isRequired: true
  description: |+
    The thumbprint of the x.509 certificate the administrator wishes to set as the AD FS SSL certificate that is installed and configured for the FS proxy component of the Web Application Proxy.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: WebApplicationProxy.Set-WebApplicationProxySslCertificate
name: Set-WebApplicationProxySslCertificate
description: |-
  Sets the binding to the AD FS SSL certificate that is installed and configured for the FS proxy component of the Web Application Proxy.
metadata:
  external help file: Microsoft.IdentityServer.Management.Proxy.dll-Help.xml
  Module Name: WebApplicationProxy
  ms.date: 12/05/2017
  online version: https://docs.microsoft.com/powershell/module/webapplicationproxy/set-webapplicationproxysslcertificate?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-WebApplicationProxySslCertificate
