### YamlMime:PowershellCmdlet
summary: |-
  Resets the Server Message Block (SMB) client configuration parameters to their default values.
module: SmbShare
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-SmbClientConfiguration
  href: ./Get-SmbClientConfiguration.yml
- text: Set-SmbClientConfiguration
  href: ./Set-SmbClientConfiguration.yml
syntaxes:
- >-
  Reset-SmbClientConfiguration [-All] [-CompressibilitySampling]

   [-ConnectionCountPerRssNetworkInterface] [-DirectoryCacheEntriesMax] [-DirectoryCacheEntrySizeMax]

   [-DirectoryCacheLifetime] [-DisableCompression] [-DormantFileLimit] [-EnableBandwidthThrottling]

   [-EnableByteRangeLockingOnReadOnlyFiles] [-EnableLargeMtu] [-EnableLoadBalanceScaleOut]

   [-EnableMultiChannel] [-EncryptionCiphers] [-ExtendedSessionTimeout] [-FileInfoCacheEntriesMax]

   [-FileInfoCacheLifetime] [-FileNotFoundCacheEntriesMax] [-FileNotFoundCacheLifetime]

   [-ForceSMBEncryptionOverQuic] [-KeepConn] [-MaxCmds] [-MaximumConnectionCountPerServer]

   [-OplocksDisabled] [-RequestCompression] [-SessionTimeout] [-SkipCertificateCheck]

   [-UseOpportunisticLocking] [-WindowSizeThreshold] [-Force] [-CimSession <CimSession[]>]

   [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Reset the large MTU behavior'
  code: |-
    Reset-SmbClientConfiguration -EnableLargeMtu -Confirm:$false
  description: |-
    This commands resets only the large MTU behavior to its default value without user confirmation.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    Resets all the SMB client configuration parameters to their default values.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to
    complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer. Enter a computer name or a session
    object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967)
    or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet. The default is the
    current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: CompressibilitySampling
  description: |+
    Resets the compression sampling behavior to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ConnectionCountPerRssNetworkInterface
  description: |+
    Resets the SMB connection count for each RSS network interface to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DirectoryCacheEntriesMax
  description: |+
    Resets the maximum cache entries that can be in the directory cache to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DirectoryCacheEntrySizeMax
  description: |+
    Resets the maximum size of directory cache entry value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DirectoryCacheLifetime
  description: |+
    Resets the directory cache lifetime to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DisableCompression
  description: |+
    Resets the SMB compression behavior to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: DormantFileLimit
  description: |+
    Resets the dormant file limit to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: EnableBandwidthThrottling
  description: |+
    Resets the bandwidth throttling behavior to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: EnableByteRangeLockingOnReadOnlyFiles
  description: |+
    Resets the enabled byte range locking behavior on read-only file to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: EnableLargeMtu
  description: |+
    Resets the enable large MTU value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: EnableLoadBalanceScaleOut
  description: |+
    Resets the enable load balance scale out value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: EnableMultiChannel
  description: |+
    Resets the enable multi-channel value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: EncryptionCiphers
  description: |+
    Resets the encryption ciphers used by the SMB client to its default value and order.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ExtendedSessionTimeout
  description: |+
    Resets the extended session time-out value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: FileInfoCacheEntriesMax
  description: |+
    Resets the maximum number entries that can be in the file information cache to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: FileInfoCacheLifetime
  description: |+
    Resets the file information cache lifetime value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: FileNotFoundCacheEntriesMax
  description: |+
    Resets the maximum number entries that can be in the file not found cache to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: FileNotFoundCacheLifetime
  description: |+
    Resets the file not found cache lifetime value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the command to run without asking for user confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ForceSMBEncryptionOverQuic
  description: |+
    Resets the for SMB encryption over QUIC value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: KeepConn
  description: |+
    Reset the time, in seconds, before the SMB client session is automatically disconnected to its
    default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: MaxCmds
  description: |+
    Resets the maximum number of concurrent outstanding network requests that the SMB client supports to
    its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: MaximumConnectionCountPerServer
  description: |+
    Resets the maximum connection count per server to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: OplocksDisabled
  description: |+
    Resets the opportunistic locks disabled value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: RequestCompression
  description: |+
    Resets the SMB client request compression value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SessionTimeout
  description: |+
    Resets the session time-out value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SkipCertificateCheck
  description: |+
    Resets the skip certificate check value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet. If
    this parameter is omitted or a value of `0` is entered, then Windows PowerShell calculates an
    optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the
    computer. The throttle limit applies only to the current cmdlet, not to the session or to the
    computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: UseOpportunisticLocking
  description: |+
    Resets the use opportunistic locks value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet isn't run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WindowSizeThreshold
  description: |+
    Resets the window size threshold value to its default value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: SmbShare.Reset-SmbClientConfiguration
name: Reset-SmbClientConfiguration
description: |-
  The `Reset-SmbClientConfiguration` cmdlet resets SMB client configuration parameters to their
  default values.

  > [!NOTE]
  > - This cmdlet is available beginning with 2022-06 Cumulative Update for Microsoft server operating
  > system version 21H2 for x64-based Systems
  > ([KB5014665](https://support.microsoft.com/help/5014665)), and Cumulative Update for Windows 11,
  > version 22H2 ([KB5014668](https://support.microsoft.com/help/5014668)).
  >
  > - The **CompressibilitySampling** and **RequestCompression** parameters are available beginning
  >   with 2022-08 Cumulative Update for Microsoft server operating system version 21H2 for x64-based
  >   Systems ([KB5016693](https://support.microsoft.com/help/5016693)), and Cumulative Update for
  >   Windows 11, version 22H2 ([KB5016691](https://support.microsoft.com/help/5016691)).
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: SmbClientConfiguration.cdxml-help.xml
  Module Name: SmbShare
  ms.date: 10/20/2022
  online version: http://go.microsoft.com/fwlink/?LinkID=241959
  schema: 2.0.0
  title: Reset-SmbClientConfiguration
