### YamlMime:PowerShellCmdlet1
uid: DeviceHealthAttestation.Backup-DHASConfiguration
name: Backup-DHASConfiguration
module: DeviceHealthAttestation
isPreview: false
summary: |-
  Backs up the configuration.
description: |-
  The **Backup-DHASConfiguration** cmdlet backs up the Device Health Attestation service configuration from the web.config file.

  You must have administrator rights to run this cmdlet.
parameters:
  cmdletParameters:
  - name: Force
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Forces the command to run without asking for user confirmation.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Path
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the location in which to save the backup configuration file.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Backup-DHASConfiguration
        [-Path] <String>
        [-Force]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
outputs:
- name: <xref href="String" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet returns a string with the backup file path.
examples:
- title: 'Example 1: Back up the service configuration'
  description: |-
    ```
    PS C:\> Backup-DHASConfiguration -Path "c:\backup.xml"
    ```

    This commands backs up the service configuration from the web.config file to the file specified by the *Path* parameter.
links:
- text: Restore-DHASConfiguration
  href: ./Restore-DHASConfiguration.yml
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  document type: cmdlet
  external help file: Microsoft.Windows.DeviceHealthAttestation.PowerShell.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/devicehealthattestation/backup-dhasconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  Module Name: DeviceHealthAttestation
  ms.date: 12/20/2016
  PlatyPS schema version: 2024-05-01
  title: Backup-DHASConfiguration
