### YamlMime:PowershellCmdlet
summary: |-
  Retrieves global Web Application Proxy settings.
module: WebApplicationProxy
notes: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#AppProxyGlobalConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    Displays the Web Application Proxy configuration.
links:
- text: Web Application Proxy overview
  href: https://technet.microsoft.com/library/dn280944.aspx
- text: Publishing Internal Applications using Web Application
  href: https://technet.microsoft.com/library/dn383650.aspx
- text: Set-WebApplicationProxyConfiguration
  href: ./Set-WebApplicationProxyConfiguration.yml
syntaxes:
- >-
  Get-WebApplicationProxyConfiguration [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob]

   [<CommonParameters>]
examples:
- title: 'Example 1: Retrieve the Web Application Proxy settings'
  code: |-
    PS C:\>Get-WebApplicationProxyConfiguration

    ADFSSignOutUrl                         : https://sts.contoso.com/adfs/ls/?wa=wsignout1.0
    ADFSTokenAcceptanceDurationSec         : 120
    ADFSTokenSigningCertificatePublicKey   : Automatically Updated
    ADFSUrl                                : https://sts.contoso.com/adfs/ls
    ADFSWebApplicationProxyRelyingPartyUri : urn:AppProxy:com
    ConfigurationChangesPollingIntervalSec : 30
    ConfigurationVersion                   : Windows Server 2016
    ConnectedServersName                   : {WAP-server1.corp.contoso.com, WAP-server2.corp.contoso.com}
    OAuthAuthenticationURL                 : https://sts.contoso.com/adfs/oauth2/authorize
    UserIdleTimeoutAction                  : Signout
    UserIdleTimeoutSec                     : 0
  description: |-
    This command retrieves the Web Application Proxy settings.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: WebApplicationProxy.Get-WebApplicationProxyConfiguration
name: Get-WebApplicationProxyConfiguration
description: |-
  The **Get-WebApplicationProxyConfiguration** cmdlet retrieves the Web Application Proxy settings that are not specific to any published application.
  To modify the settings, use the Set-WebApplicationProxyConfiguration cmdlet.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: WebApplicationProxy-help.xml
  Module Name: WebApplicationProxy
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/webapplicationproxy/get-webapplicationproxyconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-WebApplicationProxyConfiguration
