### YamlMime:PowershellCmdlet
summary: |-
  Gets binding information for the SSL certificate for federation server proxy.
module: WebApplicationProxy
notes: ""
links:
- text: Set-WebApplicationProxySslCertificate
  href: ./Set-WebApplicationProxySslCertificate.yml
syntaxes:
- Get-WebApplicationProxySslCertificate [<CommonParameters>]
examples:
- title: 'Example 1: Get binding information for a certificate'
  code: |-
    PS C:\> Get-WebApplicationProxySslCertificate
  description: |-
    This command gets the binding information for the AD FS SSL certificate that is installed and configured for the federation server proxy component of the Web Application Proxy.
  summary: ""
uid: WebApplicationProxy.Get-WebApplicationProxySslCertificate
name: Get-WebApplicationProxySslCertificate
description: |-
  The **Get-WebApplicationProxySslCertificate** cmdlet gets binding information for the Active Directory Federation Services (AD FS) Secure Sockets Layer (SSL) certificate for the federation server proxy component of the Web Application Proxy.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IdentityServer.Management.Proxy.dll-Help.xml
  Module Name: WebApplicationProxy
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/webapplicationproxy/get-webapplicationproxysslcertificate?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-WebApplicationProxySslCertificate
