### YamlMime:PowershellCmdlet
summary: |-
  Gets the configuration database synchronization properties of the Federation Service.
module: ADFS
notes: |-
  * This cmdlet keeps track of when Active Directory Federation Services (AD FS) 2.0 on a server computer last synchronized its database with other federation servers in your deployment. For example, the PollDuration property specifies the length of the poll interval in seconds.
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.IdentityServer.PowerShell.Resources.SyncPropertiesBase" data-throw-if-not-resolved="False" />
  description: |-
    A class structure that represents the synchronization properties for the Federation Service.
links:
- text: Set-ADFSSyncConfiguration
  href: ./Set-ADFSSyncConfiguration.yml
syntaxes:
- Get-ADFSSyncConfiguration [<CommonParameters>]
examples:
- title: '1:'
  code: |-
    PS C:\>Get-ADFSSyncConfiguration
  description: |-
    Gets the current synchronization properties and activity for the Federation Service.
  summary: ""
uid: ADFS.Get-ADFSSyncConfiguration
name: Get-ADFSSyncConfiguration
description: |-
  The Get-ADFSSyncConfiguration cmdlet retrieves the configuration database synchronization properties of the Federation Service.
metadata:
  external help file: Microsoft.IdentityServer.PowerShell.dll-Help.xml
  Module Name: ADFS
  online version: https://docs.microsoft.com/powershell/module/adfs/get-adfssyncconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
