### YamlMime:PowershellCmdlet
summary: |-
  Sets the configuration properties of the federation server proxy.
module: ADFS
notes: |-
  * This cmdlet may be used only on a computer that is configured in Active Directory Federation Services (AD FS) as a federation server proxy. It will not work on a federation server.
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-ADFSProxyConfiguration
  href: ./Get-ADFSProxyConfiguration.yml
syntaxes:
- >-
  Set-ADFSProxyConfiguration [-HostName <String>] [-HttpPort <Int32>] [-HttpsPort <Int32>] [-LogLevel <String[]>]

   [-ForwardProxyUrl <Uri>] [-ProxyTrustRenewPeriod <Int32>] [-PassThru] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: '-------------------------- EXAMPLE 1 --------------------------'
  code: |-
    PS C:\>Set-ADFSProxyProperties -Hostname "fs.fabrikam.com"
  description: |-
    Sets the properties for the federation server proxy with the name "fs.fabrikam.com".
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Uri" data-throw-if-not-resolved="False" />
  name: ForwardProxyUrl
  description: |+
    Specifies the URL of a forward proxy to use for communication to the federation service, if any.
    By default, there is no forward proxy configured.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: HostName
  description: |+
    Specifies the network addressable host name of the Federation Service.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: HttpPort
  description: |+
    Specifies the HTTP port for the server.
    The default value is 80.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: HttpsPort
  description: |+
    Specifies the HTTPS port for the server.
    The default value is 443.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: LogLevel
  description: |+
    Specifies the level of logging detail.
    The list defines which types of events are logged.

    Possible values are Errors, Warnings, Information, SuccessAudits, and FailureAudits.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Errors, FailureAudits, Information, Verbose, None, SuccessAudits, Warnings
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Passes an object to the pipeline.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ProxyTrustRenewPeriod
  description: |+
    Sets the interval (in minutes) that the federation server proxy uses to check with its associated federation server for updated trust tokens.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: ADFS.Set-ADFSProxyConfiguration
name: Set-ADFSProxyConfiguration
description: |-
  The Set-ADFSProxyConfiguration cmdlet changes the properties of a federation server proxy that has been previously configured.
metadata:
  external help file: Microsoft.IdentityServer.PowerShell.dll-Help.xml
  Module Name: ADFS
  online version: https://docs.microsoft.com/powershell/module/adfs/set-adfsproxyconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
