### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the remote access configuration.
module: RemoteAccess
notes: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#RemoteAccessConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Set-RemoteAccessConfiguration
  href: ./Set-RemoteAccessConfiguration.yml
syntaxes:
- >-
  Get-RemoteAccessConfiguration [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob]

   [<CommonParameters>]
examples:
- title: 'Example 1: Retrieve remote access configuration'
  code: |-
    PS C:\>Get-RemoteAccessConfiguration
  description: |-
    This command retrieves remote access configuration for a computer.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    ps_cimcommon_asjob

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a New-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227967 or Get-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227966 cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: RemoteAccess.Get-RemoteAccessConfiguration
name: Get-RemoteAccessConfiguration
description: |-
  The **Get-RemoteAccessConfiguration** cmdlet retrieves the configuration of a remote access role and returns the corresponding Windows PowerShell object.
metadata:
  external help file: PS_RemoteAccessConfiguration_v1.0.cdxml-help.xml
  Module Name: RemoteAccess
  ms.date: 12/05/2017
  online version: https://docs.microsoft.com/powershell/module/remoteaccess/get-remoteaccessconfiguration?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-RemoteAccessConfiguration
