### YamlMime:PowerShellCmdlet1
uid: Appx.Get-AppxPackageAutoUpdateSettings
name: Get-AppxPackageAutoUpdateSettings
module: Appx
isPreview: false
summary: |-
  Provides visibility to the settings configured for a particular Windows App.
description: |-
  The `Get-AppxPackageAutoUpdateSettings` PowerShell cmdlet returns the settings configured for a
  specific or all installed Windows Apps in relation to Auto Update and Repair.
parameters:
  cmdletParameters:
  - name: AllUsers
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Specifies to display Windows App Auto Update and Repair settings for all that are installed for all
      users.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: true
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PackageFullName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the Package Full Name of the app that's being queried.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: false
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: true
  - name: ShowUpdateAvailability
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Specifies to display available update information for a specific Windows App.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: true
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AppxPackageAutoUpdateSettings
        [[-PackageFullName] <String>]
        [-ShowUpdateAvailability]
        [-AllUsers]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
- name: <xref href="System.Management.Automation.SwitchParameter" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Get all App Package Auto Update settings'
  description: |-
    ```powershell
    Get-AppxPackageAutoUpdateSettings
    ```

    This will return the Auto Update and Repair settings for all configured and installed Windows Apps
    on the device, and registered to the user.
- title: 'Example 2: Get App Package Auto Update settings for all users'
  description: |-
    ```powershell
    Get-AppxPackageAutoUpdateSettings -AllUsers
    ```

    This will return the Auto Update and Repair settings for all configured and installed Windows Apps
    that have been registered for all users.
- title: 'Example 3: Get a single App Package Auto Update setting'
  description: |-
    ```powershell
    Get-AppxPackageAutoUpdateSettings -PackageFullName publisher.package1_1.0.0.0_neutral__8wekyb3d8bbwe
    ```

    This will return the Auto Update and Repair settings for a specific Windows App that has been
    installed and registered to the signed-in user.
- title: 'Example 4: Get App Package Auto Update settings for all installed Windows Apps'
  description: |-
    ```powershell
    Get-AppxPackageAutoUpdateSettings -ShowUpdateAvailability
    ```

    Displays available update information for all installed Windows Apps.
links:
- text: Package Manager API
  href: http://go.microsoft.com/fwlink/?LinkId=245447
- text: How to Add and Remove Apps
  href: http://go.microsoft.com/fwlink/?LinkID=231020
- text: Get-AppxPackage
  href: ./Get-AppxPackage.yml
- text: Get-AppxPackageManifest
  href: ./Get-AppxPackageManifest.yml
- text: Move-AppxPackage
  href: ./Move-AppxPackage.yml
- text: Remove-AppxPackage
  href: ./Remove-AppxPackage.yml
metadata:
  description: Provides guidance on how to view the auto-update and repair settings of a Windows App.
  document type: cmdlet
  external help file: Microsoft.Windows.Appx.PackageManager.Commands.dll-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/appx/Get-AppxPackageAutoUpdateSettings?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  Module Name: Appx
  ms.date: 05/15/2023
  PlatyPS schema version: 2024-05-01
