### YamlMime:PowerShellCmdlet1
uid: NetworkSwitchManager.Restore-NetworkSwitchConfiguration
name: Restore-NetworkSwitchConfiguration
module: NetworkSwitchManager
isPreview: false
summary: |-
  Restores configuration for a network switch.
description: |-
  The **Restore-NetworkSwitchConfiguration** cmdlet restores configuration for a network switch to the last saved startup configuration.
parameters:
  cmdletParameters:
  - name: CimSession
    type: <xref href="CimSession" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the **CimSession** that this cmdlet uses to connect to the network switch.
      For more information about **CimSession** objects, type `Get-Help New-CimSession`.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Confirm
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs. The cmdlet is not run.
    aliases:
    - wi
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Restore-NetworkSwitchConfiguration
        [-CimSession] <CimSession>
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Restore the configuration for a network switch'
  description: |-
    ```
    PS C:\>$Session = New-CimSession -ComputerName "NetworkSwitch08"
    PS C:\> Restore-NetworkSwitchConfiguration -CimSession $Session
    ```

    The first command creates a **CimSession** for a network switch, and then stores it in the **$Session** variable.
    For more information about **CimSession** objects, type `Get-Help New-CimSession`.

    The second command restores the configuration from the last saved configuration for NetworkSwitch08 by using the **$Session** object.
links:
- text: Save-NetworkSwitchConfiguration
  href: ./Save-NetworkSwitchConfiguration.yml
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  document type: cmdlet
  external help file: NetworkSwitchConfiguration.psm1-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/networkswitchmanager/restore-networkswitchconfiguration?view=windowsserver2025-ps&wt.mc_id=ps-gethelp
  Module Name: NetworkSwitchManager
  ms.date: 12/20/2016
  PlatyPS schema version: 2024-05-01
  title: Restore-NetworkSwitchConfiguration
