### YamlMime:PowershellCmdlet
summary: |-
  Gets native client application roles from an application in AD FS.
module: ADFS
notes: ""
inputs:
- name: <xref href="Microsoft.IdentityServer.Management.Resources.NativeClientApplication" data-throw-if-not-resolved="False" />
  description: |-
    NativeClientApplication objects are received by the *Application* parameter.
- name: <xref href="Microsoft.IdentityServer.Management.Resources.ApplicationGroup" data-throw-if-not-resolved="False" />
  description: |-
    ApplicationGroup objects are received by the *ApplicationGroup* parameter.
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    String objects are received by the *Identifier* and *Name* parameters.
outputs:
- name: <xref href="Microsoft.IdentityServer.Management.Resources.NativeClientApplication" data-throw-if-not-resolved="False" />
  description: |-
    Returns one or more NativeClientApplication objects that represent the native client application resources for the Federation Service.
links:
- text: Add-AdfsNativeClientApplication
  href: ./Add-AdfsNativeClientApplication.yml
- text: Remove-AdfsNativeClientApplication
  href: ./Remove-AdfsNativeClientApplication.yml
- text: Set-AdfsNativeClientApplication
  href: ./Set-AdfsNativeClientApplication.yml
syntaxes:
- Get-AdfsNativeClientApplication [[-Identifier] <String[]>] [<CommonParameters>]
- Get-AdfsNativeClientApplication [-Name] <String[]> [<CommonParameters>]
- Get-AdfsNativeClientApplication [-Application] <NativeClientApplication> [<CommonParameters>]
- Get-AdfsNativeClientApplication [-ApplicationGroupIdentifier] <String> [<CommonParameters>]
- Get-AdfsNativeClientApplication [-ApplicationGroup] <ApplicationGroup> [<CommonParameters>]
parameters:
- type: <xref href="NativeClientApplication" data-throw-if-not-resolved="False" />
  name: Application
  isRequired: true
  description: |+
    Specifies the native client application to get.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ApplicationGroup" data-throw-if-not-resolved="False" />
  name: ApplicationGroup
  isRequired: true
  description: |+
    Specifies the application group from which to get native client applications.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ApplicationGroupIdentifier
  isRequired: true
  description: |+
    Specifies the ID of the application group from which to get native client applications.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Identifier
  description: |+
    Specifies an array of IDs of native client applications get.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Name
  isRequired: true
  description: |+
    Specifies an array of names of native client applications get.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: ADFS.Get-AdfsNativeClientApplication
name: Get-AdfsNativeClientApplication
description: |-
  The **Get-AdfsNativeClientApplication** cmdlet gets native client application roles from an application in Active Directory Federation Services (AD FS).
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IdentityServer.Management.dll-Help.xml
  Module Name: ADFS
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/adfs/get-adfsnativeclientapplication?view=windowsserver2019-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-AdfsNativeClientApplication
