### YamlMime:PowershellCmdlet
summary: |-
  Removes a native client application role from an application in AD FS.
module: ADFS
notes: ""
inputs:
- name: <xref href="Microsoft.IdentityServer.Management.Resources.NativeClientApplication" data-throw-if-not-resolved="False" />
  description: |-
    NativeClientApplication objects are received by the *TargetApplication* parameter.
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    String objects are received by the *TargetIdentifier* and *TargetName* parameters.
outputs:
- name: <xref href="Microsoft.IdentityServer.Management.Resources.NativeClientApplication" data-throw-if-not-resolved="False" />
  description: |-
    Returns the removed NativeClientApplication object when the *PassThru* parameter is specified. By default, this cmdlet does not generate any output.
links:
- text: Add-AdfsNativeClientApplication
  href: ./Add-AdfsNativeClientApplication.yml
- text: Get-AdfsNativeClientApplication
  href: ./Get-AdfsNativeClientApplication.yml
- text: Set-AdfsNativeClientApplication
  href: ./Set-AdfsNativeClientApplication.yml
syntaxes:
- >-
  Remove-AdfsNativeClientApplication [-TargetIdentifier] <String> [-PassThru] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- Remove-AdfsNativeClientApplication [-TargetName] <String> [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Remove-AdfsNativeClientApplication [-TargetApplication] <NativeClientApplication> [-PassThru] [-WhatIf]

   [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="NativeClientApplication" data-throw-if-not-resolved="False" />
  name: TargetApplication
  isRequired: true
  description: |+
    Specifies the native client application to remove.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetIdentifier
  isRequired: true
  description: |+
    Specifies the ID of the native client application to remove.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetName
  isRequired: true
  description: |+
    Specifies the name of the native client application to remove.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: ADFS.Remove-AdfsNativeClientApplication
name: Remove-AdfsNativeClientApplication
description: |-
  The **Remove-AdfsNativeClientApplication** cmdlet removes a native client application role from an application in Active Directory Federation Services (AD FS).
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IdentityServer.Management.dll-Help.xml
  Module Name: ADFS
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/adfs/remove-adfsnativeclientapplication?view=windowsserver2019-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Remove-AdfsNativeClientApplication
