### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the Server Message Block (SMB) client configuration.
module: SmbShare
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root/Microsoft/Windows/SMB/MSFT_SmbClientConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The MSFT_SmbClientConfiguration object represents the configuration of the SMB client.
links:
- text: Set-SmbClientConfiguration
  href: ./Set-SmbClientConfiguration.yml
syntaxes:
- >-
  Get-SmbClientConfiguration [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: EXAMPLE 1
  code: |-
    PS C:\>Get-SmbClientConfiguration
    ConnectionCountPerRssNetworkInterface : 4
    DirectoryCacheEntriesMax              : 16
    DirectoryCacheEntrySizeMax            : 65536
    DirectoryCacheLifetime                : 10
    EnableBandwidthThrottling             : True
    EnableByteRangeLockingOnReadOnlyFiles : True
    EnableLargeMtu                        : True
    EnableMultiChannel                    : True
    DormantFileLimit                      : 1023
    EnableSecuritySignature               : True
    ExtendedSessionTimeout                : 1000
    FileInfoCacheEntriesMax               : 64
    FileInfoCacheLifetime                 : 10
    FileNotFoundCacheEntriesMax           : 128
    FileNotFoundCacheLifetime             : 5
    KeepConn                              : 600
    MaxCmds                               : 50
    MaximumConnectionCountPerServer       : 32
    OplocksDisabled                       : False
    RequireSecuritySignature              : False
    SessionTimeout                        : 60
    UseOpportunisticLocking               : True
    WindowSizeThreshold                   : 1
  description: |-
    This example retrieves the SMB client configuration.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    ps_cimcommon_asjob

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a New-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227967 or Get-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227966 cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: SmbShare.Get-SmbClientConfiguration
name: Get-SmbClientConfiguration
description: |-
  The **Get-SmbClientConfiguration** cmdlet retrieves the Server Message Block (SMB) client configuration.
metadata:
  external help file: SmbClientConfiguration.cdxml-help.xml
  Module Name: SmbShare
  ms.date: 10/29/2017
  online version: https://docs.microsoft.com/powershell/module/smbshare/get-smbclientconfiguration?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-SmbClientConfiguration
