### YamlMime:PowershellCmdlet
summary: |-
  Modifies the configuration for the computer that runs the IPAM server.
module: IpamServer
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Windows.Ipam.Commands.IpamConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet returns an object that contains an IPAM configuration.
links:
- text: Get-IpamConfiguration
  href: ./Get-IpamConfiguration.yml
syntaxes:
- >-
  Set-IpamConfiguration [-Port] <UInt16> [-Force] [-PassThru] [-CimSession <CimSession[]>]

   [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-IpamConfiguration [-Force] [-PassThru] [-UpdateTables] [-CimSession <CimSession[]>]

   [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-IpamConfiguration [-Force] [-PassThru] -HmacKey <SecureString> [-UpdateTables] [-CimSession <CimSession[]>]

   [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-IpamConfiguration [-Force] [-PassThru] [-RefreshHmacKey] [-CimSession <CimSession[]>]

   [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-IpamConfiguration [-Force] [-PassThru] [-ProvisioningMethod] <ProvisioningMethod> [[-GpoPrefix] <String>]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Modify an IPAM configuration'
  code: |-
    PS C:\> Set-IpamServerConfiguration -Port 45000  -PassThru -Force
    Version : 1.3 

     Port : 45000
  description: |-
    This command changes the IPAM server management port to 45000 and suppresses the default confirmation text.
    The command also returns the modified IPAM server configuration object.

    The command includes the *PassThru* parameter, so it displays results to the console.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete. 

    The cmdlet immediately returns an object that represents the job and then displays the command prompt. 
    You can continue to work in the session while the job completes. 
    To manage the job, use the `*-Job` cmdlets. 
    To get the job results, use the [Receive-Job](https://go.microsoft.com/fwlink/?LinkID=113372) cmdlet. 

    For more information about Windows PowerShell background jobs, see [about_Jobs](https://go.microsoft.com/fwlink/?LinkID=113251).

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the command to run without asking for user confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GpoPrefix
  description: |+
    Specifies the unique Group Policy Object (GPO) prefix name that IPAM uses to create the group policy objects.
    Use this parameter only when the value of the *ProvisioningMethod* parameter is set to Automatic.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SecureString" data-throw-if-not-resolved="False" />
  name: HmacKey
  isRequired: true
  description: |+
    Specifies a keyed-hash message authentication code (HMAC).

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt16" data-throw-if-not-resolved="False" />
  name: Port
  isRequired: true
  description: |+
    Specifies the TCP port number for communication between computers that run the IPAM RSAT client and the IPAM server.
    IPAM lets you configure any port number in the range 1-65535  for communication between computers that run the IPAM client and server.
    To avoid port conflicts with well-known ports, choose a port from the unassigned port range, 48620-49150.
    By default, IPAM uses port number 48885.
    The cmdlet configures appropriate custom IPAM server firewall rules for the specified new port, enables appropriate custom IPAM server firewall rules for the specified new port, and restarts the IPAM application pool to listen on the specified new port.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ProvisioningMethod" data-throw-if-not-resolved="False" />
  name: ProvisioningMethod
  isRequired: true
  description: |+
    Specifies a provisioning method.

    The acceptable values for this parameter are: Automatic and Manual.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: Automatic, Manual
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: RefreshHmacKey
  isRequired: true
  description: |+
    Indicates that the cmdlet refreshes the HMAC key, if the key has expired.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: UpdateTables
  isRequired: true
  description: |+
    Indicates that the cmdlet updates the database tables.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: IpamServer.Set-IpamConfiguration
name: Set-IpamConfiguration
description: |-
  The **Set-IpamConfiguration** cmdlet modifies the IP Address Management (IPAM) server configuration, including the TCP port over which the computer that runs the IPAM Remote Server Administration Tools (RSAT) client connects and communicates with the computer that runs the IPAM server.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: IpamConfiguration.cdxml-help.xml
  Module Name: IpamServer
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/ipamserver/set-ipamconfiguration?view=windowsserver2019-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-IpamConfiguration
