### YamlMime:PowershellCmdlet
summary: |-
  Resets the IP-HTTPS configuration elements in a GPO.
module: NetworkTransition
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet accepts no input objects.
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root\StandardCimv2\MSFT_NetIPHttpsConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The `Microsoft.Management.Infrastructure.CimInstance` object is a wrapper class that displays Windows Management Instrumentation (WMI) objects.
    The path after the pound sign (`#`) provides the namespace and class name for the underlying WMI object.

    When the *Passthru* parameter is specified, this cmdlet outputs a modified Windows Management Instrumentation (WMI) object.
links:
- text: Get-NetIPHttpsConfiguration
  href: ./Get-NetIPHttpsConfiguration.yml
- text: New-NetIPHttpsConfiguration
  href: ./New-NetIPHttpsConfiguration.yml
- text: Remove-NetIPHttpsConfiguration
  href: ./Remove-NetIPHttpsConfiguration.yml
- text: Rename-NetIPHttpsConfiguration
  href: ./Rename-NetIPHttpsConfiguration.yml
- text: Set-NetIPHttpsConfiguration
  href: ./Set-NetIPHttpsConfiguration.yml
syntaxes:
- >-
  Reset-NetIPHttpsConfiguration [-Profile <String[]>] [-ProfileActivated <Boolean[]>] [-PolicyStore <String>]

   [-State] [-AuthMode] [-StrongCRLRequired] [-PassThru] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>]

   [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Reset-NetIPHttpsConfiguration [-Profile <String[]>] [-ProfileActivated <Boolean[]>] [-GPOSession <String>]

   [-State] [-AuthMode] [-StrongCRLRequired] [-PassThru] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>]

   [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Reset-NetIPHttpsConfiguration -InputObject <CimInstance[]> [-State] [-AuthMode] [-StrongCRLRequired]

   [-PassThru] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Reset the IP-HTTPS configuration'
  code: |-
    PS C:\>$config = Get-NetIPHttpsConfiguration
    PS C:\> Reset-NetIPHttpsConfiguration -InputObject $config
  description: |-
    This set of commands gets the IP-HTTPS configuration using the Get-NetIPHttpsConfiguration cmdlet, stores it in a variable named $config and then passes the contents of the variable to this cmdlet.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AuthMode
  description: |+
    Resets the authentication mode to not configured.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GPOSession
  description: |+
    Specifies the Group Policy session that contains the IP-HTTPS configuration information to reset.

    You can use this parameter with the **NetGPO** cmdlets to aggregate multiple operations performed on a GPO.

    You cannot use this parameter with the *PolicyStore* parameter.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the input object that is used in a pipeline command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PolicyStore
  description: |+
    Specifies the policy store that contains the IP-HTTPS configuration to reset.
    For this cmdlet, this parameter only supports GPO stores.

    To reset an IP-HTTPS configuration stored in a GPO, specify the GPO name using the following format: `Domain\GPOName`

    You cannot use this parameter with the **GPOSession** parameter.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Profile
  description: |+
    Specifies the name of the IP-HTTPS configuration profile to reset.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: IPHttpsProfile
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ProfileActivated
  description: |+
    Filters the objects to reset.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: State
  description: |+
    Resets the state of the IP-HTTPS configuration to not configured.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: StrongCRLRequired
  description: |+
    Resets the strong certificate revocation list (CRL) check configuration to not configured.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: NetworkTransition.Reset-NetIPHttpsConfiguration
name: Reset-NetIPHttpsConfiguration
description: |-
  The **Reset-NetIPHttpsConfiguration** cmdlet resets the IP-HTTP configuration elements in a Group Policy Object (GPO) to the not configured state.

  Group Policy settings have one of the following three states: not configured, enabled, or disabled.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: MSFT_NetIpHTTPsConfiguration.cdxml-help.xml
  Module Name: NetworkTransition
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/networktransition/reset-netiphttpsconfiguration?view=windowsserver2019-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Reset-NetIPHttpsConfiguration
