### YamlMime:PowershellCmdlet
summary: |-
  Modifies the Teredo configuration of a computer or a Group Policy object (GPO).
module: NetworkTransition
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet accepts no input objects.
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root\StandardCimv2\MSFT_NetTeredoConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The `Microsoft.Management.Infrastructure.CimInstance` object is a wrapper class that displays Windows Management Instrumentation (WMI) objects.
    The path after the pound sign (`#`) provides the namespace and class name for the underlying WMI object.

    When the *Passthru* parameter is specified, this cmdlet outputs a modified Teredo configuration object.
links:
- text: Get-NetTeredoConfiguration
  href: ./Get-NetTeredoConfiguration.yml
- text: Reset-NetTeredoConfiguration
  href: ./Reset-NetTeredoConfiguration.yml
syntaxes:
- >-
  Set-NetTeredoConfiguration [-IPInterface <CimInstance>] [-PolicyStore <String>] [-GPOSession <String>]

   [[-Type] <Type>] [[-ServerName] <String>] [[-RefreshIntervalSeconds] <UInt32>] [[-ClientPort] <UInt32>]

   [[-ServerVirtualIP] <String>] [[-DefaultQualified] <Boolean>] [[-ServerShunt] <Boolean>]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-PassThru] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Set-NetTeredoConfiguration -InputObject <CimInstance[]> [[-Type] <Type>] [[-ServerName] <String>]

   [[-RefreshIntervalSeconds] <UInt32>] [[-ClientPort] <UInt32>] [[-ServerVirtualIP] <String>]

   [[-DefaultQualified] <Boolean>] [[-ServerShunt] <Boolean>] [-CimSession <CimSession[]>]

   [-ThrottleLimit <Int32>] [-AsJob] [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Set the Teredo server name'
  code: |-
    PS C:\>Set-NetTeredoConfiguration -ServerName "Test"
  description: |-
    This command sets the Teredo server name to Test on the local persistent store.
  summary: ""
- title: 'Example 2: Set the Teredo state'
  code: |-
    PS C:\>Set-NetTeredoConfiguration -Type Enterpriseclient -PolicyStore "Domain\GPOname"
  description: |-
    This command sets the Teredo state to enterpriseclient in a GPO named Domain\GPOname.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: ClientPort
  description: |+
    Specifies the UDP port of the client computer.
    If this parameter is not specified, then the port is chosen by the operating system.

  defaultValue: None
  position: "4"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: DefaultQualified
  description: |+
    Determines if this cmdlet qualifies Teredo by default.
    The default value is False.
    This parameter can only be specified on GPOs.

  defaultValue: None
  position: "6"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GPOSession
  description: |+
    Specifies the Group Policy session to which to store the configuration information.

    You can use this parameter with the **NetGPO** cmdlets to aggregate multiple operations performed on a GPO.

    You cannot use this parameter with the *PolicyStore* parameter.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the input object that is used in a pipeline command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" />
  name: IPInterface
  description: |+
    Specifies the interface on which to set the Teredo configuration.
    If the specified interface is not a Teredo interface, then the cmdlet does not return any configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PolicyStore
  description: |+
    Specifies the policy store that contains the configuration to set.
    The acceptable values for this parameter are:

    - PersistentStore 
    - GPO

    The default value is PersistentStore.

    To set the configuration of a GPO, specify the GPO name using the following format: Domain\GPOName

    You cannot use this parameter with the *GPOSession* parameter.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: RefreshIntervalSeconds
  description: |+
    Specifies the client refresh interval in seconds.

  defaultValue: None
  position: "3"
  aliases: RefreshInterval
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ServerName
  description: |+
    Specifies the name or IPv4 address of the Teredo server.

  defaultValue: None
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: ServerShunt
  description: |+
    Indicates that the tunnel miniport and IPv4 routing layer are bypassed for high throughput on the Teredo relay functionality of the Teredo server.

  defaultValue: None
  position: "7"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ServerVirtualIP
  description: |+
    Specifies the virtual IPv4 address of the server.
    This parameter is not applicable if the computer is a Teredo client.
    This parameter can only be specified on GPOs.

  defaultValue: None
  position: "5"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Type" data-throw-if-not-resolved="False" />
  name: Type
  description: |+
    Specifies the state of Teredo.
    The acceptable values for this parameter are:

    - Disabled: Disables the Teredo service. 
    - Client.
    Enables the Teredo client. 
    - Enterpriseclient.
    Skips the managed network detection. 
    - Server.
    Enables the Teredo server. 
    - Relay. 
    - Automatic.
    - Default.
    The default state is client.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: Default, Relay, Client, Server, Disabled, Automatic, Enterpriseclient, Natawareclient
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: NetworkTransition.Set-NetTeredoConfiguration
name: Set-NetTeredoConfiguration
description: |-
  The **Set-NetTeredoConfiguration** cmdlet modifies the Teredo configuration of either a computer or a Group Policy Object (GPO).
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: MSFT_NetTeredoConfiguration.cdxml-help.xml
  Module Name: NetworkTransition
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/networktransition/set-netteredoconfiguration?view=windowsserver2019-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-NetTeredoConfiguration
