### YamlMime:PowershellCmdlet
summary: |-
  Gets the IP address of a virtual network adapter configured to be used when a virtual machine fails over.
module: Hyper-V
notes: ""
outputs:
- name: <xref href="VMNetworkAdapterFailoverConfiguration" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-VMNetworkAdapterFailoverConfiguration [-VMNetworkAdapterName <String>] [-ComputerName <String[]>]

   [-VMName] <String[]> [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Get-VMNetworkAdapterFailoverConfiguration [-VMNetworkAdapterName <String>] [-VM] <VirtualMachine[]> [-WhatIf]

   [-Confirm] [<CommonParameters>]
- >-
  Get-VMNetworkAdapterFailoverConfiguration [-VMNetworkAdapter] <VMNetworkAdapterBase[]> [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: Example 1
  code: |-
    PS C:\>Get-VMNetworkAdapterFailoverConfiguration VM01
  description: |-
    This example gets the failover IP address configuration of all virtual network adapters attached to a virtual machine named VM01.
  summary: ""
- title: Example 2
  code: |-
    PS C:\>Get-VMNetworkAdapterFailoverConfiguration VM01 -VMNetworkAdapterName NetworkAdapter
  description: |-
    This example gets the failover IP address configuration of a virtual network adapter named NetworkAdapter on a virtual machine named VM01.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ComputerName
  description: |+
    Specifies one or more Hyper-V hosts on which the IP address configuration of a virtual network adapter is to be retrieved.
    NetBIOS names, IP addresses, and fully-qualified domain names are allowable.
    The default is the local computer - use "localhost" or a dot (".") to specify the local computer explicitly.

  defaultValue: .
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="VirtualMachine" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: VM
  isRequired: true
  description: |+
    Specifies the virtual machine for which you want to get the IP address configuration of a virtual network adapter.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: VMName
  isRequired: true
  description: |+
    Specifies the name of the virtual machine for which you want to get the IP address configuration of a virtual network adapter.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="VMNetworkAdapterBase" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: VMNetworkAdapter
  isRequired: true
  description: |+
    Specifies the virtual network adapter whose IP address configuration you want to get.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: VMNetworkAdapterName
  description: |+
    Specifies the name of the virtual network adapter whose IP address configuration you want to get.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: Hyper-V.Get-VMNetworkAdapterFailoverConfiguration
name: Get-VMNetworkAdapterFailoverConfiguration
description: |-
  The **Get-VMNetworkAdapterFailoverConfiguration** cmdlet gets the IP address configuration of a virtual network adapter configured to be used when a virtual machine fails over.
metadata:
  external help file: Microsoft.HyperV.PowerShell.dll-Help.xml
  Module Name: Hyper-V
  ms.date: 10/30/2017
  online version: https://docs.microsoft.com/powershell/module/hyper-v/get-vmnetworkadapterfailoverconfiguration?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-VMNetworkAdapterFailoverConfiguration
