### YamlMime:PowershellCmdlet
summary: |-
  Adds a property to an IIS configuration section.
module: WebAdministration
notes: ""
links:
- text: Remove-WebConfigurationProperty
  href: ./Remove-WebConfigurationProperty.yml
syntaxes:
- >-
  Add-WebConfigurationProperty -Name <String> [-Type <String>] [-Value <PSObject>] [-Clr <String>]

   [-AtElement <Hashtable>] [-AtIndex <Int32>] [-AtName <String>] [-Force] [-Location <String[]>]

   [-Filter] <String[]> [[-PSPath] <String[]>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: '-------------- EXAMPLE 1: Adding a Default Document --------------'
  code: |-
    IIS:\>Add-WebConfigurationProperty //defaultDocument/files "IIS:\sites\Default Web Site" -AtIndex 0 -Name collection -Value "new-index.html"
  description: |-
    This command adds a new Default Document named new-index.html to the top of the list of existing documents.
  summary: ""
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AtElement
  description: |+
    The element at which the value is to be inserted.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: AtIndex
  description: |+
    The index at which the property is to be inserted.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AtName
  description: |+
    The property name at which the property is to be inserted.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Clr
  description: |+
    Version of the .NET framework in the form vn.n, such as v4.0 or v2.0.
    The default is v4.0.
    This parameter is used only when PSPath is set to either Machine or Machine/Webroot.
    If PSPath is not set to one of these values and the Clr parameter is set, PowerShell ignores the value of Clr and returns a warning.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Filter
  isRequired: true
  description: |+
    Specifies the IIS configuration section, or an XPath query that returns a configuration element.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the property to be written.
    If a lock exists, the property is written at a level in the configuration above the lock.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Location
  description: |+
    Location of the configuration property setting.
    Location tags are frequently used for configuration settings that must be set more precisely than per application or per virtual directory.
    For example, a setting for a particular file or directory could use a location tag.
    Location tags are also used if a particular section is locked.
    In such an instance, the configuration system would have to use a location tag in one of the parent configuration files.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the IIS configuration property to add.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PSPath
  description: |+
    Specifies the configuration path.
    This can be either an IIS configuration path in the formatcomputer name/webroot/apphost, or the IIS module path in this format IIS:\sites\Default Web Site.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Type
  description: |+
    The type of property to add.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Value
  description: |+
    The value of the configuration property to add.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: WebAdministration.Add-WebConfigurationProperty
name: Add-WebConfigurationProperty
description: |-
  Adds a property to an IIS configuration section.
  Globbing is supported.
metadata:
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  online version: https://docs.microsoft.com/powershell/module/webadministration/add-webconfigurationproperty?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
