### YamlMime:PowershellCmdlet
summary: |-
  Creates a backup of an IIS configuration.
module: WebAdministration
notes: ""
links:
- text: Restore-WebConfiguration
  href: ./Restore-WebConfiguration.yml
syntaxes:
- Backup-WebConfiguration [-Name] <String> [<CommonParameters>]
examples:
- title: '-------------- EXAMPLE 1: Backing up an IIS configuration --------------'
  code: |-
    IIS:\>Backup-WebConfiguration -Name MyIISBackup
  description: |-
    Demonstrates how to create a backup of your IIS configuration in a folder named "MyIISBackup".

    Name Creation Date

    ---- -------------

    MyIISBackup 2/20/2009 12:00:00 AM
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The name of the folder created to store the backup files.
    If a backup with the name specified already exists, an error is returned.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: WebAdministration.Backup-WebConfiguration
name: Backup-WebConfiguration
description: |-
  Creates a backup of an IIS configuration.
  A folder named with the value of theNameparameter is created for the backup in the $env:Windir\System32\inetsrv\backup folder.
metadata:
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  online version: https://docs.microsoft.com/powershell/module/webadministration/backup-webconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
