### YamlMime:PowershellCmdlet
summary: |-
  Converts an IIS virtual directory to an IIS Web application.
module: WebAdministration
notes: ""
links:
- text: Get-WebApplication
  href: ./Get-WebApplication.yml
- text: New-WebApplication
  href: ./New-WebApplication.yml
- text: Remove-WebApplication
  href: ./Remove-WebApplication.yml
syntaxes:
- >-
  ConvertTo-WebApplication [-ApplicationPool <String>] [-Force] [[-PSPath] <String[]>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'EXAMPLE 1: Convert a Virtual Directory to a Web Application'
  code: |-
    md $env:systemdrive\inetpub\Contoso
    New-WebVirtualDirectory -Site "Default Web Site" -Name ContosoVDir -physicalPath $env:systemdrive\inetpub\Contoso 
    ConvertTo-WebApplication "IIS:\Sites\Default Web Site\ContosoVDir"
  description: |-
    This example creates a physical directory named "Contoso." It then creates a virtual directory in IIS that uses that physical directory.
    It then converts the virtual directory to a Web application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ApplicationPool
  description: |+
    The application pool in which the application runs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the conversion without prompting you for confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PSPath
  description: |+
    Specifies the configuration path.
    This can be either an IIS configuration path in the format computer name/webroot/apphost, or the IIS module path in this format IIS:\sites\Default Web Site.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: WebAdministration.ConvertTo-WebApplication
name: ConvertTo-WebApplication
description: |-
  Converts an IIS virtual directory to an IIS Web application.
metadata:
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  online version: https://docs.microsoft.com/powershell/module/webadministration/convertto-webapplication?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
