### YamlMime:PowershellCmdlet
summary: |-
  Gets the location of a specified configuration setting.
module: WebAdministration
notes: ""
syntaxes:
- Get-WebConfigurationLocation [[-Name] <String>] [-Recurse] [[-PSPath] <String[]>] [<CommonParameters>]
examples:
- title: '-------------- EXAMPLE 1: Get location tags --------------'
  code: |-
    IIS:\>Get-WebConfigurationLocation
  description: |-
    Returns all locations that are configured by using location tags.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the name of the configuration location.
    All locations are returned if theNameparameter is not specified.

  defaultValue: None
  pipelineInput: true
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PSPath
  description: |+
    An IIS configuration path to the location.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Recurse
  description: |+
    If theRecurseparameter is used, locations within the hierarchy of the specified location are also returned.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: WebAdministration.Get-WebConfigurationLocation
name: Get-WebConfigurationLocation
description: |-
  Gets the location of a specified configuration setting.
metadata:
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  online version: https://docs.microsoft.com/powershell/module/webadministration/get-webconfigurationlocation?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
