### YamlMime:PowershellCmdlet
summary: |-
  Gets the file system path of the Web.config file.
module: WebAdministration
notes: ""
syntaxes:
- Get-WebConfigFile [[-PSPath] <String[]>] [<CommonParameters>]
examples:
- title: '-------------- EXAMPLE 1: Open the Web.config file for the Default Web Site --------------'
  code: |-
    IIS:\>notepad (Get-WebConfigFile 'IIS:\Sites\Default Web Site')
  description: |-
    This example demonstrates how to use Notepad to open the web.config file for the Default Web Site.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PSPath
  description: |+
    The IIS module namespace path to the site containing the Web.config file.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
uid: WebAdministration.Get-WebConfigFile
name: Get-WebConfigFile
description: |-
  Gets the physical path of the IIS configuration file at the specified IIS module namespace path.
metadata:
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  online version: https://docs.microsoft.com/powershell/module/webadministration/get-webconfigfile?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
