### YamlMime:PowershellCmdlet
summary: |-
  Renames a configuration location.
module: WebAdministration
notes: ""
syntaxes:
- >-
  Rename-WebConfigurationLocation -Name <String> -NewName <String> [-Recurse] [[-PSPath] <String[]>] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: '-------------- EXAMPLE 1: Rename a configuration location --------------'
  code: |-
    IIS:\>Rename-WebConfigurationLocation -Name 'Default Web Site/oldApp' -NewName 'Default Web Site/newApp' -PSPath IIS:\
  description: |-
    Renames a configuration location on the Default Web Site from "oldApp" to "newApp."
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    The current name of the configuration location to rename.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: NewName
  isRequired: true
  description: |+
    The new name of the configuration location to rename.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PSPath
  description: |+
    An IIS configuration path to the location to rename.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Recurse
  description: |+
    If included, specifies that location tags defined lower in the location hierarchy should also be renamed.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: WebAdministration.Rename-WebConfigurationLocation
name: Rename-WebConfigurationLocation
description: |-
  Renames the specified configuration location with the new name provided.
metadata:
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  online version: https://docs.microsoft.com/powershell/module/webadministration/rename-webconfigurationlocation?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
