### YamlMime:PowershellCmdlet
summary: |-
  Gets an object that contains detailed information about the configuration of a Storage Spaces pool.
module: StorageSpaces
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-SpacesConfiguration [-StoragePoolFriendlyName] <String>
examples:
- title: Example 1 - Get Storage Spaces configuration for a local pool
  code: |-
    PS C:\>Get-SpacesConfiguration -StoragePoolFriendlyName Internal

    StoragePoolFriendlyName        : Internal
    HealthStatus                   : Healthy
    IsReadOnly                     : False
    IsClusteredStoragePool         : False
    ThinProvisionAlertThreshold    : 70 %
    StoragePoolFreeGigabytes       : 1514
    StoragePoolUsedSpacePercent    : 45.79
    StoragePoolFreeSpacePercent    : 54.21
    OperationalStatus              : OK
    NumberofPhysicalDisksInPool    : 4
    NumberofStorageSpacesInPool    : 1
    NumberofUnhealthyPhysicalDisks : 0
    NumberofUnhealthyStorageSpaces : 0

    OperationalStatus         : OK
    HealthStatus              : Healthy
    DiskUniqueID              : EBB5E72780C7E1119CC4F46D0439C015
    DriveLetter               : S
    VolumeSize                : 1374254243840
    SizeRemaining             : 691400519680
    VolumeObjectID            : \\?\Volume{27e7b5f2-c780-11e1-9cc4-f46d0439c015}\
    FileSystem                : NTFS
    BackingPhysicalDisks      : {Seagate ST750LX003-1AC15 SCSI Disk Device, Seagate ST750LX003-1AC15 SCSI Disk Device,
    Seagate ST750LX003-1AC15 SCSI Disk Device, Seagate ST750LX003-1AC15 SCSI Disk Device}
    PoolFriendlyName          : Internal
    SpaceFriendlyName         : Data
    StorageSpaceUniqueID      : EBB5E72780C7E1119CC4F46D0439C015
    IsManualAttach            : False
    DetachedReason            : None
    SpaceUsageAlertPercentage : {70}
  description: ""
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: StoragePoolFriendlyName
  isRequired: true
  description: |+
    Specifies the friendly name of the storage pool.

  defaultValue: None
  acceptWildcardCharacters: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
uid: StorageSpaces.Get-SpacesConfiguration
name: Get-SpacesConfiguration
description: |-
  The Get-SpacesConfiguration cmdlet gets an object that contains detailed status of the specified storage pool, as well as detailed information about all storage spaces and associated volumes.

  Note: If the pool in question is clustered, additional details are included about associated failover clustering resources.
metadata:
  external help file: StorSpaces2_Cmdlets.xml
  Module Name: StorageSpaces
  ms.date: 10/30/2017
  online version: https://docs.microsoft.com/powershell/module/storagespaces/get-spacesconfiguration?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-SpacesConfiguration
