### YamlMime:PowershellCmdlet
summary: |-
  Returns current MPIO settings for Storage Spaces.
module: StorageSpaces
notes: ""
outputs:
- name: <xref href="Microsoft.PowerShell.Commands.Internal.Format.FormatStartData" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.PowerShell.Commands.Internal.Format.GroupStartData" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.PowerShell.Commands.Internal.Format.FormatEntryData" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.PowerShell.Commands.Internal.Format.GroupEndData" data-throw-if-not-resolved="False" />
  description: ""
- name: <xref href="Microsoft.PowerShell.Commands.Internal.Format.FormatEndData" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- Get-StorageSpacesMpioConfiguration
examples:
- title: Example 1 - Get current MPIO settings for Storage Spaces
  code: |-
    PS C:\>Get-StorageSpacesMpioConfiguration
  description: ""
  summary: ""
uid: StorageSpaces.Get-StorageSpacesMpioConfiguration
name: Get-StorageSpacesMpioConfiguration
description: |-
  The Get-StorageSpacesMPIOConfiguration cmdlet gets the current MPIO settings for Storage Spaces, as well as whether MPIO is configured optimally for Storage Spaces.
metadata:
  external help file: StorSpaces2_Cmdlets.xml
  Module Name: StorageSpaces
  ms.date: 10/30/2017
  online version: https://docs.microsoft.com/powershell/module/storagespaces/get-storagespacesmpioconfiguration?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-StorageSpacesMpioConfiguration
