### YamlMime:PowershellCmdlet
summary: |-
  Sets the configuration information for the specified printer.
module: PrintManagement
notes: ""
inputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/MSFT_Printer" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet accepts one printer object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet produces no output objects.
links:
- text: Get-PrintConfiguration
  href: ./Get-PrintConfiguration.yml
syntaxes:
- >-
  Set-PrintConfiguration [-PrinterObject] <CimInstance> [-AsJob] [-CimSession <CimSession>] [-Collate <Boolean>]

   [-Color <Boolean>] [-DuplexingMode <DuplexingModeEnum>] [-PaperSize <PaperSizeEnum>]

   [-PrintTicketXml <String>] [-ThrottleLimit <Int32>] [-Confirm] [-WhatIf]
- >-
  Set-PrintConfiguration [-PrinterName] <String> [-AsJob] [-CimSession <CimSession>] [-Collate <Boolean>]

   [-Color <Boolean>] [-ComputerName <String>] [-DuplexingMode <DuplexingModeEnum>] [-PaperSize <PaperSizeEnum>]

   [-PrintTicketXml <String>] [-ThrottleLimit <Int32>] [-Confirm] [-WhatIf]
- >-
  Set-PrintConfiguration [-InputObject] <CimInstance> [-AsJob] [-CimSession <CimSession>]

   [-ThrottleLimit <Int32>] [-Confirm] [-WhatIf]
examples:
- title: '-------------------------- Example 1: Set the default paper size -------------------------- xample:Set the default paper size'
  code: |-
    PS C:\> Set-PrintConfiguration -PrinterName "Microsoft XPS Document Writer" -PaperSize A4
  description: |-
    This command sets the default paper size of the printer named "Microsoft XPS Document Writer" printer to A4.
  summary: ""
- title: 'Example 2: Set the default paper size using print configuration object'
  code: |-
    PS C:\>$PrintConfiguration = Get-PrintConfiguration -PrinterName "Microsoft XPS Document Writer"




    PS C:\>$PrintConfiguration.paperSize = A4




    PS C:\>Set-PrintConfiguration -InputObject $PrintConfiguration
  description: |-
    This set of commands retrieves a print configuration object into a variable ($PrintConfiguration) using Get-PrintConfiguration, sets the paper size in the printer configuration object to A4 and then passes the contents of the variable to **Set-PrintConfiguration**.
  summary: ""
- title: 'Example 3: Set the default paper size of all printers'
  code: |-
    PS C:\>$printers = get-printer * 
    foreach ($printer in $printers)
    { 
        Set-printconfiguration -printerName $printer.name -PaperSize A4
    }
  description: |-
    This command gets all the printers into a variable $printers and then loops through all the printers and displays the properties.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    ps_cimcommon_asjob

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" />
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a New-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227967 or Get-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227966 cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Collate
  description: |+
    Specifies whether or not to collate the output of the printer by default.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Color
  description: |+
    Specifies whether the printer should use either color or grayscale printing by default.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ComputerName
  description: |+
    Specifies the name of the computer on which the printer is located.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="DuplexingModeEnum" data-throw-if-not-resolved="False" />
  name: DuplexingMode
  description: |+
    Specifies the duplexing mode the printer uses by default.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Specifies the object which contains the printer configuration settings to set.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PaperSizeEnum" data-throw-if-not-resolved="False" />
  name: PaperSize
  description: |+
    Specifies the paper size the printer uses by default.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PrinterName
  isRequired: true
  description: |+
    Specifies the printer on which to set the configuration information.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" />
  name: PrinterObject
  isRequired: true
  description: |+
    Specifies the object which contains the printer on which to change the configuration settings.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PrintTicketXml
  description: |+
    Specifies the print ticket XML defining the default print settings for this printer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: PrintManagement.Set-PrintConfiguration
name: Set-PrintConfiguration
description: |-
  The **Set-PrintConfiguration** cmdlet sets the printer configuration for the specified printer. 
  Using the **Set-PrintConfiguration** cmdlet, you can manage the configuration of the following features:

  ● Collate

  ● Color

  ● Duplexing Mode

  ● N-Up

  ● Paper Size

  The **Set-PrintConfiguration** cmdlet also accepts print configuration objects using Get-PrintConfiguration cmdlet.

  You cannot use wildcard characters with **Set-PrintConfiguration**.
  You can use **Set-PrintConfiguration** in a Windows PowerShell remoting session.

  You need administrator privileges to use **Set-PrintConfiguration**.
metadata:
  external help file: PrintMgmt_Cmdlets.xml
  Module Name: PrintManagement
  online version: https://docs.microsoft.com/powershell/module/printmanagement/set-printconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
