### YamlMime:PowerShellCmdlet1
uid: ADFS.Export-AdfsDeploymentSQLScript
name: Export-AdfsDeploymentSQLScript
module: ADFS
isPreview: false
summary: |-
  Generates SQL scripts to create the AD FS database and to grant permissions.
description: |-
  The **Export-AdfsDeploymentSQLScript** cmdlet generates the SQL scripts that you can use separately to create the Active Directory Federation Services (AD FS) database and to grant permissions.
parameters:
  cmdletParameters:
  - name: Confirm
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: "False"
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: DestinationFolder
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the folder in which the cmdlet saves the generated SQL scripts.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ServiceAccountName
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the Active Directory® Domain Services account under which the AD FS service runs.
      All nodes in the farm must use the same service account.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: "False"
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Export-AdfsDeploymentSQLScript
        -DestinationFolder <String>
        -ServiceAccountName <String>
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
examples:
- title: 'Example 1: Export SQL deployment scripts'
  description: |-
    ```
    PS C:\> Export-AdfsDeploymentSQLScript -DestinationFolder ".\ScriptFolder" -ServiceAccountName "ContosoDomain\PattiFuller"
    ```

    This command exports SQL deployment scripts for AD FS installation on behalf of the specified AD FS service account.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  document type: cmdlet
  external help file: Microsoft.IdentityServer.Deployment.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/adfs/export-adfsdeploymentsqlscript?view=windowsserver2016-ps&wt.mc_id=ps-gethelp
  Module Name: ADFS
  ms.date: 12/20/2016
  PlatyPS schema version: 2024-05-01
  title: Export-AdfsDeploymentSQLScript
