### YamlMime:PowershellCmdlet
summary: |-
  Modifies configuration settings for a server application role of an application in AD FS.
module: ADFS
notes: ""
links:
- text: Add-AdfsServerApplication
  href: ./Add-AdfsServerApplication.yml
- text: Get-AdfsServerApplication
  href: ./Get-AdfsServerApplication.yml
- text: Remove-AdfsServerApplication
  href: ./Remove-AdfsServerApplication.yml
syntaxes:
- >-
  Set-AdfsServerApplication [-TargetIdentifier] <String> [-Identifier <String>] [-Name <String>]

   [-RedirectUri <String[]>] [-Description <String>] [-ADUserPrincipalName <String>]

   [-JWTSigningCertificate <X509Certificate2[]>] [-JWTSigningCertificateRevocationCheck <RevocationSetting>]

   [-ChangeClientSecret] [-ResetClientSecret] [-JWKSUri <Uri>] [-ReloadJWTSigningKeys] [-JWKSFile <String>]

   [-LogoutUri <String>] [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-AdfsServerApplication [-TargetName] <String> [-Identifier <String>] [-Name <String>]

   [-RedirectUri <String[]>] [-Description <String>] [-ADUserPrincipalName <String>]

   [-JWTSigningCertificate <X509Certificate2[]>] [-JWTSigningCertificateRevocationCheck <RevocationSetting>]

   [-ChangeClientSecret] [-ResetClientSecret] [-JWKSUri <Uri>] [-ReloadJWTSigningKeys] [-JWKSFile <String>]

   [-LogoutUri <String>] [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-AdfsServerApplication [-TargetApplication] <ServerApplication> [-Identifier <String>] [-Name <String>]

   [-RedirectUri <String[]>] [-Description <String>] [-ADUserPrincipalName <String>]

   [-JWTSigningCertificate <X509Certificate2[]>] [-JWTSigningCertificateRevocationCheck <RevocationSetting>]

   [-ChangeClientSecret] [-ResetClientSecret] [-JWKSUri <Uri>] [-ReloadJWTSigningKeys] [-JWKSFile <String>]

   [-LogoutUri <String>] [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ADUserPrincipalName
  description: |+
    Specifies the Active Directory account that corresponds to the confidential client that is registered.
    The only client authentication method available for use with Active Directory accounts is Windows Integrated Authentication (WIA).

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ChangeClientSecret
  description: |+
    Indicates that this cmdlet changes the client secret value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Description
  description: |+
    Specifies a description.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Identifier
  description: |+
    Specifies an ID.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: JWKSFile
  description: |+
    Specifies a file that contains a JSON Web Token (JWT).

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Uri" data-throw-if-not-resolved="False" />
  name: JWKSUri
  description: |+
    Specifies the URI of a JWT.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="X509Certificate2" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: JWTSigningCertificate
  description: |+
    Specifies an array of signing certificates for JWT.
    This public certificate is used to validate signatures for JWTs issued by this client for authenticating itself against AD FS by using the private key JWT client authentication method.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="RevocationSetting" data-throw-if-not-resolved="False" />
  name: JWTSigningCertificateRevocationCheck
  description: |+
    Specifies revocation checks to perform to validate signatures for JWTs sent by confidential clients.
    The acceptable values for this parameter are:

    - None 
    - CheckEndCert 
    - CheckEndCertCacheOnly 
    - CheckChain 
    - CheckChainCacheOnly 
    - CheckChainExcludeRoot 
    - CheckChainExcludeRootCacheOnly

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: None, CheckEndCert, CheckEndCertCacheOnly, CheckChain, CheckChainCacheOnly, CheckChainExcludeRoot, CheckChainExcludeRootCacheOnly
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: LogoutUri
  description: |+
    Specifies the logout URI for the OAuth 2.0 client to register with the AD FS. When AD FS initiates a logout it redirects the client's user-agent to this URI by rendering this URI in an iframe. The value of this parameter must be an absolute URI, may include a query component, and must not include a fragment component. This parameter is available with the Windows Update KB4038801 installed.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies a name.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: RedirectUri
  description: |+
    Specifies an array of redirection URIs for the OAuth 2.0 client to register with AD FS.
    The redirection URI is specified by the OAuth 2.0 client when it requests authorization to access a resource in ADFS.

    The redirection URI specified by the client must already be registered with AD FS.
    It must correspond to the client identifier for that OAuth 2.0 client.
    If the client ID and redirection URI correspond to a pre-registered OAuth 2.0 client and the resource owner authorized access by providing their credentials, ADFS delivers the authorization code or access token by redirecting the client's user-agent back to this redirection URI.

    The value of this parameter must match exactly the redirection URI that is specified by the OAuth 2.0 client when requesting authorization.
    This includes trailing slashes '/', if they are required.
    We recommended the use of more secure schemes such as https in a redirection URI.

    For Windows Store applications that authenticate by using the Windows Web Authentication Broker, use the `ms-app://` scheme for a redirection URI.
    If you are developing a Windows Store application, obtain the redirection URI for your application by using the following code fragment: 

    `Uri redirectURI = Windows.Security.Authentication.Web.WebAuthenticationBroker.GetCurrentApplicationCallbackUri();`

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ReloadJWTSigningKeys
  description: |+
    Indicates that this cmdlet reloads JWT signing keys.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ResetClientSecret
  description: |+
    Indicates that this cmdlet resets the client secret value.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="ServerApplication" data-throw-if-not-resolved="False" />
  name: TargetApplication
  isRequired: true
  description: |+
    Specifies the server application.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetIdentifier
  isRequired: true
  description: |+
    Specifies the ID of the server application.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetName
  isRequired: true
  description: |+
    Specifies the name of the server application.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: ADFS.Set-AdfsServerApplication
name: Set-AdfsServerApplication
description: |-
  The **Set-AdfsServerApplication** cmdlet modifies configuration settings for a server application role of an application in Active Directory Federation Services (AD FS).
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IdentityServer.Management.dll-Help.xml
  Module Name: ADFS
  ms.date: 09/19/2017
  online version: https://docs.microsoft.com/powershell/module/adfs/set-adfsserverapplication?view=windowsserver2016-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-AdfsServerApplication
