### YamlMime:PowerShellCmdlet1
uid: UEV.Import-UevConfiguration
name: Import-UevConfiguration
module: UEV
isPreview: false
summary: |-
  Imports the UE-V configuration.
description: |-
  The **Import-UevConfiguration** cmdlet imports the Microsoft User Experience Virtualization (UE-V) computer configuration from a settings migration (.uev) file.
  You must have administrative credentials to run this cmdlet.
parameters:
  cmdletParameters:
  - name: Confirm
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Prompts you for confirmation before running the cmdlet.
    aliases:
    - cf
    defaultValue: "False"
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Path
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the path of the settings migration file.
      The cmdlet imports the UE-V configuration from the settings migration file (.uev file) that you specify.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: WhatIf
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      Shows what would happen if the cmdlet runs.
      The cmdlet is not run.
    aliases:
    - wi
    defaultValue: "False"
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Import-UevConfiguration
        [-Path] <String>
        [-WhatIf]
        [-Confirm]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
examples:
- title: 'Example 1: Import the UE-V configuration'
  description: |-
    ```
    PS C:\> Import-UevConfiguration -Path "ContosoUev.uev"
    ```

    This command imports the UE-V computer configuration from the settings migration file named ContosoUev.uev.
links:
- text: Get-UevConfiguration
  href: ./Get-UevConfiguration.yml
- text: Set-UevConfiguration
  href: ./Set-UevConfiguration.yml
- text: Clear-UevConfiguration
  href: ./Clear-UevConfiguration.yml
- text: Export-UevConfiguration
  href: ./Export-UevConfiguration.yml
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  document type: cmdlet
  external help file: Microsoft.Uev.Commands.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/uev/import-uevconfiguration?view=windowsserver2016-ps&wt.mc_id=ps-gethelp
  Module Name: UEV
  ms.date: 12/20/2016
  PlatyPS schema version: 2024-05-01
  title: Import-UevConfiguration
