### YamlMime:PowerShellCmdlet1
uid: IISAdministration.Remove-IISConfigAttribute
name: Remove-IISConfigAttribute
module: IISAdministration
isPreview: false
summary: |-
  Removes a configuration attribute from an IIS configuration section or configuration element attribute.
description: |-
  The **Remove-IISConfigAttribute** cmdlet removes a configuration attribute from an Internet Information Services (IIS) configuration section or a configuration element.
  The value removed is the value for the given ConfigurationElement and not necessarily the effective value for a given site / virtual directory / folder etc.
  To obtain the effective attribute values, always retrieve the configuration element by specifying the commit path as the deepest level possible.
  Even the configuration attribute is not defined at that level, the parent attributes are scanned and the effective configuration element is returned.
  You can then work on this ConfigurationElement to get/set/remove configuration attribute values.
parameters:
  cmdletParameters:
  - name: AttributeName
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the attribute that is to be deleted.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "2"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ConfigElement
    type: <xref href="ConfigurationElement" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the IIS ConfigurationSection or ConfigurationElement from which the matching attribute is to be deleted.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "1"
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Remove-IISConfigAttribute
        [-ConfigElement] <ConfigurationElement>
        [-AttributeName] <String>
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="Microsoft.Web.Administration.ConfigurationElement" data-throw-if-not-resolved="False" />
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Remove a configuration attribute from an IIS web site.'
  description: |-
    ```
    PS C:\> Get-IISSite "Default Web Site" | Get-IISConfigElement -ChildElementName "limits" | Remove-IISConfigAttribute -AttributeName "MaxUrlSegments"
    ```

    This command removes the configuration attribute value for the attribute MaxUrlSegments from the Default Web Site, defaulting to its parent or system wide defaults.
- title: 'Example 2: Remove configuration attribute values from different parts of the configuration store:'
  description: |-
    ```
    PS C:\> Get-IISConfigSection "system.webServer/asp" | Remove-IISConfigAttribute -AttributeName "ScriptErrorMessage"
    ```

    This command removes the global attribute value for ScriptErrorMessage, defaulting to the schema default.
links:
- text: Get-IISConfigAttributeValue
  href: ./Get-IISConfigAttributeValue.yml
- text: Set-IISConfigAttributeValue
  href: ./Set-IISConfigAttributeValue.yml
- text: IIS Administration Cmdlets for Windows PowerShell
  href: index.yml
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  document type: cmdlet
  external help file: Microsoft.IIS.Powershell.Commands.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/iisadministration/remove-iisconfigattribute?view=windowsserver2025-ps&wt.mc_id=ps-gethelp
  Module Name: IISAdministration
  ms.date: 12/20/2016
  PlatyPS schema version: 2024-05-01
  title: Remove-IISConfigAttribute
