### YamlMime:PowershellCmdlet
summary: |-
  Adds a collection element to an IIS configuration collection.
module: WebAdministration
notes: ""
inputs:
- name: <xref href="PSObject" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="PSObject" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-WebConfigurationProperty
  href: ./Add-WebConfigurationProperty.yml
- text: Set-WebConfiguration
  href: ./Set-WebConfiguration.yml
syntaxes:
- >-
  Add-WebConfiguration [-Value <PSObject>] [-Clr <String>] [-AtElement <Hashtable>] [-AtIndex <Int32>]

   [-AtName <String>] [-Force] [-Location <String[]>] [-Filter] <String[]> [[-PSPath] <String[]>] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Add a new default document'
  code: |-
    IIS:\> Add-WebConfiguration -Filter "//defaultDocument/files" -PSPath "IIS:\sites\Default Web Site" -AtIndex 0 -Value @{value="new-index.html"}
  description: |-
    This command adds a new default document to the default document collection of the default website.
    By specifying a value of 0 for the *atIndex* parameter, the new default document is inserted at the top of the list.
  summary: ""
parameters:
- type: <xref href="Hashtable" data-throw-if-not-resolved="False" />
  name: AtElement
  description: |+
    Specifies the element in the collection location at which this cmdlet inserts the value.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: AtIndex
  description: |+
    Specifies the index at which this cmdlet inserts the value.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AtName
  description: |+
    Specifies the name at which this cmdlet inserts the value.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Clr
  description: |+
    Specifies the version of the .NET Framework in the form vn.n, such as v4.0 or v2.0.
    The default is v4.0.
    Specify this parameter only when the *PSPath* parameter is set to either Machine or Machine/Webroot.
    If *PSPath* is not set to one of these values and the *Clr* parameter is set, Windows PowerShell® ignores the value of *Clr* and returns a warning.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Filter
  isRequired: true
  description: |+
    Specifies the IIS configuration section or an XPath query that returns either a configuration section or a configuration element that contains a collection.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the creation of a configuration, and overrides existing element settings.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Location
  description: |+
    Specifies the location to which this cmdlet writes the configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PSPath
  description: |+
    Specifies the configuration path.
    This path can be either an IIS configuration path in the format computer name/webroot/apphost, or the IIS module path in the format IIS:\sites\Default Web Site.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Value
  description: |+
    Specifies the value to add to the configuration collection.
    You can specify a single value or a value/key combination in a hash table.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: WebAdministration.Add-WebConfiguration
name: Add-WebConfiguration
description: |-
  The **Add-WebConfiguration** cmdlet adds a collection element to an existing Internet Information Services (IIS) configuration collection.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  ms.date: 12/27/2016
  online version: https://docs.microsoft.com/powershell/module/webadministration/add-webconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Add-WebConfiguration
