### YamlMime:PowershellCmdlet
summary: |-
  Clears the request tracing configuration from a website.
module: WebAdministration
notes: ""
links:
- text: Disable-WebRequestTracing
  href: ./Disable-WebRequestTracing.yml
- text: Clear-WebRequestTracingSetting
  href: ./Clear-WebRequestTracingSetting.yml
syntaxes:
- Clear-WebRequestTracingSettings [[-Name] <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Remove request tracing from the default website'
  code: |-
    IIS:\> Clear-WebRequestTracingSettings -Name "Default Web Site"
  description: |-
    This command removes request tracing from the default website.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies the name of the site from which request tracing settings are cleared.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: WebAdministration.Clear-WebRequestTracingSettings
name: Clear-WebRequestTracingSettings
description: |-
  The **Clear-WebRequestTracingSettings** cmdlet clears request tracing settings from the specified website.
  It also disables request tracing for the site.
  This cmdlet is identical to Clear-WebRequestTracingSetting, which is preferred.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  ms.date: 12/27/2016
  online version: https://docs.microsoft.com/powershell/module/webadministration/clear-webrequesttracingsettings?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Clear-WebRequestTracingSettings
