### YamlMime:PowershellCmdlet
summary: |-
  Converts an IIS virtual directory to an IIS web application.
module: WebAdministration
notes: ""
links:
- text: Get-WebApplication
  href: ./Get-WebApplication.yml
- text: New-WebApplication
  href: ./New-WebApplication.yml
- text: New-WebVirtualDirectory
  href: ./New-WebVirtualDirectory.yml
- text: Remove-WebApplication
  href: ./Remove-WebApplication.yml
syntaxes:
- >-
  ConvertTo-WebApplication [-ApplicationPool <String>] [-Force] [[-PSPath] <String[]>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Convert a virtual directory to a web application'
  code: |-
    IIS:\> Md $Env:systemdrive\inetpub\Contoso 
    IIS:\> New-WebVirtualDirectory -Site "Default Web Site" -Name "ContosoVDir" -PhysicalPath "$Env:systemdrive\inetpub\Contoso" 
    IIS:\> ConvertTo-WebApplication -PSPath "IIS:\Sites\Default Web Site\ContosoVDir"
  description: |-
    The first command creates a physical directory named Contoso.

    The second command creates a virtual directory in IIS that uses that physical directory.

    The last command converts the virtual directory to a web application.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ApplicationPool
  description: |+
    Specifies the application pool in which the application runs.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the command to run without asking for user confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PSPath
  description: |+
    Specifies the configuration path.
    This can be either an IIS configuration path in the format computer name/webroot/apphost, or the IIS module path in the format IIS:\sites\Default Web Site.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: WebAdministration.ConvertTo-WebApplication
name: ConvertTo-WebApplication
description: |-
  The **ConvertTo-WebApplication** cmdlet converts an Internet Information Services (IIS) virtual directory to an IIS web application.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  ms.date: 12/27/2016
  online version: https://docs.microsoft.com/powershell/module/webadministration/convertto-webapplication?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: ConvertTo-WebApplication
