### YamlMime:PowershellCmdlet
summary: |-
  Renames a configuration location.
module: WebAdministration
notes: ""
links:
- text: Get-WebConfigurationLocation
  href: ./Get-WebConfigurationLocation.yml
- text: Remove-WebConfigurationLocation
  href: ./Remove-WebConfigurationLocation.yml
syntaxes:
- >-
  Rename-WebConfigurationLocation -Name <String> -NewName <String> [-Recurse] [[-PSPath] <String[]>] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Rename a configuration location'
  code: |-
    IIS:\> Rename-WebConfigurationLocation -Name "Default Web Site/oldApp" -NewName "Default Web Site/newApp" -PSPath "IIS:\"
  description: |-
    This command renames a configuration location on the default website from oldApp to newApp.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the current name of the configuration location.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: NewName
  isRequired: true
  description: |+
    Specifies the new name of the configuration location.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PSPath
  description: |+
    Specifies an IIS configuration path to the location.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Recurse
  description: |+
    Indicates that the cmdlet renames location tags defined lower in the location hierarchy.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: WebAdministration.Rename-WebConfigurationLocation
name: Rename-WebConfigurationLocation
description: |-
  The **Rename-WebConfigurationLocation** cmdlet renames the specified configuration location with the new name provided.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  ms.date: 12/27/2016
  online version: https://docs.microsoft.com/powershell/module/webadministration/rename-webconfigurationlocation?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Rename-WebConfigurationLocation
