### YamlMime:PowershellCmdlet
summary: |-
  Changes the value of an IIS configuration element.
module: WebAdministration
notes: ""
inputs:
- name: <xref href="PSObject" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="PSObject" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Add-WebConfiguration
  href: ./Add-WebConfiguration.yml
- text: Backup-WebConfiguration
  href: ./Backup-WebConfiguration.yml
- text: Clear-WebConfiguration
  href: ./Clear-WebConfiguration.yml
- text: Get-WebConfiguration
  href: ./Get-WebConfiguration.yml
- text: Restore-WebConfiguration
  href: ./Restore-WebConfiguration.yml
- text: Select-WebConfiguration
  href: ./Select-WebConfiguration.yml
syntaxes:
- >-
  Set-WebConfiguration -Value <PSObject> [-Metadata <String>] [-Clr <String>] [-Force] [-Location <String[]>]

   [-Filter] <String[]> [[-PSPath] <String[]>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-WebConfiguration -InputObject <Object> [-Metadata <String>] [-Clr <String>] [-Force] [-Location <String[]>]

   [-Filter] <String[]> [[-PSPath] <String[]>] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Set new bindings on an existing website'
  code: |-
    IIS:\> Set-WebConfiguration -Filter "/system.applicationHost/sites/site[@name=" DemoSite"]/bindings" -PSPath "IIS:\" -Value (@{protocol="http";bindingInformation="*:80:DemoSite1"},@{protocol="http";bindingInformation="*:80:DemoSite2"})
  description: |-
    This command replaces the existing bindings of the Web site named DemoSite with new bindings.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Clr
  description: |+
    Specifies the version of the .NET Framework in the form vn.n, such as v4.0 or v2.0.
    The default is v4.0.
    Specify this parameter only when the *PSPath* parameter is set to either Machine or Machine/Webroot.
    If *PSPath* is not set to one of these values and the *Clr* parameter is set, Windows PowerShell® ignores the value of *Clr* and returns a warning.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Filter
  isRequired: true
  description: |+
    Specifies the IIS configuration section or an XPath query that returns a configuration element.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Indicates that the cmdlet causes the configuration setting to be set at a level in the configuration hierarchy above a lock in the configuration.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Object" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Specifies an input object that contains values to set for configuration elements.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Location
  description: |+
    Specifies the location of the configuration setting.
    Location tags are frequently used for configuration settings that must be set more precisely than per application or per virtual directory.
    For example, a setting for a particular file or directory could use a location tag.
    Location tags are also used if a particular section is locked.
    In such an instance, the configuration system would have to use a location tag in one of the parent configuration files.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Metadata
  description: |+
    If this parameter is specified, configuration metadata such as encryption or locking settings can be changed.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: PSPath
  description: |+
    Specifies the configuration path.
    This path can be either an IIS configuration path in the format computer name/webroot/apphost, or the IIS module path in the format IIS:\sites\Default Web Site.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PSObject" data-throw-if-not-resolved="False" />
  name: Value
  isRequired: true
  description: |+
    Specifies the value of the configuration setting to change.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: v, val
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: WebAdministration.Set-WebConfiguration
name: Set-WebConfiguration
description: |-
  The **Set-WebConfiguration** cmdlet changes the value of an Internet Information Services (IIS) configuration element.
  Specify an element as a configuration section or an XPath query.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IIS.PowerShell.Provider.dll-Help.xml
  Module Name: WebAdministration
  ms.date: 12/27/2016
  online version: https://docs.microsoft.com/powershell/module/webadministration/set-webconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-WebConfiguration
