### YamlMime:PowershellCmdlet
summary: |-
  Exports the custom configuration of an external authentication provider to a file.
module: ADFS
notes: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Import-AdfsAuthenticationProviderConfigurationData
  href: ./Import-AdfsAuthenticationProviderConfigurationData.yml
syntaxes:
- >-
  Export-AdfsAuthenticationProviderConfigurationData -Name <String> -FilePath <String> [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Export configuration data'
  code: |-
    PS C:\> Export-AdfsAuthenticationProviderConfigurationData -Name "ContosoExternalAuthProvider" -FilePath "C:\share\test.txt"
  description: |-
    This command exports configuration data for the authentication provider named ContosoExternalAuthProvider to the file C:\share\test.txt
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FilePath
  isRequired: true
  description: |+
    Specifies a file path.
    The cmdlet exports the configuration data to a file that you specify.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  isRequired: true
  description: |+
    Specifies the name of the authentication provider to export.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: ADFS.Export-AdfsAuthenticationProviderConfigurationData
name: Export-AdfsAuthenticationProviderConfigurationData
description: |-
  The **Export-AdfsAuthenticationProviderConfigurationData** cmdlet exports the custom configuration of an external authentication provider to a file.
  Before you use this cmdlet, verify that the external authentication provider supports a custom configuration.
metadata:
  external help file: Microsoft.IdentityServer.Management.dll-Help.xml
  Module Name: ADFS
  ms.date: 10/30/2017
  online version: https://docs.microsoft.com/powershell/module/adfs/export-adfsauthenticationproviderconfigurationdata?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Export-AdfsAuthenticationProviderConfigurationData
