### YamlMime:PowershellCmdlet
summary: |-
  Sets the SMB client configuration.
module: SmbShare
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-SmbClientConfiguration
  href: ./Get-SmbClientConfiguration.yml
syntaxes:
- >-
  Set-SmbClientConfiguration [-ConnectionCountPerRssNetworkInterface <UInt32>]

   [-DirectoryCacheEntriesMax <UInt32>] [-DirectoryCacheEntrySizeMax <UInt32>] [-DirectoryCacheLifetime <UInt32>]

   [-DormantFileLimit <UInt32>] [-EnableBandwidthThrottling <Boolean>]

   [-EnableByteRangeLockingOnReadOnlyFiles <Boolean>] [-EnableInsecureGuestLogons <Boolean>]

   [-EnableLargeMtu <Boolean>] [-EnableLoadBalanceScaleOut <Boolean>] [-EnableMultiChannel <Boolean>]

   [-EnableSecuritySignature <Boolean>] [-ExtendedSessionTimeout <UInt32>] [-FileInfoCacheEntriesMax <UInt32>]

   [-FileInfoCacheLifetime <UInt32>] [-FileNotFoundCacheEntriesMax <UInt32>]

   [-FileNotFoundCacheLifetime <UInt32>] [-KeepConn <UInt32>] [-MaxCmds <UInt32>]

   [-MaximumConnectionCountPerServer <UInt32>] [-OplocksDisabled <Boolean>] [-RequireSecuritySignature <Boolean>]

   [-SessionTimeout <UInt32>] [-UseOpportunisticLocking <Boolean>] [-WindowSizeThreshold <UInt32>] [-Force]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Set the SMB client configuration'
  code: |-
    PS C:\>Set-SmbClientConfiguration -ConnectionCountPerRssNetworkInterface 8
    Confirm 
    Are you sure you want to perform this action? 
    Performing operation 'Modify' on Target 'SMB Client Configuration'. 
    [Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
  description: |-
    This command sets the SMB client configuration.
  summary: ""
- title: 'Example 2: Set the SMB client configuration without confirmation'
  code: |-
    PS C:\>Set-SmbClientConfiguration -ConnectionCountPerRssNetworkInterface 4 -Force
  description: |-
    This command sets the SMB client configuration without user confirmation.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: ConnectionCountPerRssNetworkInterface
  description: |+
    Specifies the SMB connection count per each RSS network interface.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: DirectoryCacheEntriesMax
  description: |+
    Specifies the maximum cache entries that can be in the directory cache.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: DirectoryCacheEntrySizeMax
  description: |+
    Specifies the maximum size of directory cache entry.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: DirectoryCacheLifetime
  description: |+
    Specifies the directory cache lifetime.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: DormantFileLimit
  description: |+
    Specifies the dormant file limit.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableBandwidthThrottling
  description: |+
    Indicates that bandwidth throttling is enabled.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableByteRangeLockingOnReadOnlyFiles
  description: |+
    Indicates that byte range locking on read-only files is enabled.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableInsecureGuestLogons
  description: |+
    Indicates whether SMB client will allow insecure guest logons to an SMB server.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableLargeMtu
  description: |+
    Indicates that large MTU is enabled.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableLoadBalanceScaleOut
  description: |+
    Indicates whether load balance scale out is enabled.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableMultiChannel
  description: |+
    Indicates that multi-channel is enabled.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: EnableSecuritySignature
  description: |+
    Indicates that the security signature is enabled.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: ExtendedSessionTimeout
  description: |+
    Specifies the extended session time-out.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: FileInfoCacheEntriesMax
  description: |+
    Specifies the maximum number entries that can be in the file information cache.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: FileInfoCacheLifetime
  description: |+
    Specifies the file information cache lifetime.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: FileNotFoundCacheEntriesMax
  description: |+
    Specifies the maximum number entries that can be in the file not found cache.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: FileNotFoundCacheLifetime
  description: |+
    Specifies the file not found cache lifetime.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the command to run without asking for user confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: KeepConn
  description: |+
    Specifies the time, in seconds, before the SMB client session is automatically disconnected.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: MaxCmds
  description: |+
    Specifies the maximum number of concurrent outstanding network requests that the SMB client supports.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: MaximumConnectionCountPerServer
  description: |+
    Specifies the maximum connection count per server.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: OplocksDisabled
  description: |+
    Indicates that opportunistic locks are disabled.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: RequireSecuritySignature
  description: |+
    Indicates that the security signature is required.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: SessionTimeout
  description: |+
    Specifies the session time-out.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: UseOpportunisticLocking
  description: |+
    Indicates that opportunistic locks are used.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: WindowSizeThreshold
  description: |+
    Specifies the window size threshold.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: SmbShare.Set-SmbClientConfiguration
name: Set-SmbClientConfiguration
description: |-
  The **Set-SmbClientConfiguration** cmdlet sets the Server Message Block (SMB) client configuration.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: SmbClientConfiguration.cdxml-help.xml
  Module Name: SmbShare
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/smbshare/set-smbclientconfiguration?view=windowsserver2016-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-SmbClientConfiguration
