### YamlMime:PowerShellCmdlet1
uid: RemoteDesktop.Get-RDLicenseConfiguration
name: Get-RDLicenseConfiguration
module: RemoteDesktop
isPreview: false
summary: |-
  Retrieves the current settings for the RD Licensing server and the licensing mode of the Remote Desktop deployment.
description: |-
  The **Get-RDLicenseConfiguration** cmdlet retrieves the current settings for the Remote Desktop Licensing (RD Licensing) server and the licensing mode of the Remote Desktop deployment.

  RD Licensing servers manage the Remote Desktop Services client access licenses (RDS CALs) that each device or user requires to connect to a Remote Desktop Session Host (RD Session Host) server.
parameters:
  cmdletParameters:
  - name: ConnectionBroker
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the Remote Desktop Connection Broker (RD Connection Broker) server for this Remote Desktop deployment.
      If you do not supply a value, the cmdlet uses the fully qualified domain name (FQDN) of the local computer.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-RDLicenseConfiguration
        [[-ConnectionBroker] <String>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
examples:
- title: 'Example 1: Get the Remote Desktop license configuration'
  description: |-
    ```
    PS C:\> Get-RDLicenseConfiguration -ConnectionBroker "Rdcb.Contoso.com"
    ```

    This command gets the Remote Desktop license configuration for the RD Connection Broker server named Rdcb.Contoso.com.
links:
- text: Set-RDLicenseConfiguration
  href: ./Set-RDLicenseConfiguration.yml
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  document type: cmdlet
  external help file: RemoteDesktop.psm1-help.xml
  HelpUri: https://learn.microsoft.com/powershell/moduleremotedesktop/get-rdlicenseconfiguration?view=windowsserver2016-ps&wt.mc_id=ps-gethelp
  Module Name: RemoteDesktop
  ms.date: 12/20/2016
  PlatyPS schema version: 2024-05-01
  title: Get-RDLicenseConfiguration
