### YamlMime:PowershellCmdlet
summary: |-
  Restores the specified DirectAccess client configuration to the defaults.
module: DirectAccessClientComponents
notes: ""
inputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root/StandardCimv2/MSFT_DAClientExperienceConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet accepts as input a CIM object that contains a DA client experience configuration.
outputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-DAClientExperienceConfiguration
  href: ./Get-DAClientExperienceConfiguration.yml
- text: Set-DAClientExperienceConfiguration
  href: ./Set-DAClientExperienceConfiguration.yml
syntaxes:
- >-
  Reset-DAClientExperienceConfiguration [-PolicyStore <String>] [-GPOSession <String>] [-CorporateResources]

   [-IPsecTunnelEndpoints] [-PreferLocalNamesAllowed] [-UserInterface] [-SupportEmail] [-FriendlyName]

   [-ManualEntryPointSelectionAllowed] [-GslbFqdn] [-ForceTunneling] [-CustomCommands] [-PassiveMode] [-PassThru]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Reset-DAClientExperienceConfiguration -InputObject <CimInstance[]> [-CorporateResources]

   [-IPsecTunnelEndpoints] [-PreferLocalNamesAllowed] [-UserInterface] [-SupportEmail] [-FriendlyName]

   [-ManualEntryPointSelectionAllowed] [-GslbFqdn] [-ForceTunneling] [-CustomCommands] [-PassiveMode] [-PassThru]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Reset the friendly name of a client experience configuration'
  code: |-
    PS C:\>Reset-DAClientExperienceConfiguration -PolicyStore "Contoso\GPO1" -FriendlyName "Traveling Policy"
  description: |-
    This cmdlet resets the friendly name of a client experience configuration.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete. 

    The cmdlet immediately returns an object that represents the job and then displays the command prompt. 
    You can continue to work in the session while the job completes. 
    To manage the job, use the `*-Job` cmdlets. 
    To get the job results, use the [Receive-Job](https://go.microsoft.com/fwlink/?LinkID=113372) cmdlet. 

    For more information about Windows PowerShell background jobs, see [about_Jobs](https://go.microsoft.com/fwlink/?LinkID=113251).

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: CorporateResources
  description: |+
    Resets the CorporateResources property of the specified configuration to a non-configured state.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: CustomCommands
  description: |+
    Resets the CustomCommands property of the specified configuration to a non-configured state.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ForceTunneling
  description: |+
    Resets the ForceTunneling property of the specified configuration to a non-configured state.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: FriendlyName
  description: |+
    Resets the FriendlyName property of the specified configuration to a non-configured state.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GPOSession
  description: |+
    Specifies the Group Policy session to send configuration information.
    You can use *GPOSession* with the **NetGPO** cmdlets to aggregate multiple operations performed on a Group Policy Object.

    *GPOSession* cannot be used in conjunction with *PolicyStore*.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: GslbFqdn
  description: |+
    Resets the GslbFqdn property of the specified configuration to a non-configured state.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the input object that is used in a pipeline command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: IPsecTunnelEndpoints
  description: |+
    Resets the IPsecTunnelEndpoints property of the specified configuration to a non-configured state.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ManualEntryPointSelectionAllowed
  description: |+
    Resets the ManualEntryPointSelectionAllowed property of the specified configuration to a non-configured state.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassiveMode
  description: |+
    Resets the PassiveMode property of the specified configuration to a non-configured state.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Sends items from an interactive window down the pipeline as input to other cmdlets.
    By default, this cmdlet does not generate any output.
    However, to send items from the interactive window down the pipeline, click to select the items and then click OK.
    Shift-click and Ctrl-click are supported.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PolicyStore
  description: |+
    Specifies the policy store into which the cmdlet adds the reset configuration properties.

    To add the reset configuration properties to a Group Policy Object, specify the GPO name using the format "Domain\GPOName".

    To add the reset configuration properties to a computer's local GPO, specify the computer's local GPO name in the format "GPO:\<computername\>".

    **PolicyStore** cannot be used in conjunction with **GPOSession**.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PreferLocalNamesAllowed
  description: |+
    Resets the PreferLocalNamesAllowed property of the specified configuration to a non-configured state.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SupportEmail
  description: |+
    Resets the SupportEmail property of the specified configuration to a non-configured state.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: UserInterface
  description: |+
    Resets the UserInterface property of the specified configuration to a non-configured state.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: DirectAccessClientComponents.Reset-DAClientExperienceConfiguration
name: Reset-DAClientExperienceConfiguration
description: |-
  The **Reset-DAClientExperienceConfiguration** cmdlet restores the specified DirectAccess client configuration to the defaults.

  All **DAClientExperienceConfiguration** cmdlets have an ADMX file which can also configure these settings.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: MSFT_DAClientExperienceConfiguration.cdxml-help.xml
  Module Name: DirectAccessClientComponents
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/directaccessclientcomponents/reset-daclientexperienceconfiguration?view=windowsserver2019-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Reset-DAClientExperienceConfiguration
