### YamlMime:PowershellCmdlet
summary: |-
  Disables a web application.
module: MBAM
notes: ""
links:
- text: Enable-MbamWebApplication
  href: enable-mbamwebapplication.yml
- text: Get-MbamWebApplication
  href: get-mbamwebapplication.yml
- text: Test-MbamWebApplication
  href: test-mbamwebapplication.yml
syntaxes:
- Disable-MbamWebApplication [-Force] [-AdministrationPortal] [-WhatIf] [-Confirm] [<CommonParameters>]
- Disable-MbamWebApplication [-Force] [-AgentService] [-WhatIf] [-Confirm] [<CommonParameters>]
- Disable-MbamWebApplication [-Force] [-SelfServicePortal] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Disable Administration and Monitoring Website'
  code: |-
    PS C:\> Disable-MbamWebApplication -AdministrationPortal
    Are you sure you want to perform this action?
    Performing operation "Disable MBAM Web Application (AdministrationPortal) feature"
    [Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):
  description: |-
    This command disables the Administration and Monitoring Portal feature.
    The cmdlet prompts you to confirm the operation.
  summary: ""
- title: 'Example 2: Disable the Self-Service Portal'
  code: |-
    PS C:\> Disable-MbamWebApplication -SelfServicePortal -Force
  description: |-
    This command disables the Self-Service Portal feature.
    The command specifies the *Force* parameter, and, therefore, the cmdlet does not prompt you to confirm the operation.
  summary: ""
- title: 'Example 3: Disable Agent Services'
  code: |-
    PS C:\> Disable-MbamWebApplication -AgentService
    Are you sure you want to perform this action?
    Performing operation "Disable MBAM Web Application (AgentService) feature"
    [Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):
  description: |-
    This command disables the Agent Services feature.
    The cmdlet prompts you to confirm the operation.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AdministrationPortal
  isRequired: true
  description: |+
    Indicates that this cmdlet acts on the Administration and Monitoring Website web application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AgentService
  isRequired: true
  description: |+
    Indicates that this cmdlet acts on the Agent Services web application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: None
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the command to run without asking for user confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SelfServicePortal
  isRequired: true
  description: |+
    Indicates that this cmdlet acts on the Self-Service Portal web application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs. The cmdlet is not run.

  defaultValue: None
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: MBAM.Disable-MbamWebApplication
name: Disable-MbamWebApplication
description: |-
  The **Disable-MbamWebApplication** cmdlet disables a Microsoft BitLocker Administration and Monitoring (MBAM) web application.
  This cmdlet removes any website files that the **Enable-MbamWebApplication** cmdlet installed when you enabled the application.
metadata:
  description: Use this topic to help manage MDOP technologies with Windows PowerShell.
  external help file: Microsoft.MBAM.Server.Commands.dll-Help.xml
  ms.date: 12/05/2016
  ms.devlang: powershell
  schema: 2.0.0
  title: Disable-MbamWebApplication
