### YamlMime:PowershellCmdlet
summary: |-
  Gets the configuration of a web application.
module: MBAM
notes: ""
outputs:
- name: <xref href="Microsoft.MBAM.Server.Commands.AdministrationPortalConfiguration, Microsoft.MBAM.Server.Commands.SelfServicePortalConfiguration, Microsoft.MBAM.Server.Commands.AgentServiceConfiguration" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Disable-MbamWebApplication
  href: disable-mbamwebapplication.yml
- text: Enable-MbamWebApplication
  href: enable-mbamwebapplication.yml
- text: Test-MbamWebApplication
  href: test-mbamwebapplication.yml
syntaxes:
- Get-MbamWebApplication [-AdministrationPortal] [<CommonParameters>]
- Get-MbamWebApplication [-AgentService] [<CommonParameters>]
- Get-MbamWebApplication [-SelfServicePortal] [<CommonParameters>]
examples:
- title: 'Example 1: Get the configuration of Administration and Monitoring Website'
  code: |-
    PS C:\> Get-MbamWebApplication -AdministrationPortal
    Name                                 : Administration Web Portal
    Enabled                              : True
    Description                          : This feature includes the Help Desk web application for administration.
    InstallationPath                     : C:\inetpub
    HostName                             : MYSERVER.contoso.com
    Port                                 : 443
    CertificateThumbprint                : E2A7EA5533890D6567E40DFC46F53B3D31D6B689
    ComplianceAndAuditDBConnectionString : Integrated Security=SSPI;Data Source=MyDatabaseServer;Initial Catalog="MBAM Compliance Status";
    RecoveryDBConnectionString           : Integrated Security=SSPI;Data Source=MyDatabaseServer;Initial Catalog="MBAM Recovery and Hardware";
    WebServiceApplicationPoolUser        : MyDomain\MBAMWebServicesAccount
    VirtualDirectory                     : /HelpDesk
    CMIntegrationMode                    : False
    ReportUrl                            : https://MyReportsServer/ReportServer
    AdvancedHelpdeskAccessGroup          : MyDomain\AdvancedHelpdeskUserGroup
    HelpdeskAccessGroup                  : MyDomain\HelpdeskUserGroup
    ReportsReadOnlyAccessGroup           : MyDomain\ReportsUserGroup
  description: |-
    This command gets the configuration of the Administration and Monitoring Website feature on the local server.
  summary: ""
- title: 'Example 2: Get the configuration of the Self-Service Portal'
  code: |-
    PS C:\> Get-MbamWebApplication -SelfServicePortal
    Name                                 : Self Service Web Portal
    Enabled                              : True
    Description                          : This feature includes the Self Service web application that allows users to recover their own BitLocker keys.
    InstallationPath                     : C:\inetpub
    HostName                             : MYSERVER.contoso.com
    Port                                 : 443
    CertificateThumbprint                : E2A7EA5533890D6567E40DFC46F53B3D31D6B689
    ComplianceAndAuditDBConnectionString : Integrated Security=SSPI;Data Source=MyDatabaseServer;Initial Catalog="MBAM Compliance Status";
    RecoveryDBConnectionString           : Integrated Security=SSPI;Data Source=MyDatabaseServer;Initial Catalog="MBAM Recovery and Hardware";
    WebServiceApplicationPoolUser        : MyDomain\MBAMWebServicesAccount
    VirtualDirectory                     : /SelfService
  description: |-
    This command gets the configuration of the Self-Service Portal feature on the local server.
  summary: ""
- title: 'Example 3: Get the configuration of the Agent Services feature'
  code: |-
    PS C:\> Get-MbamWebApplication -AgentService
    Name                                 : Agent Web Services
    Enabled                              : True
    Description                          : This feature includes the web services to support the MBAM agent.
    InstallationPath                     : C:\inetpub
    HostName                             : MYSERVER.contoso.com
    Port                                 : 443
    ComplianceAndAuditDBConnectionString : Integrated Security=SSPI;Data Source=MyDatabaseServer;Initial Catalog="MBAM Compliance Status";
    RecoveryDBConnectionString           : Integrated Security=SSPI;Data Source=MyDatabaseServer;Initial Catalog="MBAM Recovery and Hardware";
    WebServiceApplicationPoolUser        : MyDomain\MBAMWebServicesAccount
    CMIntegrationMode                    : False
  description: |-
    This command gets the configuration of the Agent Services feature on the local server.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AdministrationPortal
  isRequired: true
  description: |+
    Indicates that this cmdlet acts on the Administration and Monitoring Website web application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AgentService
  isRequired: true
  description: |+
    Indicates that this cmdlet acts on the Agent Services web application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SelfServicePortal
  isRequired: true
  description: |+
    Indicates that this cmdlet acts on the Self-Service Portal web application.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: MBAM.Get-MbamWebApplication
name: Get-MbamWebApplication
description: |-
  The **Get-MbamWebApplication** cmdlet gets the configuration of a Microsoft BitLocker Administration and Monitoring (MBAM) web application.
metadata:
  description: Use this topic to help manage MDOP technologies with Windows PowerShell.
  external help file: Microsoft.MBAM.Server.Commands.dll-Help.xml
  ms.date: 12/05/2016
  ms.devlang: powershell
  schema: 2.0.0
  title: Get-MbamWebApplication
