### YamlMime:PowerShellCmdlet1
uid: ADFS.Get-AdfsWebApiApplication
name: Get-AdfsWebApiApplication
module: ADFS
isPreview: false
summary: |-
  Gets Web API application roles in AD FS.
description: |-
  The **Get-AdfsWebApiApplication** cmdlet gets Web API application roles in Active Directory Federation Services (AD FS).
parameters:
  cmdletParameters:
  - name: Application
    type: <xref href="WebApiApplication" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a Web API application to get.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ApplicationObject
      position: "0"
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ApplicationGroup
    type: <xref href="ApplicationGroup" data-throw-if-not-resolved="False" />
    description: |-
      Specifies an application group for which to get Web API applications.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ApplicationGroupObject
      position: "0"
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ApplicationGroupIdentifier
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the ID of an application group for which to get Web API applications.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ApplicationGroupIdentifier
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Identifier
    type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Specifies an ID of a Web API application to get.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Identifier
      position: "0"
      isRequired: false
      valueFromPipeline: true
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Specifies an array of names of Web API applications to get.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: Name
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PrefixIdentifier
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the prefix identifier of Web API applications to get.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: PrefixIdentifier
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-AdfsWebApiApplication
        [[-Identifier] <String[]>]
        [<CommonParameters>]
    ```
  parameterSetName: Identifier
  isDefault: true
- syntax: |-
    ```Syntax
    Get-AdfsWebApiApplication
        [-Name] <String[]>
        [<CommonParameters>]
    ```
  parameterSetName: Name
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AdfsWebApiApplication
        [-PrefixIdentifier] <String>
        [<CommonParameters>]
    ```
  parameterSetName: PrefixIdentifier
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AdfsWebApiApplication
        [-Application] <WebApiApplication>
        [<CommonParameters>]
    ```
  parameterSetName: ApplicationObject
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AdfsWebApiApplication
        [-ApplicationGroupIdentifier] <String>
        [<CommonParameters>]
    ```
  parameterSetName: ApplicationGroupIdentifier
  isDefault: false
- syntax: |-
    ```Syntax
    Get-AdfsWebApiApplication
        [-ApplicationGroup] <ApplicationGroup>
        [<CommonParameters>]
    ```
  parameterSetName: ApplicationGroupObject
  isDefault: false
inputs:
- name: <xref href="Microsoft.IdentityServer.Management.Resources.WebApiApplication" data-throw-if-not-resolved="False" />
  description: |-
    WebApiApplication objects are received by the *Application* parameter.
- name: <xref href="Microsoft.IdentityServer.Management.Resources.ApplicationGroup" data-throw-if-not-resolved="False" />
  description: |-
    ApplicationGroup objects are received by the *ApplicationGroup* parameter.
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    String objects are received by the *ApplicationGroupIdentifier*, *Identifier*, and *Name* parameters.
outputs:
- name: <xref href="Microsoft.IdentityServer.Management.Resources.WebApiApplication" data-throw-if-not-resolved="False" />
  description: |-
    Returns one or more WebApiApplication objects that represent the web API applications of the Federation Service.
links:
- text: Add-AdfsWebApiApplication
  href: ./Add-AdfsWebApiApplication.yml
- text: Remove-AdfsWebApiApplication
  href: ./Remove-AdfsWebApiApplication.yml
- text: Set-AdfsWebApiApplication
  href: ./Set-AdfsWebApiApplication.yml
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  document type: cmdlet
  external help file: Microsoft.IdentityServer.Management.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/adfs/get-adfswebapiapplication?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  Module Name: ADFS
  ms.date: 12/20/2016
  PlatyPS schema version: 2024-05-01
  title: Get-AdfsWebApiApplication
