### YamlMime:PowershellCmdlet
summary: |-
  Gets AD FS web customization configuration settings.
module: ADFS
notes: ""
outputs:
- name: <xref href="Microsoft.IdentityServer.Management.Resources.AdfsWebConfig" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet generates an **AdfsWebConfig** object that represents AD FS web customization configuration settings.
    This object contains the following properties: 

    - ActiveThemeName: **System.String**
    - CDCCookieReader: **System.Uri**
    - CDCCookieWriter: **System.Uri**
    - HRDCookieLifetime: **System.Int32**
    - HRDCookieEnabled: **System.Boolean**
    - ContextCookieEnabled: **System.Boolean**
links:
- text: Set-AdfsWebConfig
  href: ./Set-AdfsWebConfig.yml
syntaxes:
- Get-AdfsWebConfig [<CommonParameters>]
examples:
- title: 'Example 1: Get configuration settings'
  code: |-
    PS C:\> Get-AdfsWebConfig

    ActiveThemeName      : Default
    CDCCookieReader      :
    CDCCookieWriter      :
    HRDCookieLifetime    : 30
    HRDCookieEnabled     : True
    ContextCookieEnabled : True
  description: |-
    This command gets the web customization configuration settings.
  summary: ""
uid: ADFS.Get-AdfsWebConfig
name: Get-AdfsWebConfig
description: |-
  The **Get-AdfsWebConfig** cmdlet gets Active Directory Federation Services (AD FS) web customization configuration settings.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IdentityServer.Management.dll-Help.xml
  Module Name: ADFS
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/adfs/get-adfswebconfig?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-AdfsWebConfig
