### YamlMime:PowershellCmdlet
summary: |-
  Removes the relying party trust object for the Web Application Proxy.
module: ADFS
notes: ""
links:
- text: Add-AdfsWebApplicationProxyRelyingPartyTrust
  href: ./Add-AdfsWebApplicationProxyRelyingPartyTrust.yml
- text: Disable-AdfsWebApplicationProxyRelyingPartyTrust
  href: ./Disable-AdfsWebApplicationProxyRelyingPartyTrust.yml
- text: Enable-AdfsWebApplicationProxyRelyingPartyTrust
  href: ./Enable-AdfsWebApplicationProxyRelyingPartyTrust.yml
- text: Get-AdfsWebApplicationProxyRelyingPartyTrust
  href: ./Get-AdfsWebApplicationProxyRelyingPartyTrust.yml
- text: Set-AdfsWebApplicationProxyRelyingPartyTrust
  href: ./Set-AdfsWebApplicationProxyRelyingPartyTrust.yml
syntaxes:
- Remove-AdfsWebApplicationProxyRelyingPartyTrust [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Remove the relying party trust'
  code: |-
    PS C:\> Remove-AdfsWebApplicationProxyRelyingPartyTrust
  description: |-
    This command removes the relying party trust object for the Web Application Proxy, which denies all access to web applications through the proxy.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: ADFS.Remove-AdfsWebApplicationProxyRelyingPartyTrust
name: Remove-AdfsWebApplicationProxyRelyingPartyTrust
description: |-
  The **Remove-AdfsWebApplicationProxyRelyingPartyTrust** cmdlet removes the relying party trust object for Web Application Proxy.
  If you remove the relying party trust, Web Application Proxy blocks all external access through the proxy.
  Use this cmdlet if you plan to recreate the trust later.
  To temporarily block access through the proxy, you can, instead, disable the relying party trust by using the **Disable-AdfsWebApplicationProxyRelyingPartyTrust** cmdlet.

  The Web Application Proxy relying party trust is useful to manage global network access from outside the corporate network.
  By setting authentication and authorization policies, an administrator can restrict access to internal web applications and services that are published through the Web Application Proxy.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IdentityServer.Management.dll-Help.xml
  Module Name: ADFS
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/adfs/remove-adfswebapplicationproxyrelyingpartytrust?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Remove-AdfsWebApplicationProxyRelyingPartyTrust
