### YamlMime:PowershellCmdlet
summary: |-
  Modifies application permissions.
module: ADFS
notes: ""
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
  description: |-
    String objects are received by the *AddScope*, *Description*, *RemoveScope*, *ScopeNames*, *TargetClientRoleIdentifier*, *TargetIdentifier*, and *TargetServerRoleIdentifier* parameters.
- name: <xref href="Microsoft.IdentityServer.Management.Resources.OAuthPermission" data-throw-if-not-resolved="False" />
  description: |-
    OAuthPermission objects are received by the *InputObject* parameter.
links:
- text: Get-AdfsApplicationPermission
  href: ./Get-AdfsApplicationPermission.yml
- text: Grant-AdfsApplicationPermission
  href: ./Grant-AdfsApplicationPermission.yml
- text: Revoke-AdfsApplicationPermission
  href: ./Revoke-AdfsApplicationPermission.yml
syntaxes:
- >-
  Set-AdfsApplicationPermission [-TargetIdentifier] <String> [-ScopeNames <String[]>] [-Description <String>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-AdfsApplicationPermission [-TargetIdentifier] <String> -AddScope <String[]> [-Description <String>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-AdfsApplicationPermission [-TargetIdentifier] <String> -RemoveScope <String[]> [-Description <String>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-AdfsApplicationPermission [-InputObject] <OAuthPermission> [-ScopeNames <String[]>] [-Description <String>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-AdfsApplicationPermission [-InputObject] <OAuthPermission> -AddScope <String[]> [-Description <String>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-AdfsApplicationPermission [-InputObject] <OAuthPermission> -RemoveScope <String[]> [-Description <String>]

   [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-AdfsApplicationPermission [[-TargetClientRoleIdentifier] <String>] [[-TargetServerRoleIdentifier] <String>]

   [-ScopeNames <String[]>] [-Description <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-AdfsApplicationPermission [[-TargetClientRoleIdentifier] <String>] [[-TargetServerRoleIdentifier] <String>]

   -AddScope <String[]> [-Description <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-AdfsApplicationPermission [[-TargetClientRoleIdentifier] <String>] [[-TargetServerRoleIdentifier] <String>]

   -RemoveScope <String[]> [-Description <String>] [-WhatIf] [-Confirm] [<CommonParameters>]
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: AddScope
  isRequired: true
  description: ""
  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Description
  description: |+
    Specifies a description.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="OAuthPermission" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Specifies an **OAuthPermission** object.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: RemoveScope
  isRequired: true
  description: ""
  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ScopeNames
  description: ""
  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetClientRoleIdentifier
  description: ""
  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetIdentifier
  isRequired: true
  description: |+
    Specifies the identifier of the target.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: TargetServerRoleIdentifier
  description: |+
    Specifies the identifier of the target server role.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: ADFS.Set-AdfsApplicationPermission
name: Set-AdfsApplicationPermission
description: |-
  The **Set-AdfsApplicationPermission** cmdlet modifies application permissions.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IdentityServer.Management.dll-Help.xml
  Module Name: ADFS
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/adfs/set-adfsapplicationpermission?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-AdfsApplicationPermission
