### YamlMime:PowershellCmdlet
summary: |-
  Modifies properties of the relying party trust object for the Web Application Proxy.
module: ADFS
notes: ""
links:
- text: Add-AdfsWebApplicationProxyRelyingPartyTrust
  href: ./Add-AdfsWebApplicationProxyRelyingPartyTrust.yml
- text: Disable-AdfsWebApplicationProxyRelyingPartyTrust
  href: ./Disable-AdfsWebApplicationProxyRelyingPartyTrust.yml
- text: Enable-AdfsWebApplicationProxyRelyingPartyTrust
  href: ./Enable-AdfsWebApplicationProxyRelyingPartyTrust.yml
- text: Get-AdfsWebApplicationProxyRelyingPartyTrust
  href: ./Get-AdfsWebApplicationProxyRelyingPartyTrust.yml
- text: Remove-AdfsWebApplicationProxyRelyingPartyTrust
  href: ./Remove-AdfsWebApplicationProxyRelyingPartyTrust.yml
syntaxes:
- >-
  Set-AdfsWebApplicationProxyRelyingPartyTrust [-AlwaysRequireAuthentication <Boolean>] [-Identifier <String[]>]

   [-AccessControlPolicyName <String>] [-AccessControlPolicyParameters <Object>]

   [-IssuanceAuthorizationRules <String>] [-IssuanceAuthorizationRulesFile <String>]

   [-IssuanceTransformRules <String>] [-IssuanceTransformRulesFile <String>]

   [-AdditionalAuthenticationRules <String>] [-AdditionalAuthenticationRulesFile <String>] [-Name <String>]

   [-NotBeforeSkew <Int32>] [-Notes <String>] [-PassThru] [-TokenLifetime <Int32>] [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Specify authorization rules by using a file'
  code: |-
    PS C:\> Set-AdfsWebApplicationProxyRelyingPartyTrust -IssuanceAuthorizationRulesFile "C:\Rules\RulesFile07"
  description: |-
    This command specifies authorization rules for the Web Application Proxy relying party trust, based on a file that contains the rules.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AccessControlPolicyName
  description: ""
  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Object" data-throw-if-not-resolved="False" />
  name: AccessControlPolicyParameters
  description: |+
    Specifies access control policy parameters.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AdditionalAuthenticationRules
  description: |+
    Specifies rules for additional authentication on the proxy.
    For more information about the claim language for rules, see [Understanding Claim Rule Language in AD FS 2.0 & Higher](https://social.technet.microsoft.com/wiki/contents/articles/4792.understanding-claim-rule-language-in-ad-fs-2-0-higher.aspx) on TechNet.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: AdditionalAuthenticationRulesFile
  description: |+
    Specifies a file that contains rules for additional authentication for this relying party.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: AlwaysRequireAuthentication
  description: |+
    Indicates whether access requires authentication, even if this relying party has previously authenticated credentials for access.
    Specify a value of $True to require users to always supply credentials to access sensitive resources.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Identifier
  description: |+
    Specifies an array of unique identifiers.
    The proxy uses the identifiers that you specify to specify its corresponding relying party trust when it initiates sign-in requests to obtain tokens for itself.
    No other trust can use an identifier from this list.
    As common practice, you can use Uniform Resource Identifiers (URIs) as unique identifiers for a relying party trust, or you can use any string.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: IssuanceAuthorizationRules
  description: |+
    Specifies the issuance authorization rules for issuing claims to this relying party.
    Issuance authorization rules control access to applications that are enabled for pre-authentication through Active Directory Federation Services (AD FS), and then accessed through the proxy.
    By default, all authenticated users can access applications.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: IssuanceAuthorizationRulesFile
  description: |+
    Specifies a file that contains the issuance authorization rules for issuing claims to this relying party.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: IssuanceTransformRules
  description: |+
    Specifies the issuance transform rules for issuing claims to this relying party.
    You should not, typically, modify the value of this setting.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: IssuanceTransformRulesFile
  description: |+
    Specifies a file that contains the issuance transform rules for issuing claims to this relying party.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Name
  description: |+
    Specifies a name.
    The cmdlet modifies the Web Application Proxy relying party trust that has the friendly name that you specify.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: NotBeforeSkew
  description: |+
    Specifies the skew, as an integer, for the time stamp that marks the beginning of the validity period.
    The higher this number is, the farther back in time the validity period begins with respect to the time that the claims are issued for the relying party.
    By default, this value is 0.
    Specify a positive value if validation fails on the Web Application Proxy relying party because the validity period has not yet begun.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Notes
  description: |+
    Specifies notes.
    The cmdlet stores the notes that you specify for the Web Application Proxy relying party trust.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: TokenLifetime
  description: |+
    Specifies the duration, in minutes, for which the claims that are issued to the relying party are valid.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: ADFS.Set-AdfsWebApplicationProxyRelyingPartyTrust
name: Set-AdfsWebApplicationProxyRelyingPartyTrust
description: |-
  The **Set-AdfsWebApplicationProxyRelyingPartyTrust** cmdlet modifies properties of the relying party trust object for Web Application Proxy.
  You can modify authentication and authorization policies that control all external access through the proxy.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IdentityServer.Management.dll-Help.xml
  Module Name: ADFS
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/adfs/set-adfswebapplicationproxyrelyingpartytrust?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-AdfsWebApplicationProxyRelyingPartyTrust
