### YamlMime:PowerShellCmdlet1
uid: Hyper-V.Get-VMNetworkAdapterFailoverConfiguration
name: Get-VMNetworkAdapterFailoverConfiguration
module: Hyper-V
isPreview: false
summary: |-
  Gets the IP address of a virtual network adapter configured to be used when a virtual machine fails over.
description: |-
  The **Get-VMNetworkAdapterFailoverConfiguration** cmdlet gets the IP address configuration of a virtual network adapter configured to be used when a virtual machine fails over.
parameters:
  cmdletParameters:
  - name: CimSession
    type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Runs the cmdlet in a remote session or on a remote computer.
      Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
      The default is the current session on the local computer.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: VMName
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ComputerName
    type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Specifies one or more Hyper-V hosts on which the IP address configuration of a virtual network adapter is to be retrieved.
      NetBIOS names, IP addresses, and fully qualified domain names are allowable.
      The default is the local computer.
      Use localhost or a dot (.) to specify the local computer explicitly.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: VMName
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Credential
    type: <xref href="PSCredential" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Specifies one or more user accounts that have permission to perform this action.
      The default is the current user.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: VMName
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: VM
    type: <xref href="VirtualMachine" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Specifies the virtual machine for which you want to get the IP address configuration of a virtual network adapter.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: VMObject
      position: "0"
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: VMName
    type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Specifies the name of the virtual machine for which you want to get the IP address configuration of a virtual network adapter.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: VMName
      position: "0"
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: VMNetworkAdapter
    type: <xref href="VMNetworkAdapter" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Specifies the virtual network adapter whose IP address configuration you want to get.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: ResourceObject
      position: "0"
      isRequired: true
      valueFromPipeline: true
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: VMNetworkAdapterName
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the name of the virtual network adapter whose IP address configuration you want to get.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: VMName
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    - name: VMObject
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-VMNetworkAdapterFailoverConfiguration
        [-VMName] <String[]>
        [-CimSession <CimSession[]>]
        [-ComputerName <String[]>]
        [-Credential <PSCredential[]>]
        [-VMNetworkAdapterName <String>]
        [<CommonParameters>]
    ```
  parameterSetName: VMName
  isDefault: true
- syntax: |-
    ```Syntax
    Get-VMNetworkAdapterFailoverConfiguration
        [-VM] <VirtualMachine[]>
        [-VMNetworkAdapterName <String>]
        [<CommonParameters>]
    ```
  parameterSetName: VMObject
  isDefault: false
- syntax: |-
    ```Syntax
    Get-VMNetworkAdapterFailoverConfiguration
        [-VMNetworkAdapter] <VMNetworkAdapter[]>
        [<CommonParameters>]
    ```
  parameterSetName: ResourceObject
  isDefault: false
outputs:
- name: <xref href="Microsoft.HyperV.PowerShell.VMNetworkAdapterFailoverSetting" data-throw-if-not-resolved="False" />
examples:
- title: Example 1
  description: |-
    ```
    PS C:\> Get-VMNetworkAdapterFailoverConfiguration VM01
    ```

    This example gets the failover IP address configuration of all virtual network adapters attached to a virtual machine named VM01.
- title: Example 2
  description: |-
    ```
    PS C:\> Get-VMNetworkAdapterFailoverConfiguration VM01 -VMNetworkAdapterName NetworkAdapter
    ```

    This example gets the failover IP address configuration of a virtual network adapter named NetworkAdapter on a virtual machine named VM01.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  document type: cmdlet
  external help file: Microsoft.HyperV.PowerShell.Cmdlets.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/hyper-v/get-vmnetworkadapterfailoverconfiguration?view=windowsserver2025-ps&wt.mc_id=ps-gethelp
  Module Name: Hyper-V
  ms.date: 12/20/2016
  PlatyPS schema version: 2024-05-01
  title: Get-VMNetworkAdapterFailoverConfiguration
