### YamlMime:PowershellCmdlet
summary: |-
  Gets the domain name configuration of the Windows Server Essentials computer.
module: WSSCmdlets
notes: ""
outputs:
- name: <xref href="Microsoft.WindowsServerSolutions.RemoteAccess.Domains.DomainNameConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet generates the currently active domain name configuration object.
links:
- text: Set-WssDomainNameConfiguration
  href: ./Set-WssDomainNameConfiguration.yml
syntaxes:
- Get-WssDomainNameConfiguration [<CommonParameters>]
examples:
- title: 'Example 1: Get the domain name configuration of the Windows Server'
  code: |-
    PS C:\> Get-WssDomainNameConfiguration
  description: |-
    This command gets the domain name configuration of Windows Server Essentials.
  summary: ""
uid: WSSCmdlets.Get-WssDomainNameConfiguration
name: Get-WssDomainNameConfiguration
description: |-
  The **Get-WssDomainNameConfiguration** cmdlet gets the domain name configuration of the Windows Server Essentials computer.
  This cmdlet returns Windows Server Essentials domain configuration settings, the name of the domain provider, the certificate status, and the expiration date of the certificate.
metadata:
  external help file: WssCmdlets.dll-Help.xml
  Module Name: WSSCmdlets
  ms.date: 12/05/2017
  online version: https://docs.microsoft.com/powershell/module/wsscmdlets/get-wssdomainnameconfiguration?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-WssDomainNameConfiguration
