### YamlMime:PowershellCmdlet
summary: |-
  Creates a file specification that specifies the files and folders to include in or exclude from a backup.
module: WSSCmdlets
notes: ""
outputs:
- name: <xref href="Microsoft.WindowsServerSolutions.DataProtection.ServerBackup.ObjectModel.BackupFileSpec" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet generates the object that specifies whether files or folders are included or excluded in the server backup.
links:
- text: Add-WssBackupConfiguration
  href: ./Add-WssBackupConfiguration.yml
- text: Get-WssBackupConfiguration
  href: ./Get-WssBackupConfiguration.yml
- text: Remove-WssBackupConfiguration
  href: ./Remove-WssBackupConfiguration.yml
syntaxes:
- >-
  New-WssBackupConfiguration [-FilePath] <String> [-FileName] <String> [-IsDirectory] [-IsExcludeSpec]

   [<CommonParameters>]
examples:
- title: 'Example 1: Create a backup file specification'
  code: |-
    PS C:\> $Spec = New-WssBackupConfiguration -FilePath "c:\users\" -FileName * -IsDirectory -IsExcludeSpec
  description: |-
    This command creates a backup file specification that excludes folders in the c:\users path from the backup.
    It then stores the backup specification in the variable named $Spec.
  summary: ""
parameters:
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FileName
  isRequired: true
  description: |+
    Specifies the name of a file to back up.
    Use * for this parameter to back up all files in the path that the **FilePath** parameter specifies.

  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: FilePath
  isRequired: true
  description: |+
    Specifies the path that contains the files to back up.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: IsDirectory
  description: |+
    Indicates that the file specification refers to a folder.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: IsExcludeSpec
  description: |+
    Indicates that the cmdlet excludes the files in the specification from the backup

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: WSSCmdlets.New-WssBackupConfiguration
name: New-WssBackupConfiguration
description: |-
  The **New-WssBackupConfiguration** cmdlet creates a file specification for a backup of a volume.
  The file specification lists the files and folders to include in or exclude from the backup.
metadata:
  external help file: WssCmdlets.dll-Help.xml
  Module Name: WSSCmdlets
  ms.date: 12/05/2017
  online version: https://docs.microsoft.com/powershell/module/wsscmdlets/new-wssbackupconfiguration?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: New-WssBackupConfiguration
