### YamlMime:PowershellCmdlet
summary: |-
  Removes a file specification from a backup volume.
module: WSSCmdlets
notes: ""
inputs:
- name: <xref href="Microsoft.WindowsServerSolutions.DataProtection.ServerBackup.ObjectModel.BackupVolume" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.WindowsServerSolutions.DataProtection.ServerBackup.ObjectModel.BackupFileSpec" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet generates an object that indicates whether to include or exclude files or folders in the server backup.
links:
- text: Add-WssBackupConfiguration
  href: ./Add-WssBackupConfiguration.yml
- text: Get-WssBackupConfiguration
  href: ./Get-WssBackupConfiguration.yml
- text: New-WssBackupConfiguration
  href: ./New-WssBackupConfiguration.yml
syntaxes:
- Remove-WssBackupConfiguration [-Volume] <BackupVolume> [-Configuration] <BackupFileSpec> [<CommonParameters>]
examples:
- title: 'Example 1: Remove a file specification from a backup volume'
  code: |-
    PS C:\>$ContosoBUVolume110 = Get-WssBackupVolume -AllVolumes
    PS C:\> $ContosoBUFilespec05 = Get-WssBackupConfiguration -Volume $ContosoBUVolume110[0]
    PS C:\> Remove-WssBackupConfiguration -Configuration $ContosoBUFilespec05[1]
  description: |-
    This command removes the backup file specification from a backup volume.

    The first command gets the backup volumes from the server and stores them in the **$ContosoBUVolume110** variable.

    The second command gets the backup file specification from the first item (located in position 0) in **$ContosoBUVolume110** and stores the backup file specification in the **$ContosoBUFilespec05** variable.

    The third command removes the backup file specification from the second item (located in position 1) in **$ContosoBUFilespec05**.
  summary: ""
parameters:
- type: <xref href="BackupFileSpec" data-throw-if-not-resolved="False" />
  name: Configuration
  isRequired: true
  description: |+
    Specifies the backup file specification to remove from the volume.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: Config
  parameterValueGroup: ""
- type: <xref href="BackupVolume" data-throw-if-not-resolved="False" />
  name: Volume
  isRequired: true
  description: |+
    Specifies the volume from which to remove the file specification.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: WSSCmdlets.Remove-WssBackupConfiguration
name: Remove-WssBackupConfiguration
description: |-
  The **Remove-WssBackupConfiguration** cmdlet removes a file specification from a backup volume.
  When you remove a file specification from a backup volume, the files and folders in the file specification are no longer backed up with the backup volume.
metadata:
  external help file: WssCmdlets.dll-Help.xml
  Module Name: WSSCmdlets
  ms.date: 12/05/2017
  online version: https://docs.microsoft.com/powershell/module/wsscmdlets/remove-wssbackupconfiguration?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Remove-WssBackupConfiguration
