### YamlMime:PowershellCmdlet
summary: |-
  Repairs the router configuration.
module: WSSCmdlets
notes: ""
syntaxes:
- Repair-WssRouterConfiguration [<CommonParameters>]
examples:
- title: 'Example 1: Repair the router configuration'
  code: |-
    PS C:\> Repair-WssRouterConfiguration
  description: |-
    This command repairs the router configuration.
  summary: ""
uid: WSSCmdlets.Repair-WssRouterConfiguration
name: Repair-WssRouterConfiguration
description: |-
  The **Repair-WssRouterConfiguration** cmdlet repairs the router configuration for a sbs_sbs8_2 installation.
  This cmdlet also sets port forwarding for the router.
metadata:
  external help file: WssCmdlets.dll-Help.xml
  Module Name: WSSCmdlets
  ms.date: 12/05/2017
  online version: https://docs.microsoft.com/powershell/module/wsscmdlets/repair-wssrouterconfiguration?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Repair-WssRouterConfiguration
