### YamlMime:PowershellCmdlet
summary: |-
  Resets the DNS64 configuration on a computer.
module: NetworkTransition
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root\StandardCimv2\MSFT_NetDnsTransitionConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The `Microsoft.Management.Infrastructure.CimInstance` object is a wrapper class that displays Windows Management Instrumentation (WMI) objects.
    The path after the pound sign (`#`) provides the namespace and class name for the underlying WMI object.
links:
- text: Disable-NetDnsTransitionConfiguration
  href: ./Disable-NetDnsTransitionConfiguration.yml
- text: Enable-NetDnsTransitionConfiguration
  href: ./Enable-NetDnsTransitionConfiguration.yml
- text: Get-NetDnsTransitionConfiguration
  href: ./Get-NetDnsTransitionConfiguration.yml
- text: Get-NetDnsTransitionMonitoring
  href: ./Get-NetDnsTransitionMonitoring.yml
- text: Set-NetDnsTransitionConfiguration
  href: ./Set-NetDnsTransitionConfiguration.yml
syntaxes:
- >-
  Reset-NetDnsTransitionConfiguration [-Adapter <CimInstance>] [-State] [-OnlySendAQuery] [-LatencyMilliseconds]

   [-AlwaysSynthesize] [-AcceptInterface] [-SendInterface] [-ExclusionList] [-PrefixMapping] [-PassThru]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Reset-NetDnsTransitionConfiguration -InputObject <CimInstance[]> [-State] [-OnlySendAQuery]

   [-LatencyMilliseconds] [-AlwaysSynthesize] [-AcceptInterface] [-SendInterface] [-ExclusionList]

   [-PrefixMapping] [-PassThru] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf]

   [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Reset the DNS64 configuration'
  code: |-
    PS C:\>Reset-NetDnsTransitionConfiguration -State -LatencyMilliseconds
  description: |-
    This command resets the state and latency of the DNS64 configuration.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AcceptInterface
  description: |+
    Resets the interface on which the DNS64 is listening to all interfaces classified in the Domain profile.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" />
  name: Adapter
  description: |+
    Specifies the network adapter on which to apply the reset.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AlwaysSynthesize
  description: |+
    Specifies that the DNS64 will always synthesize responses by sending both the AAAA response and well as the synthesized A response, when set to $False.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: ExclusionList
  description: |+
    Resets to the list of IPv6 address ranges to be excluded from synthesis by the DNS64 to `::ffff:0:0/96`.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the input object that is used in a pipeline command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: LatencyMilliseconds
  description: |+
    Resets to the default value of 300 ms for the delay between the AAAA and A query that the DNS64 sends.

  defaultValue: None
  position: Named
  aliases: Latency
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: OnlySendAQuery
  description: |+
    Specifies that both A and AAAA queries will be sent, when set to $False.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PrefixMapping
  description: |+
    Resets to the list of IPv6 address ranges to be excluded from synthesis by the DNS64 to `64:FF9B::/96`, `0.0.0.0/0`.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: SendInterface
  description: |+
    Resets the interface on which the DNS64 sends DNS queries to all interface classified in the Domain profile.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: State
  description: |+
    Resets the state of the DNS64 configuration to disabled.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: NetworkTransition.Reset-NetDnsTransitionConfiguration
name: Reset-NetDnsTransitionConfiguration
description: |-
  The **Reset-NetDnsTransitionConfiguration** resets the settings for the DNS64 configuration with the default settings.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: MSFT_NetDnsTransitionConfiguration.cdxml-help.xml
  Module Name: NetworkTransition
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/networktransition/reset-netdnstransitionconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Reset-NetDnsTransitionConfiguration
