### YamlMime:PowershellCmdlet
summary: |-
  Sets an ISATAP configuration on a computer or on a Group Policy Object (GPO).
module: NetworkTransition
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet accepts no input objects.
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root\StandardCimv2\MSFT_NetISATAPConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The `Microsoft.Management.Infrastructure.CimInstance` object is a wrapper class that displays Windows Management Instrumentation (WMI) objects.
    The path after the pound sign (`#`) provides the namespace and class name for the underlying WMI object.

    When the *Passthru* parameter is specified, this cmdlet outputs a modified ISATAP configuration object.
links:
- text: Get-NetIsatapConfiguration
  href: ./Get-NetIsatapConfiguration.yml
- text: Set-NetIsatapConfiguration
  href: ./Set-NetIsatapConfiguration.yml
syntaxes:
- >-
  Set-NetIsatapConfiguration [-IPInterface <CimInstance>] [-PolicyStore <String>] [-GPOSession <String>]

   [[-State] <State>] [[-Router] <String>] [[-ResolutionState] <State>] [[-ResolutionIntervalSeconds] <UInt32>]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-PassThru] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Set-NetIsatapConfiguration -InputObject <CimInstance[]> [[-State] <State>] [[-Router] <String>]

   [[-ResolutionState] <State>] [[-ResolutionIntervalSeconds] <UInt32>] [-CimSession <CimSession[]>]

   [-ThrottleLimit <Int32>] [-AsJob] [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Set ISATAP configuration'
  code: |-
    PS C:\>Set-NetIsatapConfiguration -Router superisatap
  description: |-
    This command modifies the router name.
  summary: ""
- title: 'Example 2: Set a router using an input object'
  code: |-
    PS C:\>$config = ( Get-NetIPInterface -InterfaceIndex 14 | Get-NetIPISATAPConfiguration )
    PS C:\> $config.Router = "SuperIsatap"
    PS C:\> Set-NetIsatapConfiguration -InputObject $config
  description: |-
    This set of commands uses the Get-NetIPInterface and Get-NetIsatapConfiguration cmdlets to get the ISATAP configuration of the interface at index 14 and stores it in a variable named $config, and then sets the router name to SuperIsatap using this cmdlet.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GPOSession
  description: |+
    Specifies the Group Policy session to which to store the configuration information.

    You can use this with the **NetGPO** cmdlets to aggregate multiple operations performed on a GPO.

    You cannot use this parameter with the *PolicyStore* parameter.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the input object that is used in a pipeline command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" />
  name: IPInterface
  description: |+
    Specifies the IP interface on which to set the ISATAP configuration.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PolicyStore
  description: |+
    Specifies the policy store that contains the configuration to set.
    The acceptable values for this parameter are:

    - PersistentStore 
    - ActiveStore 
    - GPO

    To set the configuration of a GPO, specify the GPO name using the following format: Domain\GPOName

    You cannot use this parameter with the *GPOSession* parameter.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="UInt32" data-throw-if-not-resolved="False" />
  name: ResolutionIntervalSeconds
  description: |+
    Specifies how often in seconds that Windows Server® 2012 attempts to contact the specified ISATAP server.

  defaultValue: None
  position: "4"
  aliases: ResolutionInterval
  parameterValueGroup: ""
- type: <xref href="State" data-throw-if-not-resolved="False" />
  name: ResolutionState
  description: |+
    Specifies the state of router name resolution.
    The state of the router name resolution specifies how often Windows Server 2012 resolves the ISATAP router name.

  defaultValue: None
  position: "3"
  aliases: ""
  parameterValueGroup: Default, Automatic, Enabled, Disabled
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Router
  description: "Specifies the policy setting that allows you to specify a router name or IPv4 address for an ISATAP router. \r\n                         \r\nIf you enable this policy setting, then you can specify a router name or IPv4 address for an ISATAP router.\r\nIf you enter an IPv4 address of the ISATAP router, then DNS services are not required.\r\n\r\n"
  defaultValue: None
  position: "2"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="State" data-throw-if-not-resolved="False" />
  name: State
  description: "Specifies the policy setting that allows you to configure ISATAP, an address-to-router and host-to-host, host-to-router and router-to-host automatic tunneling technology that provides unicast IPv6 connectivity between IPv6 hosts across an IPv4 intranet.\r\nYou can specify one of the following three policy setting states: \r\n\r\n- Default.\r\nIf the ISATAP router name is resolved successfully, then ISATAP is configured with a link-local address and an address for each prefix received from the ISATAP router through stateless address auto-configuration. \r\n                         \r\n ---- If the ISATAP router name is not resolved successfully, then ISATAP connectivity is not available on the host using the corresponding IPv4 address. \r\n                         \r\n -- Enabled. \r\n                         \r\n ---- If the ISATAP name is resolved successfully, then ISATAP is configured with a link-local address and an address for each prefix received from the ISATAP router through stateless address auto-configuration. \r\n                         \r\n ---- If the ISATAP name is not resolved successfully, then the ISATAP interface is configured with a link-local address. \r\n                         \r\n -- Disabled.\r\nNo ISATAP interfaces are present on the host.\r\n\r\n"
  defaultValue: None
  position: "1"
  aliases: ""
  parameterValueGroup: Default, Automatic, Enabled, Disabled
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: NetworkTransition.Set-NetIsatapConfiguration
name: Set-NetIsatapConfiguration
description: |-
  The **Set-NetIsatapConfiguration** cmdlet sets an ISATAP configuration on a computer or on a Group Policy Object (GPO).
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: MSFT_NetISATAPConfiguration.cdxml-help.xml
  Module Name: NetworkTransition
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/networktransition/set-netisatapconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-NetIsatapConfiguration
