### YamlMime:PowershellCmdlet
summary: |-
  Modifies an IP-HTTPS configuration.
module: NetworkTransition
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet accepts no input objects.
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#root\StandardCimv2\MSFT_NetIpHTTPsConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    The `Microsoft.Management.Infrastructure.CimInstance` object is a wrapper class that displays Windows Management Instrumentation (WMI) objects.
    The path after the pound sign (`#`) provides the namespace and class name for the underlying WMI object.

    When the *Passthru* parameter is specified, this cmdlet outputs a modified IP-HTTPS configuration object.
links:
- text: Get-NetIPHttpsConfiguration
  href: ./Get-NetIPHttpsConfiguration.yml
- text: New-NetIPHttpsConfiguration
  href: ./New-NetIPHttpsConfiguration.yml
- text: Rename-NetIPHttpsConfiguration
  href: ./Rename-NetIPHttpsConfiguration.yml
- text: Remove-NetIPHttpsConfiguration
  href: ./Remove-NetIPHttpsConfiguration.yml
- text: Reset-NetIPHttpsConfiguration
  href: ./Reset-NetIPHttpsConfiguration.yml
syntaxes:
- >-
  Set-NetIPHttpsConfiguration [-Profile <String[]>] [-ProfileActivated <Boolean[]>] [-PolicyStore <String>]

   [-State <State>] [-Type <Type>] [-AuthMode <AuthMode>] [-StrongCRLRequired <Boolean>] [-ServerURL <String>]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-PassThru] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Set-NetIPHttpsConfiguration [-Profile <String[]>] [-ProfileActivated <Boolean[]>] [-GPOSession <String>]

   [-State <State>] [-Type <Type>] [-AuthMode <AuthMode>] [-StrongCRLRequired <Boolean>] [-ServerURL <String>]

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-PassThru] [-WhatIf] [-Confirm]

   [<CommonParameters>]
- >-
  Set-NetIPHttpsConfiguration -InputObject <CimInstance[]> [-State <State>] [-Type <Type>] [-AuthMode <AuthMode>]

   [-StrongCRLRequired <Boolean>] [-ServerURL <String>] [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>]

   [-AsJob] [-PassThru] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Set the server URL of the profile'
  code: |-
    PS C:\>Set-NetIPHttpsConfiguration -Profile "Redmond" -ServerURL "https://da.com:443/IPHTTPs" -PolicyStore "Domain\TestGPO"
  description: |-
    This command modifies the profile named Redmond in the GPO named TestGPO, modifying the server URL.
  summary: ""
- title: 'Example 2: Set the server URL using IP-HTTPS configuration object'
  code: |-
    PS C:\>Get-NetIPHttpsConfiguration -Profile "Redmond" -PolicyStore "Domain\TestGPO" | Set-NetIPHttpsConfiguration -ServerURL "https://da.com:443/IPHTTPs"
  description: |-
    This command gets the IP-HTTPS configuration profile named Redmond in the GPO named TestGPO using the Get-NetIPHttpsConfiguration cmdlet, and then provides the output object as input to this cmdlet using the pipeline operator.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="AuthMode" data-throw-if-not-resolved="False" />
  name: AuthMode
  description: |+
    Specifies the authentication mode.
    The acceptable values for this parameter are:

    - None.
    Performs no client authentication during the SSL handshake.
    This is the default value. 
    - Certificates.
    Uses client certificates to authenticate clients.
    This authentication mode applies only to a server interface on a computer running Windows Server® 2012 or Windows Server 2016.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: None, Certificates
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GPOSession
  description: |+
    Specifies the Group Policy session to which to store the configuration information.

    You can use this parameter with the **NetGPO** cmdlets to aggregate multiple operations performed on a Group Policy Object (GPO).

    You cannot use this parameter with the *PolicyStore* parameter.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: InputObject
  isRequired: true
  description: |+
    Specifies the input object that is used in a pipeline command.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PolicyStore
  description: |+
    Specifies the policy store that contains the IP-HTTPS configuration profile to set.
    The acceptable values for this parameter are:

    - ActiveStore 
    - PersistentStore 
    - GPO

    To set the configuration profile of a GPO, specify the GPO name using the following format: Domain\GPOName

    You cannot use this parameter with the *GPOSession* parameter.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Profile
  description: |+
    Specifies the name of the profile to modify.
    This parameter is only allowed when the store is a GPO.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: IPHttpsProfile
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ProfileActivated
  description: |+
    Filters the objects to modify.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ServerURL
  description: |+
    Specifies the URL for the server.
    If the profile is a client profile, Windows attempts to connect to the server URL.
    If the profile is a server profile, then this is the URL to which the server listens.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="State" data-throw-if-not-resolved="False" />
  name: State
  description: |+
    Specifies the state behavior of IP-HTTPS.
    The acceptable values for this parameter are:

    - Default. 
     ---- For a server interface, IP-HTTPS is always configured. 
    ---- For a client interface, IP-HTTPS is configured on demand based on the other connectivity options available.
    Client interfaces are created with this setting by default. 
    - Enabled.
    IP-HTTPS is always configured, for both server interfaces and client interfaces.
    Server interfaces are created with this setting by default. 
    - Disabled.
    Disables the IP-HTTPS interface. 
    - OutsideEnabled.
    IP-HTTPs is configured on demand whenever the computer is outside of the corporate network.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Default, Enabled, Disabled, OutsideEnabled
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: StrongCRLRequired
  description: |+
    Determines if a strong certificate revocation list (CRL) check is required before connection.

    The default value is False.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Type" data-throw-if-not-resolved="False" />
  name: Type
  description: |+
    Specifies if IP-HTTPS should start in server mode or client mode.
    The parameter value set to server mode is only allowed on Windows Server 2012 or Windows Server 2016.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Client, Server
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: NetworkTransition.Set-NetIPHttpsConfiguration
name: Set-NetIPHttpsConfiguration
description: |-
  The **Set-NetIPHttpsConfiguration** cmdlet modifies an IP-HTTPS configuration.

  You can specify the IP-HTTPS configuration profile to modify either by using a configuration object retrieved by the Get-NetIPHttpsConfiguration cmdlet or by specifying the profile name.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: MSFT_NetIpHTTPsConfiguration.cdxml-help.xml
  Module Name: NetworkTransition
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/networktransition/set-netiphttpsconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-NetIPHttpsConfiguration
