### YamlMime:PowershellCmdlet
summary: |-
  Removes IPAM server configuration events.
module: IpamServer
notes: ""
outputs:
- name: <xref href="IpamConfigurationEvent" data-throw-if-not-resolved="False" />
  description: |-
    An object that represents an IPAM server configuration event.
links:
- text: Get-IpamConfigurationEvent
  href: ./Get-IpamConfigurationEvent.yml
syntaxes:
- >-
  Remove-IpamConfigurationEvent -EndDate <DateTime> [-PassThru] [-Force] [-CimSession <CimSession[]>]

   [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Remove all configuration events'
  code: |-
    PS C:\> $Today = Get-DatePS C:\>Remove-IpamConfigurationEvent -EndDate $Today
    Confirm

    All Event catalogue data upto and including the date selected by you will be deleted permanently. Do you want to

    continue?

    [Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):Y
  description: |-
    This command removes all configuration events data though today.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    ps_cimcommon_asjob

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a New-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227967 or Get-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227966 cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="DateTime" data-throw-if-not-resolved="False" />
  name: EndDate
  isRequired: true
  description: |+
    Specifies the end date as a **DateTime** object.
    The cmdlet removes configuration events through this date from the IPAM database.
    To obtain a **DateTime** object, use the **Get-Date** cmdlet.
    For more information, type `Get-Help Get-Date`.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Force
  description: |+
    Forces the command to run without asking for user confirmation.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: PassThru
  description: |+
    Returns an object representing the item with which you are working.
    By default, this cmdlet does not generate any output.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: IpamServer.Remove-IpamConfigurationEvent
name: Remove-IpamConfigurationEvent
description: |-
  The **Remove-IpamConfigurationEvent** cmdlet permanently removes IP Address Management (IPAM) server configuration events from the IPAM database.
  The cmdlet removes all the configuration events that IPAM gathered through the specified end date.

  Do not specify the current date as the end date.
  The IPAM server collects the configuration events from DHCP servers as part of the next data gathering task, and, therefore, specifying the current date does not result in permanently deleting events from the current day.
metadata:
  external help file: IpamConfigurationEvent.cdxml-help.xml
  Module Name: IpamServer
  ms.date: 10/30/2017
  online version: https://docs.microsoft.com/powershell/module/ipamserver/remove-ipamconfigurationevent?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Remove-IpamConfigurationEvent
