### YamlMime:PowershellCmdlet
summary: |-
  Gets security information about a virtual machine.
module: Hyper-V
notes: ""
outputs:
- name: <xref href="Microsoft.HyperV.PowerShell.VMSecurity" data-throw-if-not-resolved="False" />
  description: ""
syntaxes:
- >-
  Get-VMSecurity [-CimSession <CimSession[]>] [-ComputerName <String[]>] [-Credential <PSCredential[]>]

   [-VMName] <String[]> [<CommonParameters>]
- Get-VMSecurity [-VM] <VirtualMachine[]> [<CommonParameters>]
examples:
- title: 'Example 1: Get security information about a virtual machine'
  code: |-
    PS C:\> Get-VMSecurity -VMName "VM01"
  description: |-
    This command gets security information about the virtual machine named VM01.
  summary: ""
parameters:
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: ComputerName
  description: |+
    Specifies one or more Hyper-V hosts to run the cmdlet.
    NetBIOS names, IP addresses, and fully-qualified domain names are allowable.
    The default is the local computer.
    Use "localhost" or a dot (".") to specify the local computer explicitly.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="PSCredential" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: Credential
  description: |+
    Specifies a user account that has permission to perform this action.
    The default is the current user.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="VirtualMachine" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: VM
  isRequired: true
  description: |+
    Specifies one or more virtual machines for which this cmdlet gets security settings.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: VMName
  isRequired: true
  description: |+
    Specifies the name of one or more virtual machines for which this cmdlet gets security settings.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ""
  parameterValueGroup: ""
uid: Hyper-V.Get-VMSecurity
name: Get-VMSecurity
description: |-
  The **Get-VMSecurity** cmdlet gets security information about a virtual machine.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.HyperV.PowerShell.Cmdlets.dll-Help.xml
  Module Name: Hyper-V
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/hyper-v/get-vmsecurity?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-VMSecurity
