### YamlMime:PowershellCmdlet
summary: |-
  Retrieves the current configuration of the Microsoft Group Key Distribution Service (KdsSvc) from Active Directory (AD).
module: KDS
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet accepts no input objects.
outputs:
- name: <xref href="Microsoft.KeyDistributionService.KdsServerConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    A KdsServerConfiguration object contains information such as the key derivation function (KDF) algorithm and secret agreement algorithm used in key generation.
links:
- text: Add-KdsRootKey
  href: ./Add-KdsRootKey.yml
- text: Clear-KdsCache
  href: ./Clear-KdsCache.yml
- text: Get-KdsRootKey
  href: ./Get-KdsRootKey.yml
- text: Set-KdsConfiguration
  href: ./Set-KdsConfiguration.yml
- text: Test-KdsRootKey
  href: ./Test-KdsRootKey.yml
syntaxes:
- Get-KdsConfiguration [<CommonParameters>]
examples:
- title: 'Example 1: Retrieve the current KDS configuration'
  code: |-
    PS C:\>Get-KdsConfiguration
  description: |-
    This example retrieves the current configuration of the Microsoft Group KdsSvc from AD.
  summary: ""
uid: KDS.Get-KdsConfiguration
name: Get-KdsConfiguration
description: |-
  The **Get-KdsConfiguration** cmdlet retrieves the current configuration of the Microsoft Group Key Distribution Service (KdsSvc) from Active Directory (AD).
  The KDS configuration defines how keys are generated from the root keys.
metadata:
  external help file: Microsoft.KeyDistributionService.Cmdlets.dll-Help.xml
  Module Name: KDS
  online version: https://docs.microsoft.com/powershell/module/kds/get-kdsconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
