### YamlMime:PowerShellCmdlet1
uid: NetworkController.Get-NetworkControllerLoadBalancerFrontendIpConfiguration
name: Get-NetworkControllerLoadBalancerFrontendIpConfiguration
module: NetworkController
isPreview: false
parameters:
  cmdletParameters:
  - name: CertificateThumbprint
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the digital public key X.509 certificate of a user account that has permission to perform this action.This is the certificate thumbprint of the certificate.This thumbprint must also be provided in the *ClientCertificateThumbprint* parameter in the **Install-NetworkController** or **Set-NetworkController** cmdlet so that Network Controller can authorize this user.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ConnectionUri
    type: <xref href="Uri" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the Uniform Resource Identifier (URI) of the Network Controller, used by all Representational State Transfer (REST) clients to connect to Network Controller.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Credential
    type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
    description: |-
      Specifies a user credential that has permission to perform this action.The default value is the current user.This user must be present in the security group provided in the *ClientSecurityGroup* parameter in the **Install-NetworkController** cmdlet.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: LoadBalancerId
    type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Specifies the load balancer where the resource belongs
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PassInnerException
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ResourceId
    type: <xref href="String" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
    description: |-
      Specifies the unique identifier of the resource
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "1"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-NetworkControllerLoadBalancerFrontendIpConfiguration
        [-LoadBalancerId] <String[]>
        [[-ResourceId] <String[]>]
        -ConnectionUri <Uri>
        [-CertificateThumbprint <String>]
        [-Credential <PSCredential>]
        [-PassInnerException]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: |-
    Following properties can be retrieved for front end IP configuration of load balancer resource:
    1. Private IP address (VIP)
    2. Private IP address allocation method: Static or dynamic
    3. Load balancing rules associated with the resource
    4. Inbound NAT rules associated with the resource
    5. Outbound NAT rules associated with the resource
    6. Subnet associated with the resource
    7. Access control list associated with the resource
    8. Service insertion rules associated with the resource
examples:
- title: Example 1
  description: |-
    This example retrieves all the front end IP resource associated with a load balancer resource named lb1

    ```
    Get-NetworkControllerLoadBalancerFrontEndIpconfiguration -ConnectionUri https://networkcontroller -LoadBalancerId lb1
    ```
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  document type: cmdlet
  external help file: Microsoft.NetworkController.Powershell.dll-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/networkcontroller/get-networkcontrollerloadbalancerfrontendipconfiguration?view=windowsserver2025-ps&wt.mc_id=ps-gethelp
  Module Name: NetworkController
  ms.date: 12/20/2016
  PlatyPS schema version: 2024-05-01
  title: Get-NetworkControllerLoadBalancerFrontendIpConfiguration
