### YamlMime:PowershellCmdlet
summary: |-
  Returns the configuration for the DirectAccess client user experience.
module: DirectAccessClientComponents
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance Microsoft.Management.Infrastructure.CimInstance#root/StandardCimv2/MSFT_DAClientExperienceConfiguration" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet returns a CIM object that contains the DA client experience configuration.
links:
- text: Reset-DAClientExperienceConfiguration
  href: ./Reset-DAClientExperienceConfiguration.yml
- text: Set-DAClientExperienceConfiguration
  href: ./Set-DAClientExperienceConfiguration.yml
syntaxes:
- >-
  Get-DAClientExperienceConfiguration [-PolicyStore <String>] [-GPOSession <String>] [-CimSession <CimSession[]>]

   [-ThrottleLimit <Int32>] [-AsJob] [<CommonParameters>]
examples:
- title: 'Example: Retrieve the DirectAccess client experience configuration from the active store'
  code: |-
    PS C:\> Get-DAClientExperienceConfiguration -PolicyStore ActiveStore
  description: |-
    This cmdlet retrieves the DirectAccess client experience configuration from the active policy store.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    ps_cimcommon_asjob

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a New-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227967 or Get-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227966 cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: GPOSession
  description: |+
    Specifies the Group Policy session from which to read client experience configuration information.
    You can use **GPOSession** with the **NetGPO** cmdlets to aggregate multiple operations performed on a Group Policy Object.

    **GPOSession** cannot be used in conjunction with **PolicyStore**.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PolicyStore
  description: |+
    Specifies the policy store from which the cmdlet reads the client experience configuration information.

    To read the client experience configuration information from a Group Policy Object, specify the GPO name using the following format: "Domain\GPOName"

    To read the client experience configuration information from a computer's local GPO, specify the computer's local GPO name in the following format: "GPO:\<computername\>"

    **PolicyStore** cannot be used in conjunction with **GPOSession**.

    The default value for **PolicyStore** is ActiveStore.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
uid: DirectAccessClientComponents.Get-DAClientExperienceConfiguration
name: Get-DAClientExperienceConfiguration
description: |-
  **Get-DAClientExperienceConfiguration** returns the configuration for the DirectAccess client user experience.
  The configuration returned controls the user interface behavior, as well as what configuration options are available to the user.

  All **DAClientExperienceConfiguration** cmdlets have an ADMX file that can also be used to configure the client experience settings.
metadata:
  external help file: MSFT_DAClientExperienceConfiguration.cdxml-help.xml
  Module Name: DirectAccessClientComponents
  ms.date: 10/29/2017
  online version: https://docs.microsoft.com/powershell/module/directaccessclientcomponents/get-daclientexperienceconfiguration?view=windowsserver2012r2-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Get-DAClientExperienceConfiguration
