### YamlMime:PowershellCmdlet
summary: |-
  Imports the uev_tla configuration.
module: UEV
notes: ""
links:
- text: Get-UevConfiguration
  href: ./Get-UevConfiguration.yml
- text: Set-UevConfiguration
  href: ./Set-UevConfiguration.yml
- text: Clear-UevConfiguration
  href: ./Clear-UevConfiguration.yml
- text: Export-UevConfiguration
  href: ./Export-UevConfiguration.yml
syntaxes:
- Import-UevConfiguration [-Path] <String> [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Import the UE-V configuration'
  code: |-
    PS C:\> Import-UevConfiguration -Path "ContosoUev.uev"
  description: |-
    This command imports the uev_tla computer configuration from the settings migration file named ContosoUev.uev.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: Path
  isRequired: true
  description: |+
    Specifies the path of the settings migration file.
    The cmdlet imports the uev_tla configuration from the settings migration file (.uev file) that you specify.

  defaultValue: None
  position: "0"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: UEV.Import-UevConfiguration
name: Import-UevConfiguration
description: |-
  The **Import-UevConfiguration** cmdlet imports the uev_1 computer configuration from a settings migration (.uev) file.
  You must have administrative credentials to run this cmdlet.
metadata:
  description: Use this topic to help manage MDOP technologies with Windows PowerShell.
  external help file: Microsoft.Uev.Commands.dll-Help.xml
  ms.date: 12/05/2016
  ms.devlang: powershell
  schema: 2.0.0
  title: Import-UevConfiguration
