### YamlMime:PowershellCmdlet
summary: |-
  Gets useful network information including usable interfaces, IP addresses and DNS servers.
module: NetTCPIP
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-DNSClientServerAddress
  href: ../dnsclient/Get-DnsClientServerAddress.yml
- text: Get-NetAdapter
  href: ../netadapter/Get-NetAdapter.yml
- text: Get-NetIPAddress
  href: ./Get-NetIPAddress.yml
- text: Get-NetIPInterface
  href: ./Get-NetIPInterface.yml
- text: Get-NetRoute
  href: ./Get-NetRoute.yml
syntaxes:
- Get-NetIPConfiguration [[-InterfaceAlias] <String>]
- Get-NetIPConfiguration [-All]
- Get-NetIPConfiguration [-CimSession <CimSession>] [-Detailed]
- Get-NetIPConfiguration [-InterfaceIndex] <Int32>
examples:
- title: EXAMPLE 1
  code: |-
    PS C:\>Get-NetIPConfiguration
  description: |-
    This example gets IP configuration information.
    When this cmdlet is run without parameters, it gets the IP configuration information for all of the non-virtual connected interfaces on the computer.
  summary: ""
- title: EXAMPLE 2
  code: |-
    PS C:\>GIP
  description: |-
    This example uses the alias for this cmdlet.
    `GIP` gets IP configuration information.
    When this cmdlet is run without parameters, it gets the IP configuration information for all of the non-virtual connected interfaces on the computer.
  summary: ""
- title: EXAMPLE 3
  code: |-
    PS C:\>Get-NetIPConfiguration -All
  description: |-
    This example gets the IP configuration information for all of the interfaces on the computer, including virtual interfaces, loopback interfaces, and disconnected interfaces.
  summary: ""
- title: EXAMPLE 4
  code: |-
    PS C:\>Get-NetIPConfiguration -Verbose
  description: |-
    This example gets IP configuration information.
    By using the **Verbose** parameter, the networking cmdlets are shown to gather and format the information displayed in this cmdlet.
    More information about how to use cmdlets in Windows PowerShell® can be learned by reading the output of this cmdlet with the **Verbose** parameter.
  summary: ""
- title: EXAMPLE 5
  code: |-
    PS C:\>Get-NetIPConfiguration -InterfaceIndex 12
  description: |-
    This example gets the IP configuration information for the interface at the index 12.
  summary: ""
- title: EXAMPLE 6
  code: |-
    PS C:\>Get-NetIPConfiguration | Get-NetIPAddress
  description: |-
    This example gets the IP address information, including PrefixLength, for the interfaces determined by this cmdlet.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: All
  description: |+
    Indicates that the IP configuration properties for all of the interfaces on a computer are retrieved, including virtual interfaces, loopback interfaces, as well as disconnected interfaces.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" />
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a New-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227967 or Get-CimSessionhttp://go.microsoft.com/fwlink/p/?LinkId=227966 cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Detailed
  description: |+
    Indicates that additional interface and computer configuration information are retrieved, including computer name, link layer address, network profile, MTU length, and DHCP status.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: InterfaceAlias
  description: |+
    Specifies the alias of the interface for which to get the IP configuration properties.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: InterfaceIndex
  isRequired: true
  description: |+
    Specifies the index of the interface for which to get the IP configuration properties.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
uid: NetTCPIP.Get-NetIPConfiguration
name: Get-NetIPConfiguration
description: |-
  The **Get-NetIPConfiguration** cmdlet gets useful network information including usable interfaces, IP addresses and DNS servers.
  Additional parameters show if the computer is connected to the Internet (Network Profile information), link layer address information and if DHCP is enabled.

  If no parameters are specified, then this cmdlet gets IP configuration properties for all non-virtual connected interfaces on a computer.

  This cmdlet does not get the prefix length, which is also known as the subnet mask.
  The prefix length is an addressing detail retrieved by the Get-NetIPAddress cmdlet.
  See the Get-NetIPAddress cmdlet for more information about retrieving the prefix length.
metadata:
  external help file: NetTCPIP_Cmdlets.xml
  Module Name: NetTCPIP
  online version: https://docs.microsoft.com/powershell/module/nettcpip/get-netipconfiguration?view=windowsserver2012-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
