### YamlMime:PowershellCmdlet
summary: |-
  Clears an IIS configuration collection.
module: IISAdministration
notes: ""
inputs:
- name: <xref href="Microsoft.Web.Administration.ConfigurationElementCollection" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-IISConfigCollection
  href: ./Get-IISConfigCollection.yml
- text: IIS Administration Cmdlets for Windows PowerShell
  href: ./index.yml
syntaxes:
- >-
  Clear-IISConfigCollection [-ConfigCollection] <ConfigurationElementCollection> [-WhatIf] [-Confirm]

   [<CommonParameters>]
examples:
- title: 'Example 1: Clear the defaultDocument settings for Default Web Site, which inherits from Server level and defined in applicationHost.config.'
  code: |-
    PS C:\> Get-IISConfigSection -SectionPath "system.webServer/defaultDocument" -CommitPath "Default Web Site" | Get-IISConfigCollection -CollectionName "files" | Clear-IISConfigCollection -Confirm:$False
  description: |-
    This command adds lines in web.config which is the configuration file of Default Web Site.
  summary: ""
parameters:
- type: <xref href="ConfigurationElementCollection" data-throw-if-not-resolved="False" />
  name: ConfigCollection
  isRequired: true
  description: |+
    Specifies the **ConfigurationCollection** object for which the collection elements will be cleared.
    If a **ConfigurationCollection** is previously obtained and assigned to a variable, you cannot pass it to this cmdlet through the pipeline because the pipeline engine will try to enumerate, passing **ConfigurationElement** objects instead.
    Try either passing the whole **Get-IISConfigCollection** cmdlet into the pipeline or use it as a parameter for correct results.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: IISAdministration.Clear-IISConfigCollection
name: Clear-IISConfigCollection
description: |-
  The **Clear-IISConfigCollection** cmdlet clears a given Internet Information Services (IIS) collection by removing all the elements and putting a clear tag, which is generally \<clear\>.
  This prevents from the collection to inherit collection elements from higher levels, if any.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IIS.Powershell.Commands.dll-Help.xml
  Module Name: IISAdministration
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/iisadministration/clear-iisconfigcollection?view=windowsserver2016-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Clear-IISConfigCollection
