### YamlMime:PowershellCmdlet
summary: |-
  Removes a specified configuration element.
module: IISAdministration
notes: ""
inputs:
- name: <xref href="Microsoft.Web.Administration.ConfigurationElement" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-IISConfigElement
  href: ./Get-IISConfigElement.yml
- text: Remove-IISConfigCollectionElement
  href: ./Remove-IISConfigCollectionElement.yml
- text: IIS Administration Cmdlets for Windows PowerShell
  href: ./index.yml
syntaxes:
- Remove-IISConfigElement [-ConfigElement] <ConfigurationElement> [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Remove a configuration element from an IIS website'
  code: |-
    PS C:\> Get-IISConfigSection "system.webServer/defaultDocument" -CommitPath "Default Web Site" | Remove-IISConfigElement
  description: |-
    This command removes a configuration section from a web configuration contained in IIS website Default Web Site.
  summary: ""
parameters:
- type: <xref href="ConfigurationElement" data-throw-if-not-resolved="False" />
  name: ConfigElement
  isRequired: true
  description: |+
    Specifies the Internet Information Services (IIS) ConfigurationSection or ConfigurationElement to be deleted.

  defaultValue: None
  pipelineInput: true
  position: "1"
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: IISAdministration.Remove-IISConfigElement
name: Remove-IISConfigElement
description: |-
  The **Remove-IISConfigElement** cmdlet deletes a specified configuration element.
  This affectively causes that configuration element to inherit from the parents, if any, or use the default value as described in the schema.
  If the configuration element that is being removed is a collection element, it is removed from the collection, in which case the functionality is equivalent to Remove-IISConfigCollectionElement.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: Microsoft.IIS.Powershell.Commands.dll-Help.xml
  Module Name: IISAdministration
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/iisadministration/remove-iisconfigelement?view=windowsserver2016-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Remove-IISConfigElement
