### YamlMime:PowerShellCmdlet1
uid: RemoteDesktop.Get-RDDeploymentGatewayConfiguration
name: Get-RDDeploymentGatewayConfiguration
module: RemoteDesktop
isPreview: false
summary: |-
  Gets configuration settings for the RD Gateway for a Remote Desktop deployment.
description: |-
  The **Get-RDDeploymentGatewayConfiguration** cmdlet gets configuration settings for the Remote Desktop Gateway (RD Gateway) for a Remote Desktop deployment.
parameters:
  cmdletParameters:
  - name: ConnectionBroker
    type: <xref href="String" data-throw-if-not-resolved="False" />
    description: |-
      Specifies the Remote Desktop Connection Broker (RD Connection Broker) server for this Remote Desktop deployment.
      If this parameter does not appear, the default value is the fully qualified domain name (FQDN) of the local host.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-RDDeploymentGatewayConfiguration
        [[-ConnectionBroker] <String>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: |-
    Gatewaymode (String) - One of these values: Automatic, DoNotUse or Custom.

    LogonMethod (String) - One of these values: Password, Smartcard or AllowUserToSelectRuntime.

    GatewayExternalFQDN - External FQDN of the RD Gateway server specified for the deployment.
examples:
- title: 'Example 1: Get configuration settings for the RD Gateway'
  description: |-
    ```
    PS C:\> Get-RDDeploymentGatewayConfiguration -ConnectionBroker "rdcb.contoso.com"
    ```

    This command retrieves the configuration settings of the RD Gateway server associated with the RD Connection Broker server named rdcb.contoso.com.
links:
- text: Set-RDDeploymentGatewayConfiguration
  href: ./Set-RDDeploymentGatewayConfiguration.yml
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  document type: cmdlet
  external help file: RemoteDesktop.psm1-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/RemoteDesktop/get-rddeploymentgatewayconfiguration?view=windowsserver2025-ps&wt.mc_id=ps-gethelp
  Module Name: RemoteDesktop
  ms.date: 12/20/2016
  PlatyPS schema version: 2024-05-01
  title: Get-RDDeploymentGatewayConfiguration
