### YamlMime:PowerShellCmdlet1
uid: NetworkController.Get-NetworkControllerVirtualNetworkConfiguration
name: Get-NetworkControllerVirtualNetworkConfiguration
module: NetworkController
isPreview: false
parameters:
  cmdletParameters:
  - name: CertificateThumbprint
    type: <xref href="String" data-throw-if-not-resolved="False" />
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: ConnectionUri
    type: <xref href="Uri" data-throw-if-not-resolved="False" />
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Credential
    type: <xref href="PSCredential" data-throw-if-not-resolved="False" />
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: PassInnerException
    type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
    description: |-
      This thumbprint must also be provided in the **ClientCertificateThumbprint** parameter in the **Install-NetworkController** or **Set-NetworkController** cmdlet so that Network Controller can authorize this user.

      The thumbprint must be provided only if the network controller client authentication is X509 certificates.
      **Get-NetworkController** retrieves that client authentication and authorization information.
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: Named
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  document type: cmdlet
  external help file: Microsoft.NetworkController.Powershell.dll-help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/networkcontroller/get-networkcontrollervirtualnetworkconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  Module Name: NetworkController
  ms.date: 12/20/2016
  PlatyPS schema version: 2024-05-01
  title: Get-NetworkControllerVirtualNetworkConfiguration
