### YamlMime:PowerShellCmdlet1
uid: OsConfiguration.Get-OsConfigurationProperty
name: Get-OsConfigurationProperty
module: OsConfiguration
isPreview: false
summary: |-
  {{ Fill in the Synopsis }}
description: |-
  {{ Fill in the Description }}
parameters:
  cmdletParameters:
  - name: FriendlyName
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      {{ Fill FriendlyName Description }}
    aliases:
    - FNAME
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "2"
      isRequired: false
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: Name
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      {{ Fill Name Description }}
    acceptedValues:
    - DriftControl
    - RefreshPeriod
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "0"
      isRequired: true
      valueFromPipeline: false
      valueFromPipelineByPropertyName: false
      valueFromRemainingArguments: false
    supportsWildcards: false
  - name: SourceId
    type: <xref href="System.String" data-throw-if-not-resolved="False" />
    description: |-
      {{ Fill SourceId Description }}
    aliases:
    - SID
    defaultValue: None
    dontShow: false
    isDynamic: false
    parameterSets:
    - name: (All)
      position: "1"
      isRequired: false
      valueFromPipeline: true
      valueFromPipelineByPropertyName: true
      valueFromRemainingArguments: false
    supportsWildcards: false
  commonParameters: |-
    This cmdlet supports the common parameters: -Debug, -ErrorAction, -ErrorVariable,
    -InformationAction, -InformationVariable, -OutBuffer, -OutVariable, -PipelineVariable,
    -ProgressAction, -Verbose, -WarningAction, and -WarningVariable. For more information, see
    [about_CommonParameters](https://go.microsoft.com/fwlink/?LinkID=113216).
syntaxes:
- syntax: |-
    ```Syntax
    Get-OsConfigurationProperty
        [-Name] <String>
        [[-SourceId] <String>]
        [[-FriendlyName] <String>]
        [<CommonParameters>]
    ```
  parameterSetName: Default
  isDefault: true
inputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
outputs:
- name: <xref href="System.String" data-throw-if-not-resolved="False" />
examples:
- title: Example 1
  description: |-
    ```powershell
    PS C:\> {{ Add example code here }}
    ```

    {{ Add example description here }}
metadata:
  document type: cmdlet
  external help file: Microsoft.Management.OsConfiguration.Commands.dll-Help.xml
  HelpUri: https://learn.microsoft.com/powershell/module/osconfiguration/get-osconfigurationproperty?view=windowsserver2025-ps&wt.mc_id=ps-gethelp
  Module Name: OsConfiguration
  ms.date: 02/21/2024
  PlatyPS schema version: 2024-05-01
  title: Get-OsConfigurationProperty
