name: (Scheduled) Stale branch removal

permissions:
  contents: write
      
on:
  schedule:
    - cron: "0 9 1 * *"

  # workflow_dispatch:
  

jobs:

  stale-branch:
    if: github.repository_owner == 'MicrosoftDocs'
    uses: MicrosoftDocs/microsoft-365-docs/.github/workflows/Shared-StaleBranch.yml@workflows-prod
    with:
        PayloadJson: ${{ toJSON(github) }}
        RepoBranchSkipList: '[
                              "ExampleBranch1",
                              "ExampleBranch2"
                             ]'
        ReportOnly: false
    secrets:
        AccessToken: ${{ secrets.GITHUB_TOKEN }}