### YamlMime:PowershellCmdlet
summary: |-
  Sets the configuration information for the specified printer.
module: PrintManagement
notes: ""
inputs:
- name: <xref href="Microsoft.Management.Infrastructure.CimInstance#ROOT/StandardCimv2/MSFT_Printer" data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet accepts one printer object.
outputs:
- name: <xref href=" " data-throw-if-not-resolved="False" />
  description: |-
    This cmdlet produces no output objects.
links:
- text: Get-PrintConfiguration
  href: ./Get-PrintConfiguration.yml
syntaxes:
- >-
  Set-PrintConfiguration [-Collate <Boolean>] [-Color <Boolean>] [-DuplexingMode <DuplexingModeEnum>]

   [-PaperSize <PaperSizeEnum>] [-PrintTicketXml <String>] [-PrinterObject] <CimInstance>

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-PrintConfiguration [-Collate <Boolean>] [-Color <Boolean>] [-DuplexingMode <DuplexingModeEnum>]

   [-PaperSize <PaperSizeEnum>] [-PrintTicketXml <String>] [-ComputerName <String>] [-PrinterName] <String>

   [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>] [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
- >-
  Set-PrintConfiguration [-InputObject] <CimInstance> [-CimSession <CimSession[]>] [-ThrottleLimit <Int32>]

   [-AsJob] [-WhatIf] [-Confirm] [<CommonParameters>]
examples:
- title: 'Example 1: Set the default paper size'
  code: |-
    PS C:\> Set-PrintConfiguration -PrinterName "Microsoft XPS Document Writer" -PaperSize A4
  description: |-
    This command sets the default paper size of the printer named Microsoft XPS Document Writer printer to A4.
  summary: ""
- title: 'Example 2: Set the default paper size using print configuration object'
  code: |-
    PS C:\>$PrintConfiguration = Get-PrintConfiguration -PrinterName "Microsoft XPS Document Writer"
    PS C:\> $PrintConfiguration.paperSize = A4
    PS C:\> Set-PrintConfiguration -InputObject $PrintConfiguration
  description: |-
    The first command gets a printer configuration by using **Get-PrintConfiguration**.
    The command stores the result in the $PrintConfiguration variable.

    The second command assigns the value A4 to the **paperSize** property of $PrintConfiguration.

    The final command sets the value of the printer configuration to the modified value of $PrintConfiguration.
  summary: ""
- title: 'Example 3: Set the default paper size of all printers'
  code: |-
    PS C:\>$Printers = Get-Printer * Foreach ($Printer in $Printers){     Set-PrintConfiguration -PrinterName $Printer.name -PaperSize A4}
  description: |-
    This command gets all the printers into a variable $Printers and then loops through all the printers and displays the properties.
  summary: ""
parameters:
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: AsJob
  description: |+
    Runs the cmdlet as a background job. Use this parameter to run commands that take a long time to complete.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="CimSession" data-throw-if-not-resolved="False" /><span>[</span><span>]</span>
  name: CimSession
  description: |+
    Runs the cmdlet in a remote session or on a remote computer.
    Enter a computer name or a session object, such as the output of a [New-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227967) or [Get-CimSession](https://go.microsoft.com/fwlink/p/?LinkId=227966) cmdlet.
    The default is the current session on the local computer.

  defaultValue: None
  position: Named
  aliases: Session
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Collate
  description: |+
    Specifies whether to collate the output of the printer by default.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="Boolean" data-throw-if-not-resolved="False" />
  name: Color
  description: |+
    Specifies whether the printer should use either color or grayscale printing by default.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: ComputerName
  description: |+
    Specifies the name of the computer on which the printer is located.

  defaultValue: None
  pipelineInput: true
  position: Named
  aliases: Computer, CN
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: Confirm
  description: |+
    Prompts you for confirmation before running the cmdlet.

  defaultValue: "False"
  position: Named
  aliases: cf
  parameterValueGroup: ""
- type: <xref href="DuplexingModeEnum" data-throw-if-not-resolved="False" />
  name: DuplexingMode
  description: |+
    Specifies the duplexing mode the printer uses by default.
    The acceptable values for this parameter are:

    - OneSided 
    - TwoSidedLongEdge 
    - TwoSidedShortEdge

  defaultValue: None
  position: Named
  aliases: Duplex, Duplexing
  parameterValueGroup: OneSided, TwoSidedLongEdge, TwoSidedShortEdge
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" />
  name: InputObject
  isRequired: true
  description: |+
    Specifies the input object that is used in a pipeline command.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: ConfigObject
  parameterValueGroup: ""
- type: <xref href="PaperSizeEnum" data-throw-if-not-resolved="False" />
  name: PaperSize
  description: |+
    Specifies the paper size the printer uses by default.
    For valid values, see the Syntax section.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: Custom, Letter, LetterSmall, Tabloid, Ledger, Legal, Statement, Executive, A3, A4, A4Small, A5, B4, B5, Folio, Quarto, Sheet10x14, Sheet11x17, Note, Envelope9, Envelope10, Envelope11, Envelope12, Envelope14, CSheet, DSheet, ESheet, EnvelopeDL, EnvelopeC5, EnvelopeC3, EnvelopeC4, EnvelopeC6, EnvelopeC65, EnvelopeB4, EnvelopeB5, EnvelopeB6, EnvelopeItaly, EnvelopeMonarch, EnvelopePersonal, FanfoldUS, FanfoldStandardGerman, FanfoldLegalGerman, ISOB4, JapanesePostcard, Sheet9x11, Sheet10x11, Sheet15x11, EnvelopeInvite, Reserved48, Reserved49, LetterExtra, LegalExtra, TabloidExtra, A4Extra, LetterTransverse, A4Transverse, LetterExtraTransverse, APlus, BPlus, LetterPlus, A4Plus, A5Transverse, B5Transverse, A3Extra, A5Extra, B5Extra, A2, A3Transverse, A3ExtraTransverse, JapaneseDoublePostcard, A6, JapaneseEnvelopeKaku2, JapaneseEnvelopeKaku3, JapaneseEnvelopeChou3, JapaneseEnvelopeChou4, LetterRotated, A3Rotated, A4Rotated, A5Rotated, B4JISRotated, B5JISRotated, JapanesePostcardRotated, JapaneseDoublePostcardRotated, A6Rotated, JapaneseEnvelopeKaku2Rotated, JapaneseEnvelopeKaku3Rotated, JapaneseEnvelopeChou3Rotated, JapaneseEnvelopeChou4Rotated, B6JIS, B6JISRotated, Sheet12x11, JapaneseEnvelopeYou4, JapaneseEnvelopeYou4Rotated, PRC16K, PRC32K, PRC32KBig, PRCEnvelope1, PRCEnvelope2, PRCEnvelope3, PRCEnvelope4, PRCEnvelope5, PRCEnvelope6, PRCEnvelope7, PRCEnvelope8, PRCEnvelope9, PRCEnvelope10, PRC16KRotated, PRC32KRotated, PRC32KBigRotated, PRCEnvelope1Rotated, PRCEnvelope2Rotated, PRCEnvelope3Rotated, PRCEnvelope4Rotated, PRCEnvelope5Rotated, PRCEnvelope6Rotated, PRCEnvelope7Rotated, PRCEnvelope8Rotated, PRCEnvelope9Rotated, PRCEnvelope10Rotated
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PrinterName
  isRequired: true
  description: |+
    Specifies the printer on which to set the configuration information.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: PN
  parameterValueGroup: ""
- type: <xref href="CimInstance" data-throw-if-not-resolved="False" />
  name: PrinterObject
  isRequired: true
  description: |+
    Specifies the object which contains the printer on which to change the configuration settings.

  defaultValue: None
  pipelineInput: true
  position: "0"
  aliases: Printer
  parameterValueGroup: ""
- type: <xref href="String" data-throw-if-not-resolved="False" />
  name: PrintTicketXml
  description: |+
    Specifies the print ticket XML defining the default print settings for this printer.

  defaultValue: None
  position: Named
  aliases: PrintTicket, PT
  parameterValueGroup: ""
- type: <xref href="Int32" data-throw-if-not-resolved="False" />
  name: ThrottleLimit
  description: |+
    Specifies the maximum number of concurrent operations that can be established to run the cmdlet.
    If this parameter is omitted or a value of `0` is entered, then Windows PowerShell® calculates an optimum throttle limit for the cmdlet based on the number of CIM cmdlets that are running on the computer.
    The throttle limit applies only to the current cmdlet, not to the session or to the computer.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: ""
- type: <xref href="SwitchParameter" data-throw-if-not-resolved="False" />
  name: WhatIf
  description: |+
    Shows what would happen if the cmdlet runs.
    The cmdlet is not run.

  defaultValue: "False"
  position: Named
  aliases: wi
  parameterValueGroup: ""
uid: PrintManagement.Set-PrintConfiguration
name: Set-PrintConfiguration
description: |-
  The **Set-PrintConfiguration** cmdlet sets the printer configuration for the specified printer. 
  Using the **Set-PrintConfiguration** cmdlet, you can manage the configuration of the following features:

  - Collate
  - Color
  - Duplexing Mode
  - N-Up
  - Paper Size

  The **Set-PrintConfiguration** cmdlet also accepts print configuration objects by using the Get-PrintConfiguration cmdlet.

  You cannot use wildcard characters with **Set-PrintConfiguration**.
  You can use **Set-PrintConfiguration** in a Windows PowerShell remoting session.

  You need administrator credentials to use **Set-PrintConfiguration**.
metadata:
  description: Use this topic to help manage Windows and Windows Server technologies with Windows PowerShell.
  external help file: MSFT_PrinterConfiguration_v1.0.cdxml-help.xml
  Module Name: PrintManagement
  ms.date: 12/20/2016
  online version: https://docs.microsoft.com/powershell/module/printmanagement/set-printconfiguration?view=windowsserver2022-ps&wt.mc_id=ps-gethelp
  schema: 2.0.0
  title: Set-PrintConfiguration
